### PR TITLE
[Bugged] Added basic random names functionality | No merge for now!

### PR DESCRIPTION
**Pull request by Ceddini**
Added some random names into the game.

Don't be offended if I left out your name! I will add it, if people like
this small feature :smile:

I would love some feedback, even if it's bad. This is my first real contribution to this game (I don't see my translation as a real contribution xD)

To-Do list:

- [X] Add all contributors
- [X] Fix the localization prefix in the tooltip

I think for my next contribution I want to change this names file to a json file or something like that to incorporate custom descriptions for each person, like in Prison Architect. But I'm not really sure on how to tackle that. So if someone has an idea, i would love to hear it!

### CODE REVIEW

**Comment by RodRitter** [comment]
Awesome!

**Comment by Tranberry** [comment]
Nice :rabbit:

**Comment by Ceddini** [comment]
Just a quick question: Did I add the name correctly? Or is there a better place to set the name of the character?

**Comment by RodRitter** [comment]
Yep, code looks good :)

**Comment by Ceddini** [comment]
Thank you! Then I will add all of the contributors and some random picked names from issues! +Myself, 'cause I'm selfish 😈

And I will try to remove the translation prefix ("en_US_en_US_") of the tooltip to make it look nicer.

**Comment by Ceddini** [comment]
Oh, I also fixed the localization for the selection. If all of this is good, then please merge for now :D

**Comment by RodRitter** [comment]
Good job

**Comment by Ceddini** [comment]
@RodRitter Something didn't work correctly ._. Sometimes, when I created a Character, it would fetch an empty string :(
Could you look into it? I don't really understand what is happening... The file gets loaded correctly and I don't believe that my Random.Range is wrong...

**Comment by RodRitter** [comment]
I'll take a look

**Comment by Ceddini** [comment]
@RodRitter Found the problem. My Regex filter (or however it is called) was wrong. I just need "\r\n" instead of "\r|\n|\r\n".
And my Random Range was also wrong, because I forgot that the max value is not in the list of possible outcomes. so I don't need the -1.

I'll make a new PR for the fix.

**Comment by RodRitter** [comment]
Yep found that too. Create a new PR with that fix and I'll merge it.

**Comment by Mizipzor** [comment]
This is awesome. :)
How did you create the list? Can you ask Github for a list of contributors?

**Comment by Ceddini** [comment]
@Mizipzor You can see all contributors under the tab Graphs next to the pull requests

**Comment by Mizipzor** [comment]
@Ceddini Cheers!

**Comment by Ceddini** [comment]
@RodRitter Created the PR

**Comment by Ceddini** [comment]
@RodRitter No I didn't... I created the PR on my fork...

**Comment by RodRitter** [comment]
Ok link it here when you're done

**Comment by Ceddini** [comment]
@RodRitter #405 This should be it

**Comment by Ceddini** [comment]
@RodRitter I had do delete my local files and redownload them, because something messed up pretty hard...

**Comment by Ceddini** [comment]
@RodRitter I really don't want to ask it in the issues section, because I think it doesn't contribute very much, but I still want to ask it, so: 
How often would be a sensible amount to update the names.txt? I created myself a little scripts that gets all the contributors through the GitHub API, so it's very easy for me to do it, but I still need to know how often is too much 😄

**Comment by Tranberry** [comment]
Know jack **** I would perhaps update weekly, that way you won't be crying for more than six days and about 23,9 hours.

**Comment by Ceddini** [comment]
@Tranberry Could you please elaborate what you mean? I really don't get it. I just asked how often I should update it, so that every contributor get's his name in the game but without spamming the PRs... This was an honest question so I really don't understand what you mean...

**Comment by Tranberry** [comment]
@Ceddini  I'm basically trying to say: I don't know what will be considered spam, but I don't see why it have to be updated with a higher frequency than once a week if it's just adding some names and not being a major change.

**Comment by Ceddini** [comment]
@Tranberry Okay thank you. The problem with your statement was the crying part that I didn't understand and this somehow felt aggressive which I really couldn't understand, because I'm completely new to game development, working in teams and working on such a scale, so I just wanted to know what would be considered correct, so that I am ably to learn more about such projects.
But I still am grateful for your help

**Comment by Tranberry** [comment]
Sorry, I'm tired and tried to not be serious for once. You are doing good work, and I'm happy that you are involved in this project :kiss:

**Comment by RodRitter** [comment]
@Ceddini As long as you're not spamming, then it doesn't matter. If you're spamming too often then your PR's simply won't be accepted. Also if you look at issue #513 that Quill has just posted, you might want to look into that first.

**Pull request merged**
