### PR TITLE
Contributor name script

### PR DESCRIPTION
**Pull request by kd7uiy**
This python script generates the standard list of Character Names, which should be used for all future updates to the Character Names list

### CODE REVIEW

**Comment by mikejbrown** [comment]
Why not [str.capitalize()](https://docs.python.org/3/library/stdtypes.html#str.capitalize) (also in 2.7)?

**Comment by kd7uiy** [comment]
Because I didn't know that existed... Sigh.

**Comment by sboigelot** [comment]
Would it be possible to add in the script an array that override default names? I would prefer having my surname in the game instead of the compress version of my fullname as username. That would be a great addition!

**Comment by mikejbrown** [comment]
@kd7uiy  No worries. It's a big standard library. If you find yourself wanting to do something that seems like it should be pretty common, do a quick search of the library reference. It's probably in there! :grinning:

**Comment by kd7uiy** [comment]
I did, which lead me to a SO question, with that code... Sigh.

As far as the exceptions, it can be done, I don't think we should do that for the base version. I'll think about it...

**Comment by mikejbrown** [comment]
Another future TODO might be to call this on game load to always fetch the latest list...

**Comment by kd7uiy** [comment]
The last could in theory be done, but I'd rather not have a web dependency to start the game. Plus, running the script takes a few seconds. Lastly, I don't want to pound the Github API. Making it as part of the build process might be a good idea, but that's as far as I would go.

**Comment by sboigelot** [comment]
I'm with @kd7uiy, let's not add download at game start, we should already get rid of the one that downalod localisation, but that's another topic :)

**Comment by mikejbrown** [comment]
I was about to say doesn't the localisation already do that.. :grinning: 

Could always do some caching.

**Comment by kd7uiy** [comment]
I was trying to figure out why I didn't see the localization files in my branch! 

Honestly though, for now it doesn't matter much, and when it does matter, the list will be pretty constant, so...

**Comment by sboigelot** [comment]
@kd7uiy check #1197 for more info

**Pull request merged**
