### PR TITLE
Power system - on update rework

### PR DESCRIPTION
**Pull request by TheRiven**
Ok, now that I can actually work on this again.

I have moved the power system check from the furniture update function to its own function so that it is no longer used by ALL the furniture. This function can instead be used in the Lua code for furniture to check if it has power.

This will allow alternative behaviour to be scripted in Lua for if the furniture has power or not.

Once again the only furniture using this at the moment is the oxygen generator.

### CODE REVIEW

**Comment by TheRiven** [comment]
hrm, i guess that's what i get for messing around in git to fix my button issue

**Comment by TheRiven** [comment]
Right, I guess I will put this on hold until I get that commit list cleaned up

**Comment by vogonistic** [comment]
@TheRiven Do you want some help with sorting out the PR or are you working on improving the feature?

**Comment by TheRiven** [comment]
@vogonistic I would definitely welcome a point in the right direction, I am currently trying to get my head around the rebase command as that has been mentioned a few times in other PRs but I don't fully understand how it works and what it will clean up or keep.

I was planning on waiting for Quills next git video he said should be out today as this might help make git click for me, but if I can get it solved by then all the better.

**Comment by TheRiven** [comment]
Ok I am sort of there, but now I cannot sync without saving those font licence files again... and it won't delete them or ignore them. :confused:

**Comment by Mizipzor** [comment]
You should redo this to get rid of the font files. Unless you rebase and squash but redoing is probably easier. I dont know if it's obvious, but in Git you dont _have_ to commit all changed files. The font files will show up as changed until its fixed, but you can work just fine. Just dont commit them.

**Comment by TheRiven** [comment]
@Mizipzor That's the problem, I cannot sync unless I commit the files and I cannot seem to discard them.

github-sync-issue

**Comment by TheRiven** [comment]
@Mizipzor As you say in #254 I may need to nuke again and start over, its only a few lines in 2 files that I have actually changed. But I may wait until #187 has been taken in so I can hopefully top having to deal with those licence files.

**Comment by Mizipzor** [comment]
I have no idea why the desktop client would show that error, that makes no sense to me. I just assume that if I sync and I have uncommitted changes they would be discarded. What if you open a git terminal there and do `git checkout --force master`? That should delete uncommited changes. You can also checkout our branch. Be careful, as i said this reverts uncommitted changes.

**Comment by TheRiven** [comment]
Well git checkout --force master does move me to the master, but when I go back to the branch it still shows the commits have not been synced. I cannot see the licence files at this point but once i try syncing again it shows that error again and the files reappear.

**Comment by Mizipzor** [comment]
How about recreating your clone entirely? Copy paste your (changed) files to desktop or something. Delete everything, both on Github and locally. Then refork, download, create a branch, paste your changes, commit and push. I did this _a lot_ when learning Git due to constant fuck ups. ^^

**Comment by TheRiven** [comment]
Ahhh that worked, #257 now only has that one commit. Its no longer forcing me to do something with those licence files although they do still show up, hopefully that will be fixed soon.

**Comment by JosephBywater** [comment]
Nice :+1:

**Comment by TheRiven** [comment]
@Mizipzor Thanks for the help!

**Comment by Mizipzor** [comment]
@TheRiven Great success!

**Pull request closed without merging**
