### PR TITLE
Prevent scrolling when settings/options menu is open

### LINKED ISSUE #449: [Bug] Options and Settings Menu doesn't prevent scrolling
unlike the save and load dialogs, options and settings have no fullscreen image as their root and don't pause other input like scrolling

### PR DESCRIPTION
**Pull request by Randshot**
Fixes #449 
I also replaced any tabs with spaces :)

### CODE REVIEW

**Comment by benji7425** [comment]
You monster.

**Comment by Randshot** [comment]
?

**Comment by benji7425** [comment]
Replacing all tabs with spaces, how could you... Tabs always!

**Comment by RodRitter** [comment]
Good job. Merged.

**Pull request merged**
