### PR TITLE
Mod manager

### LINKED ISSUE #1713: Mod Selector and Saving
I'm working on a mod selector, are these good features?
* Selection menu
* JSON mod data
* ~image~, title and description
* active mods saved in save file and settings
* ~`graphical` setting makes mod not get saved with save file and load after other mods~
* Load order editable in mod selection menu
* `doNotSave` bool makes mod not be included in save

### PR DESCRIPTION
**Pull request by Dan54**
[Test Mods.zip](https://github.com/TeamPorcupine/ProjectPorcupine/files/671944/Test.Mods.zip)
### The issue this fixes

Closes #1713 

### What this PR does

* Mod selection menu
* JSON mod data
* Mod title and description
* Active mods saved in savefile and settings
* Load order editable in mod selection menu
* `doNotSave` bool makes mod not be included in save
* `bool ModUtils.IsModLoaded(string modName)`

### Images

modmenu
mod warn
### TODO
- [x] Make which button goes with which mod clearer
- [x] State which mods are needed
- [x] Fix `doNotSave`
- [x] Add `ModUtils.IsModLoaded(string modName)`
- [x] Fix booting from load

### CODE REVIEW

**Comment by NogginBops** [comment]
Looks like it could be quite hard to identify which button belongs to which mod.

**Comment by bjubes** [comment]
the dialog for confirming loading a save with mods should probably list the mods missing so the user can know whats missing and download them if they need to.

**Comment by BraedonWooding** [comment]
Note if you have changed UI (just going by the UI Alterations/Show Inactive mods in prompt commits) then update the images (just so anyone new coming along, or people seeing the progress can see the latest version at a glance) :D.  Looking good though!

**Comment by Dan54** [comment]
The images have been changed

**Comment by koosemose** [comment]
If you could add some sample mods, that would greatly aid testing this PR.

**Comment by koosemose** [comment]
Just saw you added test mods. For future reference, when you update the post with something relating to a concern with the PR, you should add a comment that it has been done, I don't get updates on an updated post, so it will end up waiting until I happen to check in on the PR and happen to notice it otherwise.

**Comment by koosemose** [comment]
So this doesn't do anything to actually load the mods?

Also it breaks starting the game directly from the _World scene, which is an important thing to be able to do for development.
```
NullReferenceException: Object reference not set to an instance of an object
ModsManager.LoadDirectoryAssets (System.String directoryName, System.Action`1 readDirectory) (at Assets/Scripts/Models/InputOutput/ModsManager.cs:225)
ModsManager.LoadSharedFiles () (at Assets/Scripts/Models/InputOutput/ModsManager.cs:111)
ModsManager..ctor () (at Assets/Scripts/Models/InputOutput/ModsManager.cs:17)
WorldController.OnEnable () (at Assets/Scripts/Controllers/WorldController.cs:68)
```

**Comment by Dan54** [comment]
I was unable to rebase.

**Comment by bjubes** [comment]
I quickly tried to see if I could rescue this branch on my own and remove the commits from master. (here)[https://github.com/TeamPorcupine/ProjectPorcupine/compare/master...bjubes:Dan54-mod-manager2?expand=1] is the pr diff. It it looks correct you can try the following to get the same result
1. pulling in the latest master from upstream
2. creating a new branch from master
3. merging in this branch
4. if all goes well, submit the new branch as a new PR.

That should remove the changes on master from being included in your PR. I'm not sure if that will completely fix all unintentional changes but its at least a partial fix.

**Comment by koosemose** [comment]
Your latest commits seem to be reverting a large number of recent commits to master.

**Comment by koosemose** [comment]
Closing this as the commits have gone off the rails, drastically negatively affecting the code base, and should not be merged in anything near its current state, and most likely needs to be redone from the ground up.

**Pull request closed without merging**
