### PR TITLE
[WIP] Animated character xml fil

### PR DESCRIPTION
**Pull request by Raketfart**
All Y Positions were wrongly from the top down. Now they are correct from bottom up.

### CODE REVIEW

**Comment by Mizipzor** [comment]
Pulled this branch to test it. But what is currently animated? Is there anything?

**Comment by Raketfart** [comment]
Nothing yet. I'm adding a WIP character animation soon

**Comment by Tranberry** [comment]
@Raketfart I'm rooting for you! :kiss:

**Comment by Raketfart** [comment]
Sorry, if this PR should have been part of #669
I didn't know if someone else was going to do character animation, and this PR would help them (as my first file was wrong)

**Comment by Mizipzor** [comment]
It almost always better to have many small pull requests instead of one large. But you are free to structure this however you want. :)

**Comment by Raketfart** [comment]
Not relevant anymore

**Pull request closed without merging**
