### PR TITLE
Small dragging fix

### LINKED ISSUE #469: [Bug] Drag area holds when letting go over UI elements
It's a bit hard to see from this, , but I will say that I let up on the dragging over the UI element. Once released, the dragging is still functional in visual, but doesn't actually do anything.

gif

### PR DESCRIPTION
**Pull request by Randshot**
Fixes #469

### CODE REVIEW

**Comment by bjubes** [comment]
FYI for future: If you write "fixes 469" in the commit message, github will notice and automatically tag the issue and close it when this PR gets merged.

**Comment by Randshot** [comment]
Oh, tanks, didn't know :)

**Comment by RodRitter** [comment]
Need to solve this merge conflict and then I'll merge it in.

**Comment by Randshot** [comment]
Ok, was sleeping. Will do that right away.

**Comment by Randshot** [comment]
@RodRitter I think I resolved the conflicts :)

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
