### PR TITLE
Images in construction menu

### PR DESCRIPTION
**Pull request by sboigelot**
Use the default floor & furniture sprite in construction menu
Also add a bulldozer image (created by hand so no licence issue)

image

### CODE REVIEW

**Comment by TomMalbran** [comment]
Cool. Now we need to get rid of the ugly buttons and have a cool background.

A couple of things, for now or later:
1. When the name of the item is too long and occupies 2 lines it is placed partially on top of the image. We need o increase the size.
2. Images that are not square look bad. Should we have a different image for the menu?
3. Should we just show the images and have the names as tooltips?

**Comment by sboigelot** [comment]
@TomMalbran I mostly agree with you

> 1. When the name of the item is too long and occupies 2 lines it is placed partially on top of the image. We need o increase the size.

I do not wish to change too much the construction menu while it's still having some pending PR

> 2. Images that are not square look bad. Should we have a different image for the menu?

We should change the stretch mode of the image not to fill the full square, but I have no idea how.

> 3. Should we just show the images and have the names as tooltips?

I would disagree here, the images are not representative enough. For instance, take the steal wall :/

**Comment by vogonistic** [comment]
This is a great idea! In a future PR I think we need to add support for a custom image for things like doors, floors and walls.

**Comment by bjubes** [comment]
Getting some errors with the new master:
```
Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs(188,38): error CS0117: `SpriteManager' does not contain a definition for `current'
Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs(154,42): error CS0117: `SpriteManager' does not contain a definition for `current'
```

**Comment by sboigelot** [comment]
@bjubes I'll check that now

**Comment by sboigelot** [comment]
@bjubes I updated the code to the new SpriteManager API

**Pull request merged**
