### PR TITLE
Added a Non-deconstructible tag for mining ores

### LINKED ISSUE #1237: Deconstructing mine ore?
I just noticed that I could deconstruct mine ore. That seems a bit odd to me... It seems like the deconstruct option for the ore should be the same as the mining option, convert it in to something more useful.

### PR DESCRIPTION
**Pull request by TomMalbran**
I am similar fashion to the Non-buildable Tag, when something is Non-deconstructible you can't right click to deconstruct it or use the Deconstruct furniture button. The furniture can be deconstructed in other fashions, like for ore, when it is mined. And as said, I added this mainly for the ores, since it wasn't right to have the option to deconstruct it, you can only mine it.

Fixes #1237

### CODE REVIEW

**Comment by ComputerOverlord** [comment]
I didn't realize right click deconstructed

**Comment by TomMalbran** [comment]
@ComputerOverlord Not exactly right click, but Right click opens a context menu which has an option to deconstruct.

**Comment by kd7uiy** [comment]
Fixes #1237

**Comment by koosemose** [comment]
Your TypeTags don't match, in one spot you're looking for Non-deconstructible, and in the other you're looking for Non-destructible.

**Comment by sboigelot** [comment]
This branch has conflicts that must be resolved

**Comment by TomMalbran** [comment]
Conflicts Fixed

@koosemose I was reading your comment and I remembered fixing that, after creating the PR, but I forgot to push that commit.

**Pull request merged**
