### PR TITLE
Cancel job on furniture decontruct

### PR DESCRIPTION
**Pull request by BeefEX**

### CODE REVIEW

**Comment by lameox** [comment]
Another suggsetion: Most of your commit is now in two pullrequests: #56  and this one.
You can, and should: 
- commit merge these changes here into your master branch
- git squash your add and revert of the ProjectSetting.asset 

By doing this, your pullrequest #56 is updated, and you can close this one. also you will not commit two basically unnecessary commits to master.

Hope i could help you ;)

**Comment by BeefEX** [comment]
How can i do that. Not very familiar with git yet.

**Comment by lameox** [comment]
So what you basically do is:
  1. Open github desktop
  2. switch to your master branch
  3. Click Compare -> cancelJobOnFurnitureDecontruct in the top left
  4. Click update from cancelJobOnFurnitureDecontruct
  5. Close github desktop. What you did is called a merge. Your master is now up to date with your cancelJobOnFurnitureDecontruct branch. Now comes the tricky part.
  6. open git bash or any other git command line (you might need to install one. i recommend [this](https://git-scm.com/downloads) one)
  7. type git rebase -i Head~4
  8. a textdocument now opens. it should have your last 4 commits, one per line, each starting with the word "pick"
  9. For all lines except the first, change the pick to a squash
  10. save and close
  11. reopen github desktop and sync with github
  12. Check, that the pullrequest #56 is now correctly updated and delete this one as it is no longer necessary.

If you need any more help, feel free to ask.

**Comment by JosephBywater** [comment]
@lameox In issue #20 @quill18 mentioned that it auto squashes commits when you merge them with a PR. Although I suppose it doesn't do harm to squash them yourself :)

**Comment by BeefEX** [comment]
@JosephBywater i had to learn it anyway :D

**Comment by BeefEX** [comment]
@lameox thanks for help

**Comment by lameox** [comment]
Ah i was not sure if @quill18 had autosquashing turned on. Well i guess in that case you can just do 1. to 5.

**Comment by BeefEX** [comment]
Joined this with #56 closing this one.

**Pull request closed without merging**
