### PR TITLE
License headers 

### PR DESCRIPTION
**Pull request by WardBenjamin**
This pull request is a WIP, do not merge.

Right now, this removes Quill's old license headers. I propose replacing them with something like this (modeled off of the GPL header thing at the bottom of the LICENSE file):

```
// ====================================================
// Project Porcupine Copyright(C) 2016 Team Porcupine
// This program comes with ABSOLUTELY NO WARRANTY; This is free software, 
// and you are welcome to redistribute it under certain conditions; See 
// file LICENSE, which is part of this source code package, for details.
// ====================================================
```

Opinions? Any modifications that should be made?

### CODE REVIEW

**Comment by vogonistic** [comment]
"Team Porcupine" probably needs a legal definition if it is going to be referenced in copyright clause.

**Comment by bjubes** [comment]
I think the license in the root dir covers all the scripts legally so no header is needed. Removing headers is on quills to do list. See #35

**Comment by WardBenjamin** [comment]
@quill18 If you don't want any new headers, this can be merged as-is, since it removes all of the old headers already.

**Comment by Mizipzor** [comment]
There a StyleCop rule that enforces headers that's currently turned off. If this goes through I'll turn it on. Even though I'm the only one using StyleCop at the moment. ^^

**Comment by quill18** [comment]
This is exactly the kind of header I want. Go for it!

**Comment by vogonistic** [comment]
@WardBenjamin Don't forget to finish this PR

**Comment by Mizipzor** [comment]
@vogonistic Wouldnt this be a great beginner task though? This is probably _the_ easiest change there is. No coding required.

**Comment by WardBenjamin** [comment]
Aaand I messed up the commit history
10/10

**Comment by Mizipzor** [comment]
@WardBenjamin Do you need help with the Git wrangling? :)

**Comment by WardBenjamin** [comment]
@Mizipzor naw, I got it. Working on it now :P

**Comment by WardBenjamin** [comment]
@Mizipzor look good now?

**Comment by WardBenjamin** [comment]
(and the conflicts begin)

**Comment by Mizipzor** [comment]
@WardBenjamin Flawless! One commit to remove, another to add. Couldnt be cleaner. :) Good job!

**Comment by WardBenjamin** [comment]
@quill18 we should be good to go on this now!

**Comment by quill18** [comment]
You missed #region License in BuildModeController.cs, if you want to be consistent.

**Comment by quill18** [comment]
Although honestly I'm not sure there's much value to regioning the copyright header.

**Comment by WardBenjamin** [comment]
@quill18 Fix'd. The only real reason that I did this is because VS collapses them by default, so I don't have to look at them more than the one line that it shows while I'm programming.

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
