### PR TITLE
Tidies lua scripts a bit

### PR DESCRIPTION
**Pull request by mikejbrown**
- Inserts license headers
 - Makes ModUtils accessible from GameEvent.lua and Quest.lua
 - A few useful log messages (not spammy)

 ...

 - And the best character name yet

### CODE REVIEW

**Comment by mikejbrown** [comment]
Note this does absolutely nothing to address #796

**Comment by Mizipzor** [comment]
Conflicts already? This project is moving quick.

**Comment by mikejbrown** [comment]
:laughing: Of course there are!

**Comment by Mizipzor** [comment]
Tested. Game starts without errors.

**Pull request merged**
