### PR TITLE
Cleaning the code

### PR DESCRIPTION
**Pull request by simonlary**
- Removed all the code that was commented during the YouTube tutorials, notably the "pre-LUA" FurnitureActions and the CreateFurniturePrototypes.

- Removed commented C# code in the LUA file

- Removing old variables and functions not used anymore like RandomizeTiles() in World.cs

- Removing some unnecessary Debug.Log() that were spamming the console, slowing the game and making debugging more difficult.  #94

### CODE REVIEW

**Comment by quill18** [comment]
This branch has conflicts that must be resolved.

Changing 24 files so dramatically is almost always going to lead to many merge conflicts in fast-changing project like this.  It's probably a good idea for you to update your repo and re-submit the cleaning one file at a time.

**Comment by bjubes** [comment]
A bit confused on what closing a PR does? Can the author reopen it once they fix their code or is it closed for good?

**Comment by Mizipzor** [comment]
@bjubes It can be reopened, but it might be simpler to just create a new one. Or rather several new ones, as the problem here was the the changes were too many.

**Comment by simonlary** [comment]
Ok, i didn't think it would lead to many conflicts since i was mostly changing unused and commented parts. I will make smaller changes on different PR next time, sorry.

**Pull request closed without merging**
