### PR TITLE
Fixed XML files layout

### PR DESCRIPTION
**Pull request by Grenkin1988**

### CODE REVIEW

**Comment by TomMalbran** [comment]
So the standard in XML is 2 spaces instead of 4 that we use in every other type of file?

**Comment by Grenkin1988** [comment]
@TomMalbran You are right. Fixed to be 4 spaces.

**Comment by dusho** [comment]
so it should be 4 spaces afterall? just now changed it to 2 from 4.. to fit furniture.xml.. so putting it back, I guess

**Comment by TomMalbran** [comment]
I think 4 is the best. Makes it easier to read and is the same for all the files. Also in editor that support xml, you don't need to change the settings just for those files.

@Grenkin1988 Should we also change all the attributes to camelCase? There are a few that are in PascalCase. And all the Tag names to PascalCase, Trader.xml has some as camelCase.

**Comment by Grenkin1988** [comment]
@TomMalbran Yes. But not in this go. Create issue and I or somebody will do this

**Comment by TomMalbran** [comment]
Here is the issue #664, which was closed but never fixed.

**Comment by Grenkin1988** [comment]
@TomMalbran Reopened

**Comment by Grenkin1988** [comment]
Should go after #1229

**Comment by vogonistic** [comment]
👍

**Comment by koosemose** [comment]
All good. Merged.

**Pull request merged**
