### PR TITLE
Fix context actions from lua

### PR DESCRIPTION
**Pull request by kd7uiy**
There is an unusual bug that this fixes that is caused by the "Action" being placed in the same piece of memory for each object yielded. The bottom line is, only the second action was possible. I'm not sure why this is the case, and I tried many means to force the two to occupy different pieces of memory, but I failed. This workaround, however, works well, and it can make it easier to debug such issues in the future.

### CODE REVIEW

**Comment by koosemose** [comment]
Looks good, fixes the context menu problem, no new bugs seem to have cropped up, and stylecop clean. Merged.

**Comment by TomMalbran** [comment]
BTW the workshop context menu actions had a similar issue when they were being worked with and the solution was to move the creation to a new function:
```
if (IsWorkshop && workshop.WorkshopMenuActions != null)
         {
             foreach (WorkshopContextMenu factoryContextMenuAction in workshop.WorkshopMenuActions)
             {
                 yield return CreateWorkshopContextMenuItem(factoryContextMenuAction);
             }
         }
```
The same can be done with the normal Furniture Actions.

**Comment by kd7uiy** [comment]
I'm all for a better solution, if you want to do it. I'm burned out on the issue for today...

**Comment by TomMalbran** [comment]
Sure I can try if that solves it. It was a weird bug. Is a Scope issue and wasn't solved by saving variables in the scope. @dusho had an issue with it, and we tested a few variants until I went with the solution that I knew that will work and tried with a function.

**Comment by dusho** [comment]
Yes, I think it is old Mono bug. According to Unity blog this was fixed for Unity 5.4 (now in beta) as a first step to bring newer .Net to Unity.

**Comment by kd7uiy** [comment]
I'm running 5.4 and found the issue. I assume you mean 5.5?

**Comment by dusho** [comment]
Yep. 5.5 , sorry.
Details: http://forum.unity3d.com/threads/upgraded-c-compiler-on-5-3-5p8.417363/

**Pull request merged**
