### PR TITLE
Fixes the HeadlineGenerator so tests run in Monodevelop

### PR DESCRIPTION
**Pull request by mikejbrown**
Currently the HeadlineGenerator and its test suite depend on UnityEngine
both for its random number generator and for Debug.Log. This means the
tests run fine in the Unity editor but fail in an IDE like Monodevelop
(and I'm guessing probably VS as well).

This issue is easily fixed by using System.Random and disabling logging
during unit tests.

The code in `ResetNextTime` is based on [this stackoverflow post](https://stackoverflow.com/questions/3365337/best-way-to-generate-a-random-float-in-c-sharp/3365374#3365374).

### CODE REVIEW

**Comment by sboigelot** [comment]
This branch has conflicts that must be resolved

**Comment by mikejbrown** [comment]
Resolved conflicts.

**Comment by bjubes** [comment]
When merging in current master, im gettings T01 and T02 failing in HeadlineGeneratorTests.cs
```
---
UnityEngine.MissingReferenceException : The object of type 'CanvasGroup' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
---
at (wrapper managed-to-native) UnityEngine.CanvasGroup:set_alpha (single)
at HeadlineController.UpdateHeadline (System.String newHeadline) [0x00000] in C:\Users\Brian\Documents\Unity\ProjectPorcupine\Assets\Scripts\UI\HeadlineController.cs:51
at HeadlineGenerator.OnUpdatedHeadline (System.String headline) [0x00012] in C:\Users\Brian\Documents\Unity\ProjectPorcupine\Assets\Scripts\Models\Events\HeadlineGenerator.cs:75
at HeadlineGenerator.OnUpdatedHeadline () [0x0005c] in C:\Users\Brian\Documents\Unity\ProjectPorcupine\Assets\Scripts\Models\Events\HeadlineGenerator.cs:66
at HeadlineGenerator.<ResetNextTime>m__37 (Scheduler.ScheduledEvent incomingEvent) [0x00000] in C:\Users\Brian\Documents\Unity\ProjectPorcupine\Assets\Scripts\Models\Events\HeadlineGenerator.cs:86
at Scheduler.ScheduledEvent.Fire () [0x0003c] in C:\Users\Brian\Documents\Unity\ProjectPorcupine\Assets\Scripts\Models\Scheduler\ScheduledEvent.cs:248
at Scheduler.ScheduledEvent.Update (Single deltaTime) [0x00013] in C:\Users\Brian\Documents\Unity\ProjectPorcupine\Assets\Scripts\Models\Scheduler\ScheduledEvent.cs:230
at Scheduler.Scheduler.Update (Single deltaTime) [0x0006c] in C:\Users\Brian\Documents\Unity\ProjectPorcupine\Assets\Scripts\Models\Scheduler\Scheduler.cs:183
at HeadlineGeneratorTest.T01_1s_No_Generation () [0x00007] in C:\Users\Brian\Documents\Unity\ProjectPorcupine\Assets\Editor\UnitTests\Controllers\HeadlineGeneratorTest.cs:49
```

**Comment by mikejbrown** [comment]
That should fix it. There is an odd interaction between the HeadlineGenerator unit test and the Unity UI elements. Basically, if you play the game in the Unity editor, then close it out and then rerun the tests it complains because the canvasGroup it is expecting to find is no longer there. Not exactly sure why the tests work initially... :confused:  In any case, adding a null check in UpdateHeadline fixes the problem.

**Pull request merged**
