### PR TITLE
UI Right Menu background

### PR DESCRIPTION
**Pull request by Ohda**
Another suggestion for temporary better.
I've used the menu construction background image.

### CODE REVIEW

**Comment by sboigelot** [comment]
You lost text space:
image

Also you should probably flip the texture vertically.

**Comment by Tranberry** [comment]
I would reflect or flip the UI elements

**Comment by TomMalbran** [comment]
That looks better.

For the future I was thinking that the bottom menu which shows information on mouse move could not have any background or just a semitransparent black, but in a way which it doesn't get too much attention. And the selection menu can pop on top of that menu (hiding it before), and it can have an x to unselect the stuff. RimWorld does something similar with the menus on the left.

**Comment by koosemose** [comment]
Looks good. Merged.

**Pull request merged**
