### PR TITLE
Specify Coding Style for Contributions according to #182

### PR DESCRIPTION
**Pull request by Dormanil**
Fixed some ambiguity in the Style Guidelines and added @lameox's TL;DR for our coding style.

### CODE REVIEW

**Comment by lameox** [comment]
I like the new wording

**Comment by QuiZr** [comment]
There is `this` keyword, should we really use underscores in private fields?

**Comment by lameox** [comment]
I think it really helps when you read a function body because nobody will specify a this for every variable they use and with the underscore you can easily see what modifies object state and what just changes local variables.

**Comment by behindcurtain3** [comment]
Looks good!

**Comment by Mizipzor** [comment]
What's the reason for using underscores as a prefix for fields? I was under the impression that we were using the default [Microsoft style](https://msdn.microsoft.com/en-us/library/ms229002(v=vs.110).aspx), specifically for this would be the [Naming of type members](https://msdn.microsoft.com/en-us/library/ms229002(v=vs.110).aspx):

> X DO NOT use a prefix for field names.

I would strongly advice against coming up with a custom style. Writing an example class is a good idea. But link to the Microsoft style and follow that. This is one of the holy wars we dont want to start here.

**Comment by vogonistic** [comment]
Hmm, can you update the styles to indicate that this is `lowerCamelCase` and this is `CamelCase`

**Comment by NogginBops** [comment]
@vogonistic Actually this is `camelCase` and this is `PascalCase`.

**Comment by lameox** [comment]
Actually its PascalCase and camelCase but i guess that is not really important to the topic :D

@Mizipzor oh i had thought microsoft would advise doing the same as their .Net Core people advise [here](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md). I found that coding style the easiest to understand quickly. 

But i guess we can also do it like in the msdn documentation as long as we reach a consensus and have a unified style.

**Comment by Dormanil** [comment]
@Mizipzor Microsoft also states in the same style document:

> The field-naming guidelines apply to static public and protected fields. Internal and private fields are not covered by guidelines, and public or protected instance fields are not allowed by the member design guidelines.

Since only private fields start with an underscore, we still comply with.

**Comment by lameox** [comment]
@Dormanil thank you for going over the guidelines and looking for that. Would have been weird if they contradicted themselves. I propose we use their underscore policy for private fields so we get a ruleset with less ambiguity

**Comment by vogonistic** [comment]
I stand corrected.

**Comment by Mizipzor** [comment]
@lameox what you linked is good. My main concern here is linking to something existing and not to try and author our own standard. It's not worth the effort. The style is not that important. But it is important that is concise and very well documented. 

How about using the default settings for StyleCop? I think they are close to that.

**Comment by lameox** [comment]
@Mizipzor i just wanted to suggest a more or less official approach from microsoft that i can attest to. I think the .Net Core team also provides a custom Setting file for StyleCop. Will have to look into that though. 

But if the standard Settings are similar then why bother. I think your idea is simpler. Would running Stylecop with defaults still autogenerate the file in the assets folder?

**Comment by Dormanil** [comment]
Sooo... what would the final style be then, so that I can fix the TL;DR example code in this PR?

**Comment by Mizipzor** [comment]
@lameox I'm not sure I understand, what file do you expect to be generated? StyleCop runs some checks and gives you what looks like compiler warnings, lines the violate the coding standard.

**Comment by Dormanil** [comment]
@Mizipzor I guess he means the StyleCop Settings in the Assets folder you are currently requesting to be pulled in #158.

**Comment by lameox** [comment]
@Mizipzor yup. i referred to the file @Dormanil mentions. Is this file generated with standard settings? if not we can solve 2 issues at once...

**Comment by Mizipzor** [comment]
The file is generated, and default settings would be an empty file. You specify overrides from the defaults. In my pull request I've added some overrides based on what the code currently looks like. For example, we don't appear to require methods to be documented.

**Comment by NogginBops** [comment]
Shouldn't it be ``//Use camelCase unless otherwise stated`?

**Comment by Dormanil** [comment]
Yes, yes it should. 

I also still need a concise answer as to the question of the underscore as a prefix to private fields.

**Comment by NogginBops** [comment]
To me underscores before fields are just ugly and don't really make anything more understandable, though some people might disagree. I tend to go for a camel case approach.

**Comment by koosemose** [comment]
I also agree that the leading underscore doesn't make things any more clear, with the exception of how quill has used a leading underscore so far (though I'm not absolutely sure he has used it completely consistently), where the field is backing a property (such as with the _Name field and Name property in Furniture.cs, if used consistently, I think that would provide a pretty clear signal that you shouldn't be using that field directly (even from within the class), and rather use the associated property.

**Comment by Dormanil** [comment]
I liked it that way as well, when a field has backed a property. I think this would be a good compromise between underscores nowhere and underscores everywhere -- underscores where they make the most sense.

**Comment by quill18** [comment]
Looks good!

And yes, I feel that the underscores are really best saved as indicators of "don't touch this directly" (i.e. backing a property), rather than used for all privates as some standards do.

**Comment by quill18** [comment]
Merged -- though I always preferred the term CamelCase to PascalCase.

**Pull request merged**
