### PR TITLE
Added threshold before panning starts

### PR DESCRIPTION
**Pull request by NoobPete**
Added threshold before panning starts, should make it a bit easier to right click objects.

### CODE REVIEW

**Comment by quill18** [comment]
Good idea, but this PR now conflicts.

**Comment by Randshot** [comment]
@NoobPete Don't forget to change the title ;)

**Comment by NoobPete** [comment]
@Randshot It's not done, I messed up in git, it's totally broken now... :p

**Comment by Mizipzor** [comment]
@NoobPete if you cant recover, starting over is always an option. :)

**Comment by NoobPete** [comment]
@Mizipzor yeah, but you should be able to do it inside git. I think it should be okay now. :)

**Comment by RodRitter** [comment]
Awesome. Works great. Merged.

**Pull request merged**
