### PR TITLE
Add localization text rescaling

### PR DESCRIPTION
**Pull request by Fogsight**
Automatically scales any text and its text box to fit completely within its anchors.

### CODE REVIEW

**Comment by Fogsight** [comment]
localization text rescaling

**Comment by WardBenjamin** [comment]
Looks great!

**Comment by Mizipzor** [comment]
Nice. I would've assumed that you had to resize the buttons, and risk screwing up the layout, but reducing the size of the font is a great compromise.

**Comment by SanteriHetekivi** [comment]
Great this fixes problem I stated in issue #164. :)

**Comment by Fogsight** [comment]
@Mizipzor, yes, but actually without resizing the font. Main reason I wanted to do it this way is to avoid "Best Fit" growing atlas out of control as described here: https://twitter.com/pgmuscat/status/763164207495933952

**Pull request merged**
