### PR TITLE
[On Hold] Remove SharpZipLib

### PR DESCRIPTION
**Pull request by hcorion**
This was a requirement of LocalizationDownloader but is no longer necessary after PR #1647 .

### CODE REVIEW

**Comment by koosemose** [comment]
This broke something:
```
-----CompilerOutput:-stderr----------
Assets/Scripts/Localization/LocalizationDownloader.cs(13,7): error CS0246: The type or namespace name `ICSharpCode' could not be found. Are you missing a using directive or an assembly reference?
Assets/Scripts/Localization/LocalizationDownloader.cs(13,7): error CS0246: The type or namespace name `ICSharpCode' could not be found. Are you missing a using directive or an assembly reference?
```

**Comment by hcorion** [comment]
@koosemose Yes, it should. This needs to be merged after my LocalizationDownloader PR #1647 .

**Comment by bjubes** [comment]
^ Changing the title so this is more obvious

**Comment by koosemose** [comment]
Marking as Abandoned due to inactivity for over a month, feel free to reopen if you return with time to work on it.

**Pull request closed without merging**
