### PR TITLE
Added Zoom Lerping - Smooth zooming

### PR DESCRIPTION
**Pull request by RodRitter**
A quick addition while I had a chance. Added some nice smooth zooming action. :sunglasses: 

Also added it's settings into the settings.xml - I'm sure someone can add it to the settings modal at some point.

### CODE REVIEW

**Comment by svmnotn** [comment]
alt text

**Comment by svmnotn** [comment]
it now has conflicts, please fix

**Comment by RodRitter** [comment]
@vogonistic Conflict resolved

**Comment by Mizipzor** [comment]
Nice effect. :)

**Pull request merged**
