### PR TITLE
Adds Unit Test to Duplicate Key Comparer

### PR DESCRIPTION
**Pull request by zwrawr**
three tests fail , currently think its  the DuplicateKeyComparer being broken rather than the the unit test code being wrong. Would like someone to take a look and see if they agree

### CODE REVIEW

**Comment by kd7uiy** [comment]
Which tests are failing?

**Comment by zwrawr** [comment]
these three

Compare_AgainstLargerValue_equalValueAtEnd_True

Compare_AgainstSmallerValue
Compare_AgainstSmallerValue_equalValueAtEnd_False

**Comment by kd7uiy** [comment]
The value of a comparison isn't guaranteed to be 1 or -1, just positive or negative, or 0 if identical. You should really be checking to see if it is greater than or less than 0.

**Comment by zwrawr** [comment]
I'll update the Asserts with that in mind , but i don't think that is the issue as it reports them returning either 1 or -1

> Compare_AgainstLargerValue_equalValueAtEnd_True [0.027s]
Expected: not -1
But was:  -1
at DuplicateKeyComparerTest.Compare_AgainstLargerValue_equalValueAtEnd_True () [0x0003e] in \ProjectPorcupine\Assets\Editor\DuplicateKeyComparerTest.cs:171

> Compare_AgainstSmallerValue [0.02s]
Expected: not 1
  But was:  1
at DuplicateKeyComparerTest.Compare_AgainstSmallerValue () [0x0003e] in \ProjectPorcupine\Assets\Editor\DuplicateKeyComparerTest.cs:190

>Compare_AgainstSmallerValue_equalValueAtEnd_False [0.022s]
Expected: not 1
  But was:  1
at DuplicateKeyComparerTest.Compare_AgainstSmallerValue_equalValueAtEnd_False () [0x0003e] in \ProjectPorcupine\Assets\Editor\DuplicateKeyComparerTest.cs:202

**Comment by kd7uiy** [comment]
The True/False should only affect something in the event of an exact tie. Otherwise, the answer should be the same. So I think that's what the difference is.

**Comment by kd7uiy** [comment]
The idea, BTW, behind the true/false is, if something is equal, do you want it placed at the beginning or the end of the list? I added that in from the one I originally used because it seemed better to stick an old task in at the end of the list, while the default behavior was to stick it in at the beginning.

**Comment by zwrawr** [comment]
What would you expect those three methods to return ?

**Comment by kd7uiy** [comment]
The second larger at the end should be negative, the first larger should be positive.

**Comment by zwrawr** [comment]
Updated to fix issues , all tests pass

**Comment by kd7uiy** [comment]
Awesome, then let's add it!

**Comment by bjubes** [comment]
Tested this PR and it works. no style cop errors. all tests pass and check correct behavior. 
:+1:

**Pull request merged**
