### PR TITLE
Modify save dialog

### PR DESCRIPTION
**Pull request by Shirkie01**
Added additional info to save dialog

### CODE REVIEW

**Comment by quill18** [comment]
Heya! Can you include a screenshot of what this looks like?

**Comment by Shirkie01** [comment]
[image: Inline image 1]

I just realized I didn't include the changes to the dialog boxes. The
vertical layout group needs to be adjusted to 32 pixels for both the save
and load dialogs. Actually, I'm also just noticing that the pointer click
isn't working the way I expected, so I think you can go ahead and reject it
due to needing more testing. I'll submit it later as a single cohesive unit.

**Comment by svmnotn** [comment]
@Shirkie01 the image is not displaying properly

**Comment by ComputerOverlord** [comment]
Nice that TheQuill responded!

**Comment by Shirkie01** [comment]
image

Here's a proper image. The latest changes were fixes for spacing and padding issues.

**Comment by emilkris33** [comment]
@Shirkie01 A suggestion for you: Would it be possible to do the thing where every other file has a white background and every other file has a light grey background? That usually makes list like this easier to look at, and it is very clear down the list what filename each time-stamp belongs to.

**Comment by Shirkie01** [comment]
image

Here are the alternating colors and additional padding on the left side of the file list.

**Comment by SquareMan** [comment]
Nice change dude. Makes the file list look a lot better as well adding some useful information

**Comment by NogginBops** [comment]
I would like to see as a small tweak the name of the save being a bigger font than the rest of the taxt. That makes it easier to filter through.

**Comment by Koljenka** [comment]
@NogginBops  or the name of the save being bold and the rest regular.

**Comment by Shirkie01** [comment]
image

I tried the bold, but I think reducing the size and putting the date in italics works.

**Comment by ComputerOverlord** [comment]
Only thing that'd make this better is a delete button.

**Comment by NogginBops** [comment]
@ComputerOverlord #89 Does this. @Shirkie01 in that issue its stated that it should be conflict free to merge that branch into this branch. I think that is a good idea.

**Comment by Koljenka** [comment]
@Shirkie01 you should also make it so that the selected save has a dark grey background.

**Comment by ComputerOverlord** [comment]
I know it did it. I just thought it'd conflict

**Comment by Koljenka** [comment]
I jsut saw that it does conflict in DialogListItem.cs but i should b3 able to just add those 2 kines to 'my' DialogListItem.cs and it should be fine.

**Comment by quill18** [comment]
Looks good.  We'll probably want to tweak this further if/when we get an in-game calendar.

**Comment by Koljenka** [comment]
now i can just pull and edit.

**Comment by ComputerOverlord** [comment]
@NogginBops I said it because of incompatability :). Creator will have to redo it.

**Pull request merged**
