### PR TITLE
[Need feedback/test] Context menu on right mouse click

### PR DESCRIPTION
**Pull request by sboigelot**
Add a context menu to the game.

Right click on any furniture, inventory or character to open a context menu full actions.
This context menu read a list of action defined by the targeted tile content.
There is also support for action only available when the player has a character selected.

Everyone can extend IContextActionProvider.GetContextMenuActions to provide more actions to the differents objects.

image

image

image

### CODE REVIEW

**Comment by sboigelot** [comment]
Change on the unity scene is just adding the context menu to the scene, but if there is merge conflict we can just ignore them.

The context menu is also located in a prefab, so it's easy to add it back

**Comment by vogonistic** [comment]
Can you fix the merge conflicts?

**Comment by sboigelot** [comment]
> Can you fix the merge conflicts?

I'm at work for now, I'll have a look at lunch time ;)

**Comment by sboigelot** [comment]
I fixed the branch but I have an issue that is unrelated probably, no time to investigate now.

When starting the game I get an error log:

UnassignedReferenceException: The variable inventoryUI of WorldController has not been assigned.
You probably need to assign the inventoryUI variable of the WorldController script in the inspector.
UnityEngine.Object.Instantiate[GameObject] (UnityEngine.GameObject original) (at C:/buildslave/unity/build/Runtime/Export/UnityEngineObject.cs:189)
InventorySpriteController.OnInventoryCreated (.Inventory inv) (at Assets/Scripts/Controllers/InventorySpriteController.cs:78)
InventorySpriteController..ctor (.World currentWorld, UnityEngine.GameObject inventoryUI) (at Assets/Scripts/Controllers/InventorySpriteController.cs:41)
WorldController.Start () (at Assets/Scripts/Controllers/WorldController.cs:100)



and


How do we not have an instance of mouse controller?
UnityEngine.Debug:LogError(Object)
Logger:Log(Level, String, Object[]) (at Assets/Scripts/Utilities/Logger.cs:138)
Logger:Log(Level, Object) (at Assets/Scripts/Utilities/Logger.cs:115)
Logger:LogError(Object) (at Assets/Scripts/Utilities/Logger.cs:53)
MouseOverRoomIndexText:Start() (at Assets/Scripts/UI/MouseOverRoomIndexText.cs:38)




this seems to be an error in the upstream master for me

**Comment by sboigelot** [comment]
ok it seems to work now, I don't know what changed. Maybe someone else should try the feature before merging, just in case.

**Comment by vogonistic** [comment]
This PR has a conflict, remove `[conflict]` from the title when it's fixed and ready for review.

**Comment by vogonistic** [comment]
It doesn't build as is. Also, don't put `[updated]` in the title. I almost missed it looking for PR's that aren't conflicting or WIPs. Just removed `[conflict]`

**Comment by sboigelot** [comment]
It builds and run again, the exposed interface of the Tile changed during the day to match CamelCase on public properties.

**Comment by vogonistic** [comment]
I get this error
```
MissingReferenceException: The variable ContextualMenuItemPrefab of ContextMenu doesn't exist anymore.
You probably need to reassign the ContextualMenuItemPrefab variable of the 'ContextMenu' script in the inspector
```

Also, it creates `Assets/Scripts/Settings.meta` which shouldn't exist anymore.

**Comment by sboigelot** [comment]
@vogonistic I had the same error and re-asigned it in the scene, something is weird. I'll have one more look.

**Comment by sboigelot** [comment]
@vogonistic hem... it works on my side (classic comment)

image

Do you still have the issue? In the scene there is a gameobject "Context Menu", the last behaviour on it is the ContextMenu script.

There is only one property on the editor, could you check if you have the ContextMenuItemPrefab set in it?

image

If not, the prefab is in the Prefab Folder.

**Comment by vogonistic** [comment]
I'm testing again

**Comment by vogonistic** [comment]
Ok, works this time. Maybe I didn't reopen the scene properly the last time or something.

**Comment by sboigelot** [comment]
Great! Thanks for the merge, and sorry for the multiple re-test needed.

**Pull request merged**
