### PR TITLE
Added 3 spritesheets for character animation

### PR DESCRIPTION
**Pull request by Raketfart**
As mentioned in issue #142 these spritesheets are for character animation

### CODE REVIEW

**Comment by Raketfart** [comment]
These files are for first stab at character animation. 
The xml file has tile information. Theres an idle south east and north facing character, as well as a 2-step walking animation for south, east and north. West facing could hopefully be flipped in the animation script.

Here is a preview.
preview

Also added is the character without helmet, and a spritsheet with only the helmet. Tile sizes are all the same.

**Comment by Raketfart** [comment]
Oh, and these are of course just modified versions of kenney.nl's spaceman, same as the original

**Comment by dustinwloring1988** [comment]
This should be a nice touch.

**Comment by Tranberry** [comment]
test1

For us who can't visualize as good. (wrong fps).

**Comment by bjubes** [comment]
Make sure to open in unity and add the generated meta files.

**Comment by Raketfart** [comment]
Done, thanks

**Comment by Tranberry** [comment]
@vogonistic @WardBenjamin @RodRitter - any input?

**Comment by WardBenjamin** [comment]
Looks good to me! I think the changes in #266 would be reasonably easy to modify so that they work with this animation system, and this looks great. Thanks!

**Comment by SteelFall** [comment]
It should be pretty easy to combine. The only changes I have really made were adding the helmet to a separate sprite and changing the character colour to white.

**Pull request merged**
