### PR TITLE
StyleCoped scripts/models/*.cs

### PR DESCRIPTION
**Pull request by zwrawr**
Improved Style of scripts in the models directory. 

Did not rename methods/Varibles or reorder public/private

### CODE REVIEW

**Comment by Grenkin1988** [comment]
You are going to have so much conflicts I think :-) You should do it in smaller parts.

**Comment by svmnotn** [comment]
no conflicts if someone merges it right now ;)

**Comment by Grenkin1988** [comment]
Than everyone else would have them

**Comment by bjubes** [comment]
The code will be clean, but everyone will hate you :)

**Comment by WardBenjamin** [comment]
To be honest, I'm in favor of doing this now while it's not too, too intrusive. 

The only issue I see is that in a bunch of places, there's now 4 forward slashes in comments. (i.e.: `////`).

**Comment by Grenkin1988** [comment]
This is still not finished, It would be better just to force people style file ehen they change it.

**Comment by zwrawr** [comment]
the //// is how StyleCop wants commented out code to be

**Comment by Grenkin1988** [comment]
There should be no commented out code #440

**Comment by zwrawr** [comment]
Before i commit that , Removing commented code will be removing commented out Debug.Log/Logger.Log is that okay?

**Comment by Grenkin1988** [comment]
@zwrawr that people still discussing.

**Comment by zwrawr** [comment]
I made a branch off this and removed commented out code , will merge if people want that

**Comment by Mizipzor** [comment]
I would advise against doing this, as others have pointed out it might be problematic for other pull requests. It is much better to do cleanup in a file youre working in anyway. Preferably as a separate commit if its much, so you can look at just the diff of the other commit to see what was actually done. 

If you really want to do some cleanup, then do one file at the time, try to find files that no one works in.

I appreciate the initiative though. :)

**Comment by WardBenjamin** [comment]
@zwrawr That's definitely an issue then. Is there a way to change that setting? Plus, it //// commented the actual comments people put there, which I don't like. I guess tbh those should be /**/ block comments, but still.

**Comment by Mizipzor** [comment]
There's no way to change, we can turn the rule off or leave it on. This is a good thing, cuts down on discussion. For the comments though, is it really that important? Considering what we would give up by turning if off. Everyone is used to something.

**Comment by WardBenjamin** [comment]
Alright, I'm okay with this now. Merging!

**Pull request merged**
