### PR TITLE
Discussion/WIP: Whitespace cleanup.

### PR DESCRIPTION
**Pull request by Mizipzor**
Replaced tabs with (4) spaces.
Removed trailing whitespace.

Heads up, you probably dont want to merge this. :)

We agreed on spaces instead of tabs, why is this not enforced? And trailing meaningless whitespace should be implicitly forbidden everywhere. I obviously didnt do this manually, and neither should you. From the project root I ran [tabs2spaces.py](https://gist.github.com/antivanov/59e00f6129725e9b4404) and [trimwhitespace.py](https://gist.github.com/Mizipzor/4da24230e31206650bff2f970a7093f3):

```
 python tabs2spaces.py Assets 4 (.*).cs$ 
 python trimwhitespace.py Assets (.*).cs$
```

This pull request is just to show the extent of the changes these scripts make, for good or bad.

We might also want to discuss if tab characters are allowed as long as they are not the first character on the line.

Maybe add these scripts in a utils folder with a `cleanup.bat`? These are meant for fixing when there is a super clear right and wrong, with no room for interpretation.

It's not great doing this as a pull request, its better done by someone with direct access to the repository. Merge all pull requests you want, and run the cleanup once.

### CODE REVIEW

**Comment by vogonistic** [comment]
If this is merged, then every other PR needs to be updated. It's better to do it in small increments, a file or two at a time.

**Comment by bjubes** [comment]
I agree. Style guidelines should make the project cleaner. Causing 30 merge conflicts will do the opposite and inhibit progress

**Comment by Mizipzor** [comment]
@vogonistic Agreed, thats why I said

> Heads up, you probably dont want to merge this. :)

And

> This pull request is just to show the extent of the changes these scripts make, for good or bad.

And

> It's not great doing this as a pull request, its better done by someone with direct access to the repository. 

But I guess I could have been clearer. I'll keep that in mind the next time.

**Comment by vogonistic** [comment]
I saw those, but a PR is basically a request to have something merged.

2 better ways (IMO):
  1. Put `[WIP]` in the title. That way (at least people who are used to it) knows that this PR is not done or ready to be merged yet.
  2. If you wanted to demonstrate the extent of changes to someone, you can create a branch with these changes in your repo, find the page that shows the diff and post that link for people to see.

It's no hard feelings.

**Pull request closed without merging**
