### PR TITLE
Change several very common logs to Verbose to reduce log spam

### PR DESCRIPTION
**Pull request by kd7uiy**
There are a number of common logging functions that slow things down drastically. These are switched to Verbose, so they normally don't show unless requested.

### CODE REVIEW

**Comment by Mizipzor** [comment]
Hm it appears some job bug fixes has snuck in here.  Quill mentioned that we should be more strict about only accepting pull requests that do what they say they do and nothing more. He might still go easy on it but I would suggest looking into splitting this up. :)

**Comment by kd7uiy** [comment]
If you look at the files changed, there's only actually 1 file that has changed, and it has nothing to do with logs. Basically, I need to clean up my git fork, which I can do, but it's somewhat painful. Bottom line, this should work as is, when it's squashed only the change indicated will be included. And there won't be any difference shown in the commit tree.

**Comment by kd7uiy** [comment]
This is related to https://github.com/TeamPorcupine/ProjectPorcupine/pull/247 and in fact, I believe https://github.com/TeamPorcupine/ProjectPorcupine/pull/247 will contain everything this does after it's conflict is resolved. So if https://github.com/TeamPorcupine/ProjectPorcupine/pull/247 is pulled in, just reject this one.

**Comment by kd7uiy** [comment]
Okay, I've done my git work, and now I'm just commiting the desired change, plus a merge. It still has the same effect.

**Comment by Mizipzor** [comment]
@kd7uiy is awesome that you figured it out. Did you do this with a force push our just recreated fork? Regardless, this way of replacing committs in a pull request is super useful.

**Comment by kd7uiy** [comment]
Force push and reading. It's a real pain...

**Comment by Mizipzor** [comment]
@kd7uiy its not pain, its fun! ^^

**Pull request merged**
