### PR TITLE
Adding z lvl to thermal

### PR DESCRIPTION
**Pull request by Geoffrotism**
Add 3D simulation for thermal changes. 
Updated LUAs to reflect this. 

- [x] fix diffusivity so it is not applied vertically to all z lvls.
- [x ] have code only iterate through enclosed rooms when changing temperature (not feasible with current code)
- [x] adding/deleting rooms needs to work properly.

follows #1326

### CODE REVIEW

**Comment by NogginBops** [comment]
Why should temperature only be tracked in enclosed rooms?

**Comment by Geoffrotism** [comment]
Less calculations. Is there a reason to track temperature in space?

**Comment by Geoffrotism** [comment]
Update: PR still under work. Can't continue until issue #1406 is resolved.

**Comment by koosemose** [comment]
Looks good, there's of course room for further improvements (such as not transmitting heat where there's no atmosphere or furniture or anything else perhaps), but it certainly seems an improvement, and I think this is a good point for this PR. Merged.

**Pull request merged**
