### PR TITLE
Adjusts the size of the Headlines depending on the text

### PR DESCRIPTION
**Pull request by kd7uiy**
The size of the Headline Box will now auto-adjust, as seen below:
capture

### CODE REVIEW

**Comment by kd7uiy** [comment]
In case anyone asks, this is identical to #1176, except for the fact that I prematurely deleted that branch. Gaaah!

**Comment by Grenkin1988** [comment]
This how it look for me
image

**Comment by kd7uiy** [comment]
Okay, I'll adjust the position, as seen here:
capture

**Comment by Grenkin1988** [comment]
Now for me it works.

**Pull request merged**
