### PR TITLE
Add preview for building floors

### PR DESCRIPTION
**Pull request by SquareMan**
Since floors require the player to build them I decided to add in the preview sprite. Unfortunately since the job system isn't fleshed out yet, the approach is a bit hackish. However, it works perfectly fine and can easily be updated once the job system is redone (specifically the job sprite system)

### CODE REVIEW

**Comment by vogonistic** [comment]
Can you add a screenshot?

**Comment by SquareMan** [comment]
It's just normal "greenified" version of the normal sprite. Give me a minute and I'll get a screenshot.

**Comment by SquareMan** [comment]
floor sprite preview

**Comment by Tranberry** [comment]
Might be a number of different reasons (nightmode, laptop screen etc..) but I can't see any difference.

**Comment by vogonistic** [comment]
I assume it's more visible while running it locally. Definitely agree that it's better than no sprite at all. 👍

**Pull request merged**
