### PR TITLE
Implement UberLogger functions in ModUtils

### LINKED ISSUE #711: Add ULogChannel, ULogWarningChannel and ULogErrorChannel to ModUtils
ModUtils exports C# methods so that they are available to Lua scripts. UberLogger (the logger library we use) has some channel logging capabilities and we would like to make those available to lua scripts as well.

Look at #672 for how it was originally implemented.

We expect the Pull Request to include at least one log message sent using each of these functions from a Lua script. 

Make sure to follow the style guidelines in [CONTRIBUTING.md](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by mikejbrown**
Fixes #711

### CODE REVIEW

**Comment by Sommerbo** [comment]
Maybe we should force the channel to be "LUA log-messages" to simplify for lua developers and to concentrate all messages in one place.

**Comment by vogonistic** [comment]
I think it's good to expose the channels, but maybe the normal log where you don't specify a channel should default to `Lua` something or other?

**Comment by Sommerbo** [comment]
Yeah, that works.

**Comment by mikejbrown** [comment]
How is that?

**Comment by mikejbrown** [comment]
That removes the LogError that pauses the game on load and pretties up the lua a little bit.

**Comment by Mizipzor** [comment]
Tested. I started the game and I saw logs in the Lua channel.

**Pull request merged**
