### PR TITLE
Zoom with Keyboard (PageUp/PageDown)

### PR DESCRIPTION
**Pull request by forsartis**
Added the ability to zoom with the Keyboard (PageUp/PageDown).
This fixes issue #762.

### CODE REVIEW

**Comment by ComputerOverlord** [comment]
numpad up/down?

**Comment by bjubes** [comment]
No page up and page down. Laptops don't usually have numpads

**Comment by FilippoLeon** [comment]
In the future it can (should) be made configurable anyways

**Comment by Mizipzor** [comment]
Im on a laptop so this was very useful to me. Thank you.

**Pull request merged**
