### PR TITLE
Power Generator Localisation

### PR DESCRIPTION
**Pull request by Dan54**
Adds English localisation for Power Generator.
localisation screen shot2

### CODE REVIEW

**Comment by WardBenjamin** [comment]
This is already completed in #236

**Comment by SanteriHetekivi** [comment]
@Dan54 @WardBenjamin And also in #169, #186 and #256 
Seems this fix is popular :)

**Comment by WardBenjamin** [comment]
@SanteriHetekivi Yeah, I think Quill mentioned it in a video or something.

**Comment by SanteriHetekivi** [comment]
@WardBenjamin Jeah my #169 was first to fix it before video went live (Noticed while making Finnish translation) and my comment in the video about the fix being already made is top comment, but still these keep coming.
Good that people are at least active :)

**Pull request closed without merging**
