### PR TITLE
Metal smelter

### PR DESCRIPTION
**Pull request by vogonistic**
This is a cherry-picked version of #165, on behalf of @UnknownSoldier1, who didn't know that I did it. Let me know if you don't want me to do something like this in the future.

I've tested it and it works great for me.

### CODE REVIEW

**Comment by ComputerOverlord** [comment]
@quill18 needs to see this one.

**Comment by UnknownSoldier1** [comment]
@vogonistic It's okay if you fix my PR, I mean, if my stuff has issues that result in them never being merged... Then it's better if someone else like you reuploads it cleanly.

**Comment by NogginBops** [comment]
Is there any screenshots of this available?

**Comment by UnknownSoldier1** [comment]
game screenshot
This was from the first PR about this feature.

**Comment by NogginBops** [comment]
👍

**Comment by WardBenjamin** [comment]
I changed the world generation to generate raw iron as well, instead of steel plates. See #260.

**Comment by AE40** [comment]
I think this is a great start, as we only (at the moment of writing this comment) have the recource "Steel Plates", Raw iron is a great start of the many recources the game will acuire and adds another level of complexity that will hopefully make the game somewhat fun.

**Comment by quill18** [comment]
Merged!

**Pull request merged**
