### PR TITLE
[Conflicts][Stylecop warnings] Work Tab

### PR DESCRIPTION
**Pull request by dustinwloring1988**
Had to delete my old PR because I had the changes done in master.

Created a work panel.like in RimWorld where you can get job priorities.
It will display the Character's name.
The priorities you set don't affect anything yet and don't save.

Control + Left Click - Set To Min
Control + Right Click - Set To Max
Left Click - Goes Down By One
Right Click - Goes Up By One

### CODE REVIEW

**Comment by Sommerbo** [comment]
If you delete the branch used for the PR request the corresponding PR is closed.

**Comment by dustinwloring1988** [comment]
@Sommerbo  Thanks, still trying to get the hang of Github.

**Comment by vogonistic** [comment]
There are a lot of StyleCop warnings that you should fix and when right-clicking, I get the contextual menu of the item below. Remove `[StyleCopy warnings]` from the title when it's fixed.

**Comment by mikejbrown** [comment]
This pull request has merge conflicts. Please resolve the conflicts and remove [Conflicts] from the title.

**Comment by mikejbrown** [comment]
Is this going ahead since #1141 was merged?

**Comment by bjubes** [comment]
I assume it can, if a different button is added for it

**Comment by sboigelot** [comment]
@dustinwloring1988 Do you still work on this? Or should someone take it over?

**Comment by sboigelot** [comment]
This PR has no sign of life since 20 days. I will close it for now to let other people work on the issue if they wish. @dustinwloring1988 feel free to re-open it if you come back and no-one closed the issue yet.

**Pull request closed without merging**
