### PR TITLE
Job spot is in proper position for smelter

### PR DESCRIPTION
**Pull request by Pyroar**
Earlier the characters stood next to the chair when smelting, now they sit on the chair.

### CODE REVIEW

**Comment by jdlaroche** [comment]
It's not a big deal, but the indentation of the new line is incorrect..

**Comment by vogonistic** [comment]
You are using tabs for indentation, can you change it to 4 spaces per tab and ensure it's aligned with other tags?

**Comment by Pyroar** [comment]
It's now fixed

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
