### PR TITLE
added copper wire

### PR DESCRIPTION
**Pull request by alexisfcote**
xml and png based on steel plate
also change one stack of steel to copper in load hack

### CODE REVIEW

**Comment by quill18** [comment]
We absolutely need a source / attribution / license for the copper wire graphic.

**Comment by alexisfcote** [comment]
I drew it myself how and why should I write the attribution?

**Comment by alexisfcote** [comment]
I think I messed up the pull request by deleting the branch on my fork. Reopening it sorry.

**Comment by svmnotn** [comment]
@quill18 might want to add a bit in the CONTRIBUTING.md file about how to handle licenses for assets.

**Comment by vogonistic** [comment]
@quill18 What is required from attribution and license standpoint?

**Comment by vogonistic** [comment]
Since it's made by @alexisfcote, presumably for ProjectPorcupine, it'll now inherit the GPL license. If we find out that it's different, we can fix it later.

**Pull request merged**
