### PR TITLE
Fixing door rotation and updating surrounding furniture when deconstructing furniture

### PR DESCRIPTION
**Pull request by Raketfart**
Furniture updates surrounding furniture regardless of size when placed or deconstructed.
Also a hotfix for door rotation when walls are placed after the door. #85

### CODE REVIEW

**Comment by Raketfart** [comment]
This is same fix as closed PullRequests #90 #92 #244 but this time with conflicts resolved and without the weird line-ending txt files included.

**Comment by Mizipzor** [comment]
Oh, you figured it out, I think I commented regarding the line endings in your other PR.  Reading notifications in chronological order. ^^

**Comment by Raketfart** [comment]
@Mizipzor Yes, thanks. I omitted the text files, but that means I can't create new branches. I'll just wait for the other PR's to get merged.

**Comment by Mizipzor** [comment]
You can merge in the fixes yourself to your repo, create branches on that, and then rebase once it has actually been merged into upstream. But it's certainly easier to just wait.

**Comment by vogonistic** [comment]
@Raketfart Please fix the merge conflicts

**Comment by Raketfart** [comment]
Phew, these git problems are killing me. I couldn't update my branch from master, so I've started over, and the conflicts are fixed in #442

**Comment by Mizipzor** [comment]
@Raketfart did you look at the video Quill made? Especially the part regarding conflict resolution? :)

**Comment by Raketfart** [comment]
No, I'll do that right away!

**Pull request closed without merging**
