### PR TITLE
Automatic Unit Tests in Travis CI

### PR DESCRIPTION
**Pull request by bjubes**
Adds configuration for unit tests on every branch and PR using Travis.

### How it works

Travis reads `.travis.yml`, which tells travis to execute `install.sh` first. `install.sh` downloads Unity 5.4 and installs it on the virtual machine. Travis is then told by `.travis.yml` to run `test.sh`. This script compiles the project and runs all the unit tests. The results of these tests is saved in an xml file which is logged out during the build.

### What it currently does
This PR currently will track every branch and PR automatically and test every commit that is pushed from now on. Travis will try to compile the project and run unit tests, and if either fails it will report a failure. This is seen as a red x next to a commit. If the latest commit in a PR fails, then the entire PR will have an error next to it on github, with a link to the log of the build.

### What it should do before being merged (help appreciated)
see my comment below

### Examples

Here is the latest build of this PR in Travis (should be passing):
[Build Status](https://travis-ci.org/bjubes/ProjectPorcupine/branches) - click on travis-unit-tests

Here is a sample PR with a change that causes a compile-time failure:
https://github.com/bjubes/ProjectPorcupine/pull/4
and its branch in travis (break-build-compile-unit-test)
[Build Status](https://travis-ci.org/bjubes/ProjectPorcupine/builds/157188400)

Here is a sample PR that compiles, but breaks a unit test:
https://github.com/bjubes/ProjectPorcupine/pull/6
and its branch in travis (fail-unit-test)
[Build Status](https://travis-ci.org/bjubes/ProjectPorcupine/builds/157241307)

Here is a sample PR that doesn't cause any errors: 
https://github.com/bjubes/ProjectPorcupine/pull/5
and its branch in travis ( passing-travis-unit-test)
[Build Status](https://travis-ci.org/bjubes/ProjectPorcupine/builds/157247821)

thanks to @ulve, whose config I used as a basis

### CODE REVIEW

**Comment by vogonistic** [comment]
If nobody jumps in and helps you with this before I can get to it, I'll help you with the status code.

**Comment by vogonistic** [comment]
Also, awesome job!

**Comment by vogonistic** [comment]
The tests looks great. What more is there to do on this PR?

**Comment by bjubes** [comment]
@vogonistic the only thing to really do is clean up test.sh. I edited the OP to reflect this. The lines im refering to are these:
```
if [ "$errorCount" != "0" ]; then
	echo $errorCount ' unit tests failed!'
	exit 1
fi

errorCount=$(grep "failures" EditorTestResults.xml | awk -F"\"" '{print $6}') #now for errors

if [ "$errorCount" != "0" ]; then
	echo $errorCount ' unit tests threw errors!'
	exit 1
fi

errorCount=$(grep "failures" EditorTestResults.xml | awk -F"\"" '{print $12}') #inconlusive tests

if [ "$errorCount" != "0" ]; then
	echo $errorCount ' unit tests were inconlusive!'
	exit 1
fi

errorCount=$(grep "failures" EditorTestResults.xml | awk -F"\"" '{print $18}') #finally for invalid tests

if [ "$errorCount" != "0" ]; then
	echo $errorCount ' unit tests were invalid!'
	exit 1
fi
```
this works for checking for errors and bad unit tests, but it obviously a terrible implementation. Im going to remove WIP from the title as this is working, but after this is merged these files will need fixing.

**Comment by bjubes** [comment]
Also I don't think merging this PR will activate CI until @quill18 authorizes Travis CI to write a web hook for this repository

**Comment by vogonistic** [comment]
We should merge early so that we can hit the ground running when it's started. I've sent a message to quill about setting it up.

**Comment by bjubes** [comment]
okay its very simple for him to set up.
Do u want to merge it now? that way I can test it even more on my fork for everyones PR and ensure its working correctly.

**Comment by quill18** [comment]
Activated on travis-ci.org -- and merging this!

**Comment by TomMalbran** [comment]
Awesome!! Next will be to add StyleCop check into Travis

**Comment by quill18** [comment]
Currently processing our first pull:

https://travis-ci.org/TeamPorcupine/ProjectPorcupine

https://travis-ci.org/TeamPorcupine/ProjectPorcupine.svg?branch=master

**Comment by bjubes** [comment]
@TomMalbran I think style cop will be a seperate webhook, just to differentiate between a PR breaking functionality vs having a few style errors.

**Comment by TomMalbran** [comment]
@bjubes Cool, that sounds good.

**Pull request merged**
