### PR TITLE
Power system should react on changes to powerValue

### PR DESCRIPTION
**Pull request by Grenkin1988**
#502
Related to #436

### CODE REVIEW

**Comment by vogonistic** [comment]
This PR has merge conflicts

**Comment by Grenkin1988** [comment]
That's rude. If all the time new PR's are going to be merged before more old one...

**Comment by vogonistic** [comment]
I can understand it feels that way, but it's doesn't make it true.

**Comment by Grenkin1988** [comment]
So right now I would do like this #558 and style all the files for everyone, that's OK?

**Comment by vogonistic** [comment]
Please stick to the issue at hand. If you have complaint at how things are done, you can either send an email to that person, open an issue or email quill. I'm online now in Discord if you want to chat about it.

**Comment by Grenkin1988** [comment]
Resolved conflicts

**Comment by Grenkin1988** [comment]
Now there is a bug...

**Pull request merged**
