### PR TITLE
Change Save format to Json

### PR DESCRIPTION
**Pull request by koosemose**
Per the decision laboriously reached in #1034 this starts the switchover to Json, by including the Json.Net library ( http://www.newtonsoft.com/json ) and changing loading/saving games to use Json. Tests that previously testing saving related xml reading/writing have been updated to use the appropriate Json based methods. Other than the file format saving/loading should behave as it did before.

### CODE REVIEW

**Comment by koosemose** [comment]
As far as I can tell Travis is failing to build at all because Json.Net requires Api Compatibility Level of .NET 2.0 (rather than subset), and it's not being built with that, I'm not sure if this is simply because git doesn't have ProjectSettings, or if when running it from the commandline you have to specifically tell it to use .Net 2.0 somehow.

On a related note, not including ProjectSettings means we can't set the project to use .Net 2.0 in general, so any one developing will have to explicitly set the Api Compatibility level on their local ProjectSettings.

**Comment by dusho** [comment]
Why not to use serialization, but explicitly json objects to serialize/deserialize? I would assume save/load files would be some binary format in the end. And using serialization would enable us to choose any formats (serializers - binary, xml, json, ...). Generally you don't want people to poke around your save files with text editor...

**Comment by koosemose** [comment]
It was an intentional decision in the beginning to have save files be non-binary. I disagree about not wanting people to poke around in save files, it opens up a lot of game play opportunities for those interested in hacking around with things (see things people do with Kerbal Space Program saves as examples). Due to the way some of the data is stored (particularly anything involving colors) autoserialization fails miserably, getting stuck in an infinite loop. Doing it this way allows me to closely mirror the data that is presently saved in xml. If, after this gets in, you or someone else wants to start changing things over to automatic serialization and can do so without running into the looping issues I was and keep the same data saved, feel free.

Of course this all may be moot if we can't get travis to a state that it can run tests with Json.Net...

**Comment by koosemose** [comment]
Actually, using autoserialisation/deserialization would be quite bad for save files, it makes them more prone to breaking from a change to the structure of an object. Also, doing it a more direct fashion allows us to only save what we need to save, and rather than deserializing something into, for example, a furniture, we can get the prototype of the furniture, and just set whatever variables need to be changed from the prototype (mostly params, location and rotation), allowing a save to automatically use new versions of objects rather than being stuck using whatever version it was when it was saved.

**Comment by koosemose** [comment]
@bjubes I'm betting your api compatibility level is .NET 2.0 Subset, because that's the error thrown when it is, which is the exact problem Travis has, and where we don't have the project settings (which stores that information) in git, even though I set it to .Net 2.0 it won't be that for anyone else, which is likely why you can't compile either.

**Comment by bjubes** [comment]
so this another drawback in #1488

**Comment by koosemose** [comment]
Closing and reopening to force travis checks to be reran.

**Comment by bjubes** [comment]
Are the save files supposed to be in json now or just support it? They seem to still be xml

**Comment by koosemose** [comment]
Any new save files should be Json... and are for me, and it is no longer capable of loading xml save files.

Are you sure you're looking at a new save from this PR?

**Comment by bjubes** [comment]
I think when i tested I had an unsaved change which cancelled the merge? Whatever happened Its now working properly for me.

**Comment by koosemose** [comment]
It may have been the sound PR, switching back and forth between branches with and without the DLL causes some issues, because Unity doesn't unload the DLL when exit play mode, so git can't delete it when you change branches.

**Pull request merged**
