### PR TITLE
[WIP] Download localization from web

### LINKED ISSUE #551: Move localizations to a separate repository and download them at start of the game.
This will clean up commits in main repo and also ensure that everyone has up-to-date version of localization (as it will be downloaded at runtime).
@quill18 should create a separate repository in TeamPorcupine purely for .lang files (of course if this issue get's nice feedback).

### PR DESCRIPTION
**Pull request by QuiZr**
The system checks only for available updates for current version of the game.
There are still a few things to do, i.e. Add an ability for user to not update to the current version of localization but I've marked them as a beginners tasks in comments so someone should fix that at some point (I really hate dealing with Scene >.>). 
Again, @quill18 should make a repository in TeamPorcupine purely for .lang files, for now there is a temporary link to my repo - that's why the tag [WIP].
There should be something for adding localization files after build in Travis CI or something.
Fixes #551.

### CODE REVIEW

**Comment by Mizipzor** [comment]
You could create the repository yourself so you can hook it all up and prove that it works. I see no problem with you continuing "owning" that repos if we use this.

**Comment by QuiZr** [comment]
Yeah, currently https://github.com/QuiZr/ProjectPorcupineLocalization is hooked up.

**Comment by bjubes** [comment]
And this code will be great if we ever implement an update feature the actual game

**Comment by QuiZr** [comment]
@bjubes I haven't think about that... Well, I need to split this up into separate functions a bit more >.>

**Comment by bjubes** [comment]
Yeah but that's wayy in the future so don't bother. Do we need to hash check the download too or is that overkill

**Comment by QuiZr** [comment]
I don't think that there is any option to get a hash for whole repo in .zip file in git.

**Comment by vogonistic** [comment]
Why was the readme in the mods directory removed?

**Comment by vogonistic** [comment]
This or looks crazy clean. Going to test it a bit later. Awesome job!

**Comment by vogonistic** [comment]
Use `[WIP]` instead of do not merge in the title. Same effect but a stronger convention.

**Comment by QuiZr** [comment]
Ok, I think it's safe to merge for now. I really don't like the idea of holding localization repo on my github tho so I will wait for @quill18 to create that repo, then I will remove [WIP] tag.

**Comment by NogginBops** [comment]
@QuiZr If this PR gets merged I think we need a change to CONTRIBUTING.md

**Comment by Mizipzor** [comment]
Can't we just change the repos it pulls from when it's merged?

**Comment by QuiZr** [comment]
@Mizipzor Sure, but this will hold development of localizations for a bit.
@NogginBops I'm not good with wording, I will try to do my best

**Comment by QuiZr** [comment]
Ok, I've updated CONTRIBUTING.md.... Someone will do a better job at it later >.>
@Mizipzor Should I remove the WIP tag? I've tested it and I think that everything should work just fine.

**Comment by Mizipzor** [comment]
If you tested it then that's good enough for me. :)

**Comment by WardBenjamin** [comment]
@Mizipzor join us on Discord?

**Comment by NogginBops** [comment]
@QuiZr I think you forgot the curr.ver file in your commit.

**Comment by QuiZr** [comment]
@NogginBops If curr.ver is not present the latest translation will (well... Should be) downloaded.

**Pull request merged**
