### PR TITLE
Make Metal Smelter consistent with new Job prototype

### PR DESCRIPTION
**Pull request by kd7uiy**
Metal Smelter needs to include a priority. Set it at medium.

### CODE REVIEW

**Comment by kd7uiy** [comment]
This is a one line of code fix, to not break the Lua code using the Job Creation change made previously.

**Comment by WardBenjamin** [comment]
@kd7uiy Btw, there's an extraneous logging-related commit again. One way to maybe avoid this is by working on different feature branches instead of on master all of the time.

**Comment by kd7uiy** [comment]
Yeah, I should really start doing that... I think I'm going to in the future, thanks for the tip!

**Comment by kd7uiy** [comment]
Now it's just two commits, the original and a merge. I'm content with that:-)

**Comment by WardBenjamin** [comment]
Looks much better!

**Comment by kd7uiy** [comment]
This should really be pulled in as soon as possible, @quill18 . It's only one line of code, and without it there's an annoying error that happens, plus the smelters don't work at all.

**Comment by henninglive** [comment]
What's up with the `pl_PL.lang` file? did you intend to modify it?

**Comment by kd7uiy** [comment]
I'm trying to get rid of that one as we speak... Sigh...

**Comment by kd7uiy** [comment]
@henninglive Got it cleared up. I tried to create a branch to put the other change in, and it didn't work as I expected it to. Bottom line, I've got it resolved now, and will ignore the other change for the time being.

**Comment by quill18** [comment]
It looks like pl_PL.lang was committed wonky eol's. I expect a lot of `git add -A` or Github Desktop users will be including it in their commits.

**Pull request merged**
