### PR TITLE
Updated list of names, capitalized and alphabetized

### PR DESCRIPTION
**Pull request by kd7uiy**
This one contains all 99 names of contributors to date to this project.

### CODE REVIEW

**Comment by mikejbrown** [comment]
Grrr argh should make this file alphabetical so the diff is easier to inspect... (you would have to alphabetize the old version as well I realize).

**Comment by kd7uiy** [comment]
Easy enough to do. I just printed it in the order that my script printed it, so... Tossed in a sort command, and it should be easier in the future.

**Comment by kd7uiy** [comment]
Hold off for one sec. I'm going to make sure all of the names are capitalized.

**Comment by kd7uiy** [comment]
Okay, now it's good to go.

**Comment by mikejbrown** [comment]
For reference here is the diff of the uncapitalized alphabetized names lists:
```diff
diff --git a/Assets/StreamingAssets/Data/CharacterNames.txt b/Assets/StreamingAssets/Data/CharacterNames.txt
index 9adedc4..299709d 100644
--- a/Assets/StreamingAssets/Data/CharacterNames.txt
+++ b/Assets/StreamingAssets/Data/CharacterNames.txt
@@ -1,65 +1,99 @@
 65001
 AaronBuckles
 Aiwha
-alexisfcote
-arrowgroundgames
 Azathos
-behindcurtain3
-bjubes
 Ceddini
 Cryma
-Derebeyi
+Dan54
 DeShrike
+Derebeyi
 DevOrc
 DiyarD
 Don42
 Dormanil
-dustinwloring1988
-emilkris33
-empireages
+Fatalexceptionz
 FilippoLeon
 Fogsight
-frankitox16
-gazebodude
 Grenkin1988
-gunthergun
 HexxaGone
-itay347
 JosephBywater
-kd7uiy
 Koljenka
-koosemose
-lameox
-lincore81
 MANDAL0R3
-mrDLSable
+Mizipzor
 NogginBops
-notnanomercy
+NoobPete
 Odhim
 Ohda
+Pyroar
 QuiZr
-racerand
 Raketfart
 Randshot
 RodRitter
+Said6289
 SanteriHetekivi
-satch3l
-sboigelot
 Shirkie01
-simonlary
 SomeGreenGoo
+Sommerbo
+Spool5520
 SquareMan
-squill25
-svmnotn
+SteelFall
 TheAkashicTraveller
 TheRiven
-tickinginstant
-tomik148
+TomMalbran
 Tranberry
 Tritaris
+UnknownSoldier1
+WardBenjamin
+WilcoDW
+Xeni91
+abackwood
+aleserena
+alexisfcote
+arrowgroundgames
+b4ux1t3
+behindcurtain3
+bitope
+bjubes
+cskiwi
+dusho
+dustinwloring1988
+emilkris33
+empireages
+forsartis
+frankitox16
+fre-ber
+gunthergun
+herrflockig
+itay347
+janpeli
+jaselito
+jdlaroche
+kd7uiy
+koosemose
+lameox
+lincore81
+longtomjr
+mattpott
+mbstraus
+mikejbrown
+misspellted
+mmooxy
+mrDLSable
+notnanomercy
+powli
+quill18
+racerand
+relinu
+satch3l
+sboigelot
+simonlary
+squill25
+svmnotn
+tickinginstant
+tomik148
 ttyz
 u21
-UnknownSoldier1
+vircung
 vogonistic
-WardBenjamin
+vringar
 zwrawr
\ No newline at end of file
```

**Comment by mikejbrown** [comment]
Anyway I'm happy to merge. If somehow someone's name got dropped out they can add it back.

**Comment by mikejbrown** [comment]
@kd7uiy if you have a script for this would you mind putting it up in a gist or something and linking it here or on the wiki so others can do this easily?

**Comment by kd7uiy** [comment]
I'll just submit it to the Scripts folder. I'm relatively confident no one got dropped, based on the fact that the list is 99 long, and we have 99 contributors.

**Pull request merged**
