### PR TITLE
Added Dutch localization

### PR DESCRIPTION
**Pull request by mrDLSable**
I have added a Dutch localization file.

### CODE REVIEW

**Comment by ComputerOverlord** [comment]
Isn't there already one...?

**Comment by mrDLSable** [comment]
Nope, just a German (de_DE). But I have added Dutch (nl_NL). Those two names often get confused.

**Comment by SanteriHetekivi** [comment]
Could you add translations to Dutch for:
furn_power_generator=Power Generator
furn_power_generator_desc=Generates power out of nothing.

They are missing in current master, but pull request #169 should add them in.

**Comment by ComputerOverlord** [comment]
@mrDLSable oh. :P

**Comment by mrDLSable** [comment]
@SanteriHetekivi Done :)

**Comment by gunthergun** [comment]
You have a typo in your last commit: 
furn_power_generator_desc=Genereert stroom **uti** het niets
should be:
furn_power_generator_desc=Genereert stroom **uit** het niets

**Comment by mrDLSable** [comment]
@gunthergun Thanks for noticing. And it's now fixed :)

**Comment by quill18** [comment]
I'm afraid this has a conflict now.

**Pull request closed without merging**
