### PR TITLE
Added Portuguese language (european Portuguese)

### PR DESCRIPTION
**Pull request by ranaerys**

### CODE REVIEW

**Comment by ranaerys** [comment]
Had to re-submit the pull request due to me derping up and deleting my local branch

**Comment by Mizipzor** [comment]
Did you intend to touch `ProjectSettings/GraphicsSettings.asset`? If not, maybe you should consider reverting it.

**Comment by ranaerys** [comment]
I didn't. I checked the wrong file. fixing it now.

**Comment by Mizipzor** [comment]
This is absolutely not needed, but if you want a clean history you can make it look like you never touched that file in the first place. It also ensures that revert actually put the same content there that it use to have. I'm talking about [git rebase](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). You have 6 commits you want to group so you would do `git rebase -i HEAD~6`, replace all words "pick" with the word "squash" in the text editor that comes up. Then `--force` push your branch and commits in this pull request is replaced! :)

Again, absolutely not needed. But it's an opportunity to learn some advanced git. Oh, and its a destructive operation so backup your files.

**Comment by ranaerys** [comment]
Yeah, that sounds great but I'm new to this so I'll let it be. I don't mind not having a clean history. Thanks for the tip, though!

**Pull request closed without merging**
