### PR TITLE
Fix right click outside map

### PR DESCRIPTION
**Pull request by Ohda**
Fix a null exception when you clic/unclick ouside the map (appear  PR #662)

### CODE REVIEW

**Comment by svmnotn** [comment]
This issue happens when someone right clicks.
The fix \/
alt text

**Comment by svmnotn** [comment]
It now has issues with merging, please fix

**Comment by vogonistic** [comment]
When you've fixed the conflicts, remove `[conflict]` from the title. Thanks!

**Comment by Ohda** [comment]
I think it's fine !

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
