### PR TITLE
Localization Tools

### PR DESCRIPTION
**Pull request by UnknownSoldier1**
Added localization tools to the game.

Along with that, I added an English and German translation. If anyone wants to make more translations, the files will be automatically found and used.

Also, I added 2 new features to the Furniture.xml:
-LocalizationCode
-UnlocalizedDescription

I added placeholders for descriptions for now, if someone is able to make better ones that would be appreciated.

### CODE REVIEW

**Comment by svmnotn** [comment]
Will add es_ES when this is merged, just commenting here so that I'm notified :)

**Comment by UnknownSoldier1** [comment]
Alright thanks, I just don't know when this will be merged, since it changes and adds a lot.

**Comment by svmnotn** [comment]
@UnknownSoldier1 you might want to fix the conflicts by updating your branch to the latest version of the master in this repo so that it is easier for @quill18 to merge the PR.

**Comment by UnknownSoldier1** [comment]
I hope this is fixed now.

**Comment by UnknownSoldier1** [comment]
I just noticed that GitHub has broke something that the code has compiler errors. Fixing this now...

**Comment by UnknownSoldier1** [comment]
Fixed now i think.

**Comment by quill18** [comment]
Fixed the conflict via #109

**Pull request closed without merging**
