### PR TITLE
Adjust size of scrollbar in construction menu for better usability (fixes #1466)

### LINKED ISSUE #1466: Construction menu scroll barg
There is a Bug in the Construction menu. When you hold scroll field (not the handle) and move mouse down it sometimes scrolls up and when you move the mouse up it scrolls down. It happens not all the time though, you kinda have to hit the right spot.

### PR DESCRIPTION
**Pull request by Geoffrotism**
Removed unused Menu prefab.
Removed old cs script.
fixes #1466 
image

### CODE REVIEW

**Comment by kd7uiy** [comment]
Usually it's better to have a more descriptive title, keep in mind the titles are what actually gets used in the combined pull request, and it can be easier to see what's going on.

**Comment by mikejbrown** [comment]
@kd7uiy Yes that's best practice (and I'm even thinking of making a PR template to encourage good behaviour around these things). But keep in mind that the merging admin can and should edit the title and message of the eventual commit if need be.

**Comment by Geoffrotism** [comment]
Ah ok. didnt realize bugfix PRs should be like that. will try to remember for the future!

**Comment by TomMalbran** [comment]
It is also a good practice to mention the bug you are fixing in the description "Fixes #1466". That way it gets linked to that issue, is a link that can be clicked, and once this PR gets merged the issue is close automatically.

And finally, if you are doing UI changes, try to add an image, so that we can see the changes.

**Comment by Geoffrotism** [comment]
corrected

**Comment by mikejbrown** [comment]
Appears to work as advertised. No obvious new bugs. Merging.

**Pull request merged**
