### PR TITLE
Implement Base Type for Furnitures

### PR DESCRIPTION
**Pull request by koosemose**
Added BaseType tag to furnitures, and changed replaceable furniture to
use BaseType

### CODE REVIEW

**Comment by koosemose** [comment]
Currently this doesn't have a huge effect, since each object quill has implemented has basically been an example of different types of objects, and appropriately I have assigned each of them a different basetype. However, this is a change I feel will potentially ease future additions, and it is best to get it in early while there are still a limited number of things to change, and future systems can be built to work off of this, rather than being reworked afterwards.

**Comment by svmnotn** [comment]
@koosemose you might want to fix the conflicts by updating your branch to the latest version of the master in this repo so that it is easier for @quill18 to merge the PR.

**Comment by koosemose** [comment]
Ahh, hadn't noticed that conflicts developed since I submitted this, I'll look into straightening those out

**Comment by koosemose** [comment]
That should sort things out, things got a little weird when trying to pull in the changes from this repo's master, so I just manually re-added my changes to the XML to a fresh copy of this repo's Furniture.xml

**Comment by quill18** [comment]
Unfortunately, this is once again conflicting with some other fixes.

**Comment by koosemose** [comment]
I doubt it will be difficult to fix, should have it unconflicted in a few minutes... Though I'll admit, I have no clear idea how to properly handle conflicts with github and usually end up just manually doing it... Fortunately this is a relatively easy change and that's still feasible.

**Comment by koosemose** [comment]
That should be straightened out now.

**Comment by quill18** [comment]
Merged!

**Pull request merged**
