### PR TITLE
Added new sprites for Oxygen generator and Smelter

### PR DESCRIPTION
**Pull request by TheRiven**
Created 2 new Sprite sheets, one for the O2 gen and one for the smelter for #607 

At the moment the game will just load the Idle sprite for each one, but it looks like an animation system is coming which will hopefully allow for the running animation cycles to be used when the machines are being used.

This is what they will look like when they are running:

smelteranimation1
o2gen-animation

### CODE REVIEW

**Comment by gunthergun** [comment]
I love it :)

**Comment by RodRitter** [comment]
Looking great. I noticed the smelter is offset up a bit. Is this intentional?

image

**Comment by TheRiven** [comment]
Yeah it looked... odd with the belts being longer and I wanted it centred but I am happy to hear what people think about changing it.

**Comment by RodRitter** [comment]
Sounds good. Merged!

**Comment by ComputerOverlord** [comment]
Is the o2G smaller?

**Comment by bjubes** [comment]
@quill18  that's some more checkboxes done for #607

**Pull request merged**
