### PR TITLE
Added background music

### PR DESCRIPTION
**Pull request by Ferr013**
Since I haven't enough programming skills, I tried contributing with some (not really high quality) music.
Thanks for the people that help me figure out how to implement it :smile: :+1:

### CODE REVIEW

**Comment by RodRitter** [comment]
This is a good opportunity for someone to implement a sound manager. If you're not that good on the programming end then maybe you can just add your music by itself, without the scripts? Then the next person is able to implement it into the the sound manager feature.

**Comment by Ferr013** [comment]
I think I've fixed the conflict. Thank you :+1:

**Comment by mikejbrown** [comment]
How easy would it be to hook up this MusicController to OnMusicChange() in DialogBoxSettings.cs so that the music volume setting works? This would partially address #538.

**Comment by RodRitter** [comment]
After looking through it again, there are far too many scene additions. Please could you try to move any scene additions into script?

**Pull request closed without merging**
