### PR TITLE
[ART] Updated Uranium "ore" sprite

### PR DESCRIPTION
**Pull request by TheRiven**
Replaced old Uranium ore sprite with one that better fits the current style and updated the XML to match.
uraniumset_1

Not included are sprites for future mining spot and processed uranium but they exist for the future.
uraniumset_0
uraniumset_2

Referencing #607

### CODE REVIEW

**Comment by Tranberry** [comment]
At long last it's the holidays, don't forget to bring the tree - seriously I like these sprites!

**Comment by Dormanil** [comment]
Looking good, Riven! I like those sprites.

**Comment by TheRiven** [comment]
Having seen it in game I feel there is a bit of a clash with the Iron ore sprite due to size but I would like other peoples opinion.

**Comment by Dormanil** [comment]
Well, you could just use the same box with different chunks of ore inside, then the size wouldn't be an issue.

**Comment by longtomjr** [comment]
Aaaah. This is so good. The lord riven has provided us mere presents with a feast for our eyes
I endorse this. This is art that was needed aswell and it is done amazingly!
GJ @TheRiven !

**Comment by TheRiven** [comment]
I have now updated the sprite to match the base size of the iron ore. It helped to actually compare them side by side which is what I should have done in the first place :grinning:

**Comment by kd7uiy** [comment]
I like the first one, looks nice!

**Comment by Raketfart** [comment]
:+1: So good!

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
