### PR TITLE
Character sprites

### PR DESCRIPTION
**Pull request by satch3l**

### CODE REVIEW

**Comment by satch3l** [comment]
namnlost-2
namnlost-1

**Comment by emilkris33** [comment]
@satch3l What exactly does this PR do?

**Comment by Mizipzor** [comment]
This appears to be two pull requests that accidentally got stuck together, some commits are for music and some are for the character sprites. If this is the case, consider rebasing the character sprites to a new branch for a new pull request. Otherwise it becomes an all-or-nothing deal, we cant accept just one of the branches.

**Comment by Tranberry** [comment]
#102 I guess we are a few who replace the character with our own.

**Comment by satch3l** [comment]
I have no clue why github does this? I try to make a new branch to pull but somehow all changes I've done is pulled as well :S

**Comment by Mizipzor** [comment]
@satch3l I think you never started a new branch for your other stuff. If you create a pull request from a branch, everything you later add to that branch is automatically included in the pull request. This is intended, as you are supposed to improve the pull request after feedback, unless you get it right the first time. This is one of the reasons why you never, ever should work directly on your master branch.

**Pull request closed without merging**
