### PR TITLE
[Updated] Feature/currencies

### PR DESCRIPTION
**Pull request by sboigelot**
Adding data support for currencies in game as discussed in #776

image

image

### CODE REVIEW

**Comment by vogonistic** [comment]
Is this the first of several PR's related to currency?

I don't see any code for saving the users currency, or loading it. There is also no functionality or code that takes money out of you wallet. It seems like a `[WIP]`, but isn't marked as such.

**Comment by sboigelot** [comment]
@vogonistic yes this is just the first minimum requierement I need to continue on the trade system. The save/load feature was broken yesterday #813 so I prefered no to add code in it until it is solved.

I'll make another PR later adding save for currencies and quest status.

**Comment by Grenkin1988** [comment]
Looks like not only your changes is part of PR

**Comment by sboigelot** [comment]
@Grenkin1988 I just rebase the PR on master, the other changes are part of master/upstream so totally compatible

**Comment by Grenkin1988** [comment]
@sboigelot So this is OK? I've just recently did the same and got > 100 files in my PR, and I decided to close it :-)

**Comment by sboigelot** [comment]
@Grenkin1988 no idea, it's weird, I may redo my PR but I don't know what would be the effect.

**Comment by sboigelot** [comment]
@vogonistic Save / Load Player wallet now integrated
What should I do about the problem reported by @Grenkin1988, any ideas?

**Comment by koosemose** [comment]
Just so you know, I've got a full fix for #813, in PR #832. One of us is probably going to have to clear a conflict when things get merged.

**Comment by sboigelot** [comment]
@koosemose Yes I already saw your fix after coding my own, your solution is better, we don't need to store x & y when the it is a character inventory. I just set them to 0.

We should merge PR #832 and I'll fix the conflict overriding my code with yours

**Comment by Mizipzor** [comment]
This branch has conflicts that must be resolved, probably due to the huge StyleCop cleanup that just happened. Fix them and remove the `[Conflicts]` tag. :)

**Comment by Mizipzor** [comment]
Would it be possible to also do a stylecop pass on this? Seeing as we just completed the big cleanup. :)

**Comment by sboigelot** [comment]
Merge conflict resolved + run a bit of stylecop. It was a big one ^^ I'm running a smoke test now to validate that I didn't brake anything

**Comment by sboigelot** [comment]
All unit tests succeed and playing all quest in game works fine.

**Comment by sboigelot** [comment]
I'll wait for saturday stylecop to end before fixing conflict again

**Comment by sboigelot** [comment]
Post stylecop day merge conflict solved

**Comment by Mizipzor** [comment]
This has been open for way too long. I tested, and everything still seems to work. But I suppose theres no way to actually test the currency until the trading bit is merged?

**Comment by sboigelot** [comment]
Great news! Thanks @Mizipzor. Yes you are rigth, there is no way to test it beside debuging in monodevelop or visual studio. But I will be able to add it in the trading system now!

**Pull request merged**
