### PR TITLE
fix mining drone station es translation

### PR DESCRIPTION
**Pull request by svmnotn**
As @frankitox16 mentioned in #124 this is a better translation. Don't translate while asleep kids :D

### CODE REVIEW

**Comment by beto2912** [comment]
I'm spanish, and a more accurate translation would be "dron de mineria"

**Comment by svmnotn** [comment]
@beto2912 I was not going for a literal translation just whatever felt right given the meaning it has in english, but you are welcome to send a PR fixing it. Honestly I should of named it es_US o es_DO since I'm not from Spain but I figured that is the one that is used the most... so... feel free to send a pr using proper spanish (as in from spain) idioms.

**Comment by frankitox16** [comment]
@beto2912 I suggested that translation because it sounded better imo... My native language is spanish, and I do know that translation that you gave is the literal one, however if you read "estacion de minería robótica", I guess you'd be expecting what the sprite looks like, a big monitor that says mining drone. 

It's also worth noticing that "Salvar" isn't the correct translation for "Save" (in this context, at least. The right one would be "Guardar"). But that's something for another PR

**Comment by svmnotn** [comment]
heh yeah... my native language is also spanish but living in the US has made translating more difficult, so sorry for the anything that looks off.

**Comment by frankitox16** [comment]
Nothing to worry, you actually did a great job!

**Pull request merged**
