### PR TITLE
Fixed AStar being called to search inventories while ignoring stockpiles

### LINKED ISSUE #64: Game is slowed significantly be current path-finding implementation
As it is currently the game has to generate the entire A*graph every time a floor tile or a piece of furniture is constructed. On my computer this causes very visible slowdown. As shown below my computer uses almost 3 full seconds regenerating the graph.
image

I am not really sure how to go about improving this so any suggestions would be greatly appreciated

### PR DESCRIPTION
**Pull request by lameox**
This lead to a search trough every tile.

Fixes #64  and #71

### CODE REVIEW

**Comment by QuiZr** [comment]
Now plopping down a stockpile results in a NullReferenceException in line 156 at InventoryManager after all of the stockpile jobs are completed.

**Comment by lameox** [comment]
I cant seem to reproduce this. Could you give me your steps for reproducing please?

**Comment by QuiZr** [comment]
All i did was:
0. Clone your repo, switch to branch Fix-AStar-Hang
1. Start a game
2. Save empty scene
3. Load empty scene to get some debug metal
4. Click pathfinding test
5. Got an NullRefferenceException on clicking and pathfinding test is not working??? (Im on separate machine, not relatated - something to do with SoundController)
6. Fixed 5. (commented it out for now, lol)
7. Relaunched, loaded game, load pathfinding test
8. Put down a single stockpile
9. As soon as job finishes Unity bursts into NullRefExc.

**Comment by lameox** [comment]
Should be fixed as well. forgot the excessive null checks :D

**Comment by QuiZr** [comment]
Yup - now it's working fine :) Can I somehow make a pullrequest based on your code before @quill18 pulls that fix in? I have working little fix for that annoying pathfinding problem ( #43 but I've nuked my repo by mistake thinking that that hang was related to my change...).

**Comment by lameox** [comment]
You should be able to fork my repository and then create a branch based off of my branch. Or if you know some git there are simpler ways via the git shell. You would add my repo as a remote and the fetch it. checkout my branch then create a new one. This avoids you having to fork and go through my fork ;)

**Comment by rfmsimoes** [comment]
With your fix the character have a wierd behaviour...like fall in love for a stock pile  xD

Because if you have 50 steel plate in stock pile and build 1 wall...the character will build the wall and after finish he will return to the stock pile.

Have you noticed that?

**Comment by QuiZr** [comment]
@rfmsimoes Yeah - fixed in #46 
@lameox Have I merged this stuff correctly?

**Comment by lameox** [comment]
I have. but it works as long as the character has new jobs and might be deprecated very soon if we implement a new job system. If you want you can try to find the source of that behaviour ;)

**Comment by lameox** [comment]
@QuiZr It seems like you did. I guess i can close this one and reference #46

**Comment by QuiZr** [comment]
I think you won't get contribution mark if you close it - Couldn't you reopen it and leave a mark for @quill18 to merge this first, then #46?

**Comment by emilkris33** [comment]
@QuiZr As long as his commits are in the history of your PR, which they are, I think it will still be marked as his when your PR is accepted. Unless the way @quill18 merges commits when accepting the pull Fs with that

**Comment by lameox** [comment]
I am not here for contribution marks :D its all fine

**Pull request closed without merging**
