### PR TITLE
Additional sounds

### PR DESCRIPTION
**Pull request by satch3l**
Additional sounds that can be used.

### CODE REVIEW

**Comment by RodRitter** [comment]
Did you create the sounds yourself? If not you need to include licensing info.

**Comment by satch3l** [comment]
Yes

**Comment by dustinwloring1988** [comment]
Nice cant wait to have more sounds, Hopefully it gets commit today. :)

**Comment by RodRitter** [comment]
I'll merge this in, but I'm not sure what our standards are for the file format, so it might need to be converted later depending on what's decided.

**Comment by Mizipzor** [comment]
Should also be noted that the sounds are just added, they are not used anywhere (yet). Is there an issue up to implement that? If not, consider creating one.

**Pull request merged**
