### PR TITLE
GUI Revamp

### PR DESCRIPTION
**Pull request by Arwic**
# General

This is a redesign of the game's user interface.  
Some basic icons are also included.

# Issues

- Scroll bars will need to be added to building flyouts when they get full.  
- Changes needed to be made to the scene.  

# Potential Improvements

- Implement a better way to populate flyouts. Floors is static and furniture uses preexisting code
- Better categorisation of items.
- Hide debug buttons.
- Make tile and selection info frames temporary tooltips rather than static frames.

# Screenshots

- Default game:
Default game

- Furniture flyout (floor flyout is similar):
Furniture flyout

- Game menu (accessed by the gear on the right of the bottom panel):
Game menu

- Options menu:
Options menu

- Save menu (load menu is similar):
Save menu

### CODE REVIEW

**Comment by vogonistic** [comment]
This looks great! I wonder how we are going to handle this vs other UI overhauls though.

**Comment by ComputerOverlord** [comment]
I like it

**Comment by buckeyestudios** [comment]
I did something similar - https://github.com/TeamPorcupine/ProjectPorcupine/pull/313 - Maybe a combination of the both of ours would be good.

I like the icons on yours but maybe we could add the text of the button beside it. And also have the localization sill on the main canvas but have the option in the settings to not display it.

Let me know what you think.

**Comment by buckeyestudios** [comment]
Feel free to email me at buckeyestudio@gmail.com and maybe we can work on a new UI for the project. 
I think we can come up with something everyone will like. I also have setting menu I would like to roll on in a new UI. Also while were at it make the UI generated by code so there will be no real reason to mess with the scenes file......

**Comment by vogonistic** [comment]
The conflicts needs to be fixed before merging.

Going forward, I strongly encourage you (@Tim-Ings and @buckeyestudios) to start an issue to discuss what you'd like to see next with the UI so you can split the work in some way.

I'd love to see the UI being generated from code so we see less updates to the scene.

**Comment by vogonistic** [comment]
I'm closing this PR for now. Please coordinate with the people in #540

**Pull request closed without merging**
