### PR TITLE
Added ability to dismiss build mode with right click

### PR DESCRIPTION
**Pull request by RodRitter**
A small change, but hopefully very useful.

### CODE REVIEW

**Comment by NogginBops** [comment]
I think this should be done with the unity input system to be able to remap the controls at startup and run time.

**Comment by RodRitter** [comment]
I am actually thinking about working on that now. If we are going to wait until we have a set standard for input, then we might consider adding this as a hotfix for now. I found it useful while debugging and playing around.

**Comment by TylerVu** [comment]
Doge

**Comment by svmnotn** [comment]
To use the unity input system would require a whole separate PR as it takes a bit more and as @RodRitter said this is more of a quick fix

**Comment by NogginBops** [comment]
That is true. Added a issue for the input manager. #13

**Pull request merged**
