### PR TITLE
[Small] Fixed Furniture Building Instantly

### LINKED ISSUE #1024: Furniture building broken
Since commit #968 building new furniture is broken for me.

Building the first furniture works fine. Then the second furniture is either not built at all or insta-built (despite dev mode being off). In my own PR I also get all atmospheres being set to NaN.

### PR DESCRIPTION
**Pull request by MANDAL0R3**
fixes #1024

### CODE REVIEW

**Comment by bjubes** [comment]
add [Small] to the title, so this gets merged soon!

**Comment by MANDAL0R3** [comment]
Like that?

**Comment by bjubes** [comment]
yeah

**Comment by MANDAL0R3** [comment]
@bjubes Thanks

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
