### PR TITLE
Game menu fixes

### PR DESCRIPTION
**Pull request by TomMalbran**
Before each time a new game menu item was added the whole menu was recreated. Now only the new menu item is added at the right index. This is an alternative fix to #1484. I left the code from that PR, but it could be removed.

Also, game menu items are removed from the waiting list after being added.

### CODE REVIEW

**Comment by mikejbrown** [comment]
I get
```
ArgumentOutOfRangeException: Argument is out of range.
System.Linq.Enumerable.ElementAt[KeyValuePair`2] (IEnumerable`1 source, Int32 index, Fallback fallback)
System.Linq.Enumerable.ElementAt[KeyValuePair`2] (IEnumerable`1 source, Int32 index)
PrototypeMap`1[Furniture].get_Item (Int32 index) (at Assets/Scripts/Models/Prototypes/PrototypeMap.cs:89)
ConstructionMenu.Update () (at Assets/Scripts/UI/InGameUI/MenuLeft/ConstructionMenu.cs:336)
```
when changing localizations and looking at the construction menu.

**Comment by mikejbrown** [comment]
I'm not getting the bug anymore since merging #1501.

**Comment by TomMalbran** [comment]
It was an issue in master, not in this PR. I just merged master, to fix it.

**Comment by mikejbrown** [comment]
Looks good. No obvious new bugs. Merging.

**Pull request merged**
