### PR TITLE
Fix Character Saving Loading

### PR DESCRIPTION
**Pull request by koosemose**
Character names weren't saved or loaded, and this caused characters to not be properly loaded (perhaps they were just invisible?)

### CODE REVIEW

**Comment by TomMalbran** [comment]
The bug when loading was that Visual Paths requires the characters names, and they were null, since they were never assigned when loaded.

You should also save the name after the else on line 1074.

**Comment by koosemose** [comment]
Done.

**Comment by vogonistic** [comment]
I get an error when I try to save. It happens right after `SaveWorld button was clicked.`
```
NullReferenceException: Object reference not set to an instance of an object
Inventory.WriteXml (System.Xml.XmlWriter writer) (at Assets/Scripts/Models/Inventory.cs:144)
World.WriteXml (System.Xml.XmlWriter writer) (at Assets/Scripts/Models/World.cs:894)
System.Xml.Serialization.XmlSerializationWriter.WriteSerializable (IXmlSerializable serializable, System.String name, System.String ns, Boolean isNullable, Boolean wrapped)
System.Xml.Serialization.XmlSerializationWriter.WriteSerializable (IXmlSerializable serializable, System.String name, System.String ns, Boolean isNullable)
System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteObject (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob, System.String element, System.String namesp, Boolean isNullable, Boolean needType, Boolean writeWrappingElem)
System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteRoot (System.Object ob)
System.Xml.Serialization.XmlSerializer.Serialize (System.Object o, System.Xml.Serialization.XmlSerializationWriter writer)
System.Xml.Serialization.XmlSerializer.Serialize (System.Xml.XmlWriter writer, System.Object o, System.Xml.Serialization.XmlSerializerNamespaces namespaces)
UnityEngine.EventSystems.EventSystem:Update()
```

**Comment by koosemose** [comment]
That's another (more serious) bug, where it will crash if a character is carrying inventory. I'm working on fixing that one, atm.

This will just make sure the character is named when loaded, which keeps the path drawing from erroring out.

**Comment by vogonistic** [comment]
Merged.

**Pull request merged**
