### PR TITLE
[WIP] Added a Room graph

### PR DESCRIPTION
**Pull request by mattpott**
This should create a graph that shows how each room is connect to each other. Currently it is not used in the path finding system but that is work for the future.

### CODE REVIEW

**Comment by Jorchay** [comment]
Could you add a photo?

**Comment by ComputerOverlord** [comment]
don't think it does have one

**Comment by FilippoLeon** [comment]
Good job, this was long due. I was about thinking implementing myself: I know how a PITA implementing this has been.

@ComputerOverlord uh?

**Comment by TomMalbran** [comment]
@mattpott If you want to remove the ```GenerateEdgesOutside()``` function, you can implement it after you find a new room in ```GenerateEdgesByRoom(Room r)```, you can check if that room is the outside room and if it is you create a new edge from the new room (the outside one) to ```r``` (the current room).

**Comment by ComputerOverlord** [comment]
@FilippoLeon Someone was asking for an image

**Comment by mattpott** [comment]
@TomMalbran I had thought to do that first but then I ran into some issues with combining two arrays which I wasn't quite sure how to do. 

Also in general I am not sure what to do about the movement cost between nodes and would love any suggestions. At the moment I made it default to 1 and just treat every edge as the same cost but in reality this is not the case as moving through a small room is quicker than moving through a big room.

**Comment by TomMalbran** [comment]
@mattpott I haven't really tested it, so I am not sure if it works, but my idea was to do something like:

At the ```Path_RoomGraph``` constructor you create a Node for the outside room, and a list of edges for that node. You then pass de outside edges list to ```GenerateEdgesByRoom```, and after line 90 of that method you add something like:

```
if (t2.Room.IsOutsideRoom())
{
    Path_Edge<Room> edge = new Path_Edge<Room>();
    edge.cost = 1;
    edge.node = nodes[r];
    outsideEdges.Add(edge);
}
```
Then on line 53 you can do something like ```outsideNode.edges = outsideEdges.ToArray();```


For the movement cost, it will depend on how it is integrated with the path system. I dont know how other games do it. A couple of posibilites is to just calculate the door to door distance in tiles, or the actual movement cost of walking from one door to the other, that can be updated when the furniture, room, floor changes.

**Comment by koosemose** [comment]
It would be greatly appreciated if an API to look up the rooms connected to a given door was able to be made available.

**Comment by mikejbrown** [comment]
This is very good! I just seem to be getting NullReferenceExceptions. Can you confirm https://github.com/mattpott/ProjectPorcupine/pull/1 is a fix?

**Comment by mattpott** [comment]
@mikejbrown I have merged the fix, I also fixed a few extra bits but i don't have the ability to test this at the moment but I will check it when i get home tonight.

**Comment by mikejbrown** [comment]
It's testing fine for me, but I've only had a quick look at it so far.

**Comment by mattpott** [comment]
@mikejbrown Is it generating the correct graph and edges? you should be able to check in the uber logger

**Comment by mattpott** [comment]
Also the graph shouldn't be updating properly when you delete a room

**Comment by mikejbrown** [comment]
Yes, it appears to be generating the correct room. It should be possible to wrap this up into an automatic test (assuming we start with the default map).

**Comment by mattpott** [comment]
yep as long as there is no rooms outside of the ship then the graph should start the same everytime.

**Comment by mattpott** [comment]
One last thing to add is regenerating the graph when a new room is added / destroyed.

**Comment by mattpott** [comment]
This should be hopefully ready now, I will refactor later to make it look nicer.

**Comment by mikejbrown** [comment]
Works for me. :+1: I really like this PR :smile:

**Comment by mattpott** [comment]
yay it no longer conflict.

**Comment by mattpott** [comment]
There are some strange bugs that I am still trying to iron out.

**Comment by Mizipzor** [comment]
This is the second oldest pull request and I feel bad for letting it hang for so long. Poke us when youve ironed out the bugs. :)

**Comment by mattpott** [comment]
It is just frustrating as I am away for 2 days at the moment so I can't work on it. The bugs seem to be when you are creating rooms as they are not properly being cleaned up in the code.

**Comment by Dormanil** [comment]
Your test code seems to have run without problems, even though I couldn't see the UberLogger log messages you sent. Debugging in Visual Studio let me run through the code though, so I know that no errors happened.

**Comment by abackwood** [comment]
Code works on my machine. hen I add a set of new rooms the graph has regenerated correctly. Good job :+1:

**Comment by Mizipzor** [comment]
@abackwood thanks for testing. :)

**Pull request merged**
