### PR TITLE
RE: [Beginner] Prevent furniture from being built along the edges of the world. Fixes #300

### LINKED ISSUE #300: [Beginner] Prevent furniture from being built along the edges of the world
Currently, you can build walls on the last tiles on the edge of the world, but it leads to a lot of checks for tiles outside the map. One common way to fix this problem is to not let the user target the tiles on the very edge of the map. 

Edit `DEFAULT__IsValidPosition()` in `Assets/Scripts/Models/Furniture.cs` so that it doesn't let the user build or place anything within 5 tiles to the edge.

Pay attention to the rules in [CONTRIBUTING.md](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/CONTRIBUTING.md)

This bug was originally reported in #294

### PR DESCRIPTION
**Pull request by lincore81**
In response to this issue: https://github.com/TeamPorcupine/ProjectPorcupine/issues/300
I hope my style is acceptable.

### CODE REVIEW

**Comment by WardBenjamin** [comment]
Looks good other than the line changes on the first and last lines. The change on the first line will prevent #287 from being merged. Fix that, and then this would be great! :+1:

**Comment by vogonistic** [comment]
Looks good to me! You can also include the words "Fixes #300" in the message, and it will automatically close the bug when this is merged.

It's pretty much traditional to have to make an additional change, so expect it.

**Comment by vogonistic** [comment]
@WardBenjamin Has a good point on the first line, that should be fixed.

The last line I think can stay. The way most editors are configured, they'll automatically fix the lack of a new line at the end of the file if it's missing, so adding it now prevents it from happening again next time someone edits it.

**Comment by lincore81** [comment]
Ok. I guess the line endings are messed up, I'll have to look into this.

**Comment by lincore81** [comment]
I re-encoded the file with bom, should be fine now. Would it not be a good idea to standardize the charset+eol?

**Comment by quill18** [comment]
@lincore81 CONTRIBUTING.md details our eol standardization and how to follow it.

Good change -- merging!

**Pull request merged**
