### PR TITLE
Fixed typo in German translation

### PR DESCRIPTION
**Pull request by Cryma**
Just a small typo in the German translation.

### CODE REVIEW

**Comment by relinu** [comment]
load_file -> Datei laden
cancle -> Abbrechen (Momrnntan mit drei b)
Mining drone sollte eher Bergbaudrone heißen

**Comment by relinu** [comment]
Und noch mehr ^^
furn_mining_drone_station_desc=Baut Materialien aus dem Nichts ab.
build= {0} bauen

**Comment by UnknownSoldier1** [comment]
Okay, hab mir bei der Übersetzung zu wenig Mühe gegeben... Naja, gibt hier ja scheinbar welche die meine Fehler ausbessern können :)

**Comment by Mizipzor** [comment]
You might want to stick to English just in case that whoever is to merge this doesnt know German, would be tricky to follow the conversation. :)

**Comment by quill18** [comment]
I'm just going to have to trust that no one is sneaking any dirty limericks into this.

**Comment by UnknownSoldier1** [comment]
@quill18 If you're not sure about it, then just use Google Translate to see if there is anything bad in there.

**Pull request merged**
