### PR TITLE
Updating the Readme image

### PR DESCRIPTION
**Pull request by kd7uiy**
Updated the game image to one more recent

### CODE REVIEW

**Comment by mikejbrown** [comment]
Your PR was fine and I merged it already but I just had a thought... maybe we should put a date on or around the image somewhere so new players can get a quick idea of how out of date it might be?

**Comment by TomMalbran** [comment]
Or maybe we can move the image to the repo:
https://help.github.com/articles/adding-images-to-wikis/

**Comment by mikejbrown** [comment]
Yeah, it'd probably be fine in the repo as long no one commits a stupidly hi res image or changes it too often.

**Comment by TomMalbran** [comment]
If is in the repo you need a PR to change it. In that PR we can decide what to do with the image, and for now we can let people change it, since is an easy PR to merge.

**Pull request merged**
