### PR TITLE
Renamed ObjectType to Type in Furniture

### PR DESCRIPTION
**Pull request by TomMalbran**
We recently started changing to Type in other classes: Inventory, Stats, Needs... If we standardize on Type for all the classes that use the PrototypeManager I can simplify it by using an interface.

### CODE REVIEW

**Comment by dusho** [comment]
If we would go with serialization/deserialization maybe also abstract class (that would hold at least that Type for now).. everything else would inherit from it

**Comment by TomMalbran** [comment]
Sure it could work for that.

For PrototypeManager I need an Interface where the Classes require to have a Type and a ReadXml method. Then I could remove all the individual classes Prototypes classes, which are all almost exactly the same, but I had to make them since most classes used a different way to store the Type.

**Comment by dusho** [comment]
ok cool.. so prototype will be gone. All variables in input class (XML now) are not changeable and dynamic things will be stored inside Parameters (cloning, load game, save game). So load game/save game will just fetch those dynamic parameters..

**Comment by TomMalbran** [comment]
No. What I mean is that FurniturePrototypes, InventoryPrototypes, NeedPrototypes, TraderPrototypes, QuestPrototypes, StatPrototypes, SchedulerEventPrototypes (they are all the same except for the read part) will be replaced by a single class Prototypes where the class that is the prototype will have to implement an Interface which will require a Type and a ReadXml.

**Comment by Grenkin1988** [comment]
I am glad somebody made this after `Inventory`, `Stat` and `Need`. :+1: 

Need to be tested well, could be bugs

**Comment by TomMalbran** [comment]
It will need some testing. But MonoDevelop does a good job on a rename and I did an extensive search for all the ObjectType. On this PR only ones that use ObjectType are in Jobs and in the Trader.

**Comment by Grenkin1988** [comment]
@TomMalbran you should do search for `objectType` also.

**Comment by TomMalbran** [comment]
I did, on both a Case sensitive search and a not case sensitive one.

**Comment by Grenkin1988** [comment]
Tested: build, power, production.
Spotted issue: deconstruction of `Furniture` immediate and do not need `Character`.

**Comment by TomMalbran** [comment]
> Spotted issue: deconstruction of Furniture immediate and do not need Character.
That is how it works in master. I believe that #1002 fixes that.

**Pull request merged**
