### PR TITLE
Log failed unit tests to Travis CI

### PR DESCRIPTION
**Pull request by bjubes**
when a Travis build fails due to a unit test failing, Travis will now log the exact failure at the end of the build log.

here is a sample where two unit test fail:
https://travis-ci.org/bjubes/ProjectPorcupine/builds/157662489

### CODE REVIEW

**Comment by bjubes** [comment]
for comparison purposes, this is a build that failed two unit tests on the current master 
https://travis-ci.org/TeamPorcupine/ProjectPorcupine/builds/157551821

**Comment by Grenkin1988** [comment]
Could we somehow highlight ` success="False" ` ?

**Comment by svmnotn** [comment]
@Grenkin1988 why? from the link it shows the name of what test failed, so there is no need to specifically highlight that they failed (if they are shown, they failed) if anything I think maybe only showing the name property instead of the whole xml line might look better.

**Comment by Grenkin1988** [comment]
I am blind perhaps. Where?
image

**Comment by svmnotn** [comment]
wrong link @Grenkin1988 it is this one: https://travis-ci.org/bjubes/ProjectPorcupine/builds/157662489

**Comment by Grenkin1988** [comment]
O.K. I am blind :-(

**Pull request merged**
