### PR TITLE
WorldGeneration improvements

### PR DESCRIPTION
**Pull request by relinu**
Fixes items spawning in the start area. Start area can now be changed in the worldgen xml file.

### CODE REVIEW

**Comment by Mizipzor** [comment]
It can be merged without conflicts, but youve added some logging lines that breaks because of #609.

**Comment by Mizipzor** [comment]
I pulled your branch and started the game with it and a world was correctly generated. But the log lines needs fixing, you can search replace `Logger.LogError` with `Debug.LogError`, thats what I did. A mere four lines. 

To any other gate keeper, feel free to merge this if the above is addressed.

**Comment by relinu** [comment]
Now it should be fine

**Comment by GamerInspired** [comment]
#636

**Comment by relinu** [comment]
@Mizipzor Everything is fixed

**Comment by Mizipzor** [comment]
Builds without modifications, can still generate a new world. :)

**Pull request merged**
