### PR TITLE
Coal item, and generator requires coal

### PR DESCRIPTION
**Pull request by wilcomega**
Added a coal item with my original sprite that i created, the coal spawns in the world and is used to power the power generator.

also changed the way things spawn and included Ice in it from someone else's commit.

### CODE REVIEW

**Comment by gunthergun** [comment]
Sorry due to me you have conflicts now in the world generator
but you can easily add to the xml file your requirement :)

**Comment by wilcomega** [comment]
Ficed the issues

**Comment by JosephBywater** [comment]
Shouldn't the chances add up to 100%? Or are the percentages of each item being spawned individual? (currently it adds up to 130%)

**Comment by gunthergun** [comment]
everything above 100 % is ignored

**Comment by wilcomega** [comment]
Fixed, 
`<Ressource objectType="Raw Iron" maxStack="50" chance="0.7" />
      <Ressource objectType="Ice" maxStack="10" chance="0.15" />
      <Ressource objectType="Coal" maxStack="20" chance="0.15" />`

**Comment by gunthergun** [comment]
Perfect :D Should be ready to merge now. If only an moderator would be online now

**Comment by wilcomega** [comment]
I cant get my precious coal to spawn, also the menus dont work, is it me and does someone have a sollution

`NullReferenceException: Object reference not set to an instance of an object
MenuController.Start () (at Assets/Scripts/UI/InGameUI/MenuController.cs:31)
`

**Comment by gunthergun** [comment]
Thank you, you found a bug .... there was some testing code in there Line 58 should be: 
int chance = i.stackSize;

it was: 

int chance = ressources[0].stackSize;

**Comment by wilcomega** [comment]
It works, thanks

**Comment by gunthergun** [comment]
Do you still have problems with the menus ?

**Comment by wilcomega** [comment]
Yes but thats a bug i am going to file in the Issues page, you can take a look at it there

**Comment by gunthergun** [comment]
ok thanks for committing the bug for me :) the coal is a really nice idea but wasn't there another guy with power cells or something ? Found it : #370 someone will need to decide which to take

**Comment by Grenkin1988** [comment]
#506 Made changes in order to enable power system to react on changes to ```powerValue```

**Comment by wilcomega** [comment]
Somehow fixed the UI issue, idk how

**Comment by Tranberry** [comment]
Are there natural occurrences of coal in space? Or at the least is it common in space?

**Comment by wilcomega** [comment]
I am not too sure, i would think carbon is availible which is kinda the same, and we can always change it so it requires oxygen or something.

**Comment by gunthergun** [comment]
Best would be if there was a coal power generator and one on power cells. So that in the beginning you search for coal because that is the cheap way but coal is a limited resource and then you switch over to the power cell power generator so essentially we have two generators :)

**Comment by Tranberry** [comment]
I would switch to gas, but I won't complain more than maybe mod it later.

**Comment by Xeni91** [comment]
Well I decided to go with Power Cells, because we are in Space and are not human ... to go with gas or coal seems a bit boring

**Comment by wilcomega** [comment]
but why do we use iron and steel? if we are not human we might as well be using different metals or different materials all together

**Comment by Xeni91** [comment]
was not my idea just saying ^^ and yes you are right

**Comment by Tranberry** [comment]
@wilcomega I'm with you on that, but iron is 'common'.

**Comment by wilcomega** [comment]
True :) but coal is eesentially just carbon, isnt that common too? and we can and probably will change it in the future anyways to something more fitting but for now i think this is a good addition

**Comment by WardBenjamin** [comment]
Fyi, you can't find coal and oil in space since they're both made from biologicals and require huge amounts of compression and such, which will only happen in a gravity well.

Maybe swap out coal with something else? Some kind of nuclear fuel like uranium or something?

**Comment by gunthergun** [comment]
@WardBenjamin can you take only that bug fix or should I make a new pull request ? Because that is kind off important

**Comment by wilcomega** [comment]
If you guys want to you can swap coal out for uranium or something similar. but i am waiting for this thing to get merged or closed

**Comment by gunthergun** [comment]
yes me as well

**Comment by WardBenjamin** [comment]
@wilcomega @gunthergun I'm going to close this, but please do open a new PR with the bug fix!

**Comment by gunthergun** [comment]
@WardBenjamin #495 fixes all of the bugs in the worldgenerator :)

**Comment by wilcomega** [comment]
@WardBenjamin The bugs are fixed, could you be so kind to re-open it?

**Comment by gunthergun** [comment]
@wilcomega he closed this because he does not want coal if you want to have such a system you should make a new PR with uranium or something

**Comment by WardBenjamin** [comment]
@wilcomega @gunthergun I mean, I'm not opposed to having coal in the game, but it's not something that we should have generating in *asteroids*. As far as those go, basically only metals, carbon, and other elements/simple compounds (silicon would be a cool one to add, for computers and stuff) show up in asteroids, and things like ammonia and water (along with misc. rock) show up in comets.

**Comment by gunthergun** [comment]
@WardBenjamin thanks for clearing that up

**Comment by wilcomega** [comment]
New one is #524

**Pull request closed without merging**
