### PR TITLE
[Dev Tool]Sprite to XML tool

### PR DESCRIPTION
**Pull request by Tritaris**
A tool that takes the Sprites you edit in the Unity sprite editor and generates the XML file needed to load sprites from the streaming assets folder. Currently only works with 1 Sprite sheet at a time. To access the tool go to Window > Sprite Sheet to XML.

This is currently working but not as fool proof as it should be. There is a "get_dataPath" error but it still works for testing. I am in need of advice of how I can improve this. I would like to be able to handle more than 1 sprite sheet at a time. Maybe a way to select the sprite you want to export instead of placing it in a folder. 

Any other ideas or tips on how to improve this  would be appreciated.

### CODE REVIEW

**Comment by Tranberry** [comment]
Sounds like something super useful for people (like me) who like tools to do stuff for us :+1:

**Comment by Tranberry** [comment]
Feature request for this would be in no order:

* open input folder button 
* overwrite or rename if same name as file already in output folder

**Comment by bjubes** [comment]
The best way to create this tool IMO is to use unity meta files. When you cut up a sprite in the sprite editor unity saves that info in the images .meta file. For example this is a excerpt meta file of a spritesheet from their example 2D game.
https://gist.github.com/bjubes/c2d480a218326e677e3734430dc884b3
as you can see, unity saves all the necessary information (x,y,width,height,ppu) in YAML. So all you need to do is create a utility that converts their large YAML file into our XML format. Then an artists can work with unity as normal, run your utility, and use the XML file it spits out in their PR for said art.

Hopefully this helps!

**Comment by bjubes** [comment]
@Tritaris I sent you a PR on this branch which adds a button to open the input folder

**Comment by Dormanil** [comment]
@Tritaris Sent you a PR containing a Fix to the XML creation to cope with recent changes to how that XML is read.

**Comment by Tritaris** [comment]
I want to thank @Tranberry , @longtomjr , @Dormanil  and @bjubes with their help and input on this.

**Comment by bjubes** [comment]
glad I could help. I think this is gonna really improve artists workflow

**Comment by vogonistic** [comment]
Who can help test this?

**Comment by bjubes** [comment]
@vogonistic  when I made my addition I tested and it worked very well

**Comment by bjubes** [comment]
Using settings mode, when the source image is in the output folder already an exception is throw.
I set the original image as a png on my desktop, and also selected desktop as the output folder.
```
IOException: Source and destination arguments are the same file.
System.IO.File.Replace (System.String sourceFileName, System.String destinationFileName, System.String destinationBackupFileName, Boolean ignoreMetadataErrors) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/File.cs:414)
System.IO.File.Replace (System.String sourceFileName, System.String destinationFileName, System.String destinationBackupFileName) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/File.cs:381)
SpriteToXML.MoveImage (System.String filePath) (at Assets/Editor/SpriteToXML.cs:504)
SpriteToXML.GenerateXML (System.String filePath, UnityEngine.Texture2D imageTexture) (at Assets/Editor/SpriteToXML.cs:447)
SpriteToXML.ShowVersion2 () (at Assets/Editor/SpriteToXML.cs:377)
SpriteToXML.OnGUI () (at Assets/Editor/SpriteToXML.cs:118)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
```

**Comment by bjubes** [comment]
other than the bug above, this PR works very well and is ready to be merged.

**Comment by longtomjr** [comment]
Tested, and works.

**Comment by vogonistic** [comment]
Merged! Thanks for testing!

**Pull request merged**
