### PR TITLE
Settings xml file

### PR DESCRIPTION
**Pull request by zwrawr**
Added a static Settings class that reads in settings from Settings.xml ,
values of these can be accessed via Settings.getSetting(string key)

Changed world controller to use this system when making a new world.
World size is now controlled by Settings.xml

Adds a couple of debug statements that only log once.

implements settings file as suggested in #21

### CODE REVIEW

**Comment by quill18** [comment]
Looks good, but please remove the "music" files from the commit.

**Comment by Mizipzor** [comment]
Why so many merges? This would be much cleaner if you rebase before you push.

**Comment by zwrawr** [comment]
I'm new to git and so i'm still getting the hang of it

**Comment by zwrawr** [comment]
I need someone to explain to me how i can remove the music meta files from my commit and PR. I am new to git and cannot figure it out.

**Comment by Mizipzor** [comment]
@zwrawr I was looking through the changes and intended to write some instructions on how to rebase this. But your change only really need one commit so I think its easier to start over.

Depending on how new you are to git, [this illustration](https://guides.github.com/introduction/flow/) might make it click. There are loads of articles online explaining this in greater detail, but you basically do this:

 1. Create a new branch for whatever you are about to do. `git checkout -b new-feature`
 2. Copy paste your file and commit, this you already know how to do.
 3. Push the new branch to your Github. `git push origin new-feature`
 4. Create a pull request from the branch on the Github web page.

**Comment by zwrawr** [comment]
I did create a new PR that solves the music meta files issues , but it still has the messy commits , going to try and solve that before i start working on anything new.

**Comment by Mizipzor** [comment]
@zwrawr That's the spirit! :) The point of the project is to learn, and not only C# and Unity but also Git. Take this opportunity to learn how to do it properly.

**Pull request closed without merging**
