### PR TITLE
Buildable Jobs (Furniture Jobs Improvements)

### PR DESCRIPTION
**Pull request by TomMalbran**
This is an improvement on the Furniture Jobs, now Buildable Jobs:
1. Generalized Furniture Jobs into Buildable Jobs.
2. The Utilities now use the Buildable Jobs.
3. Renamed SpawnOffset to OutputOffset and added InputOffset for furnitures that aren't workshops and need 3 spots. (used in the Metal Smelter)
4. Renamed the Tile Get functions into Getters.
5. Moved the Job Complete functions to the World, eventually we could move them to the Furniture and Utility Managers.

### CODE REVIEW

**Comment by sboigelot** [comment]
This branch has conflicts that must be resolved

**Comment by TomMalbran** [comment]
Conflicts fixed.

**Comment by koosemose** [comment]
Conflicted again

**Comment by TomMalbran** [comment]
Conflicts fixed again.

**Comment by kd7uiy** [comment]
More conflicts...

**Comment by TomMalbran** [comment]
And fixed.

**Comment by sboigelot** [comment]
And.. more conflict, sorry Tom :(

**Comment by kd7uiy** [comment]
Just imagine all of the conflicts he's going to cause when he finally submits this build. He'll get his revenge;-)

**Comment by TomMalbran** [comment]
I will add a namespace to every file and get my revenge... hehe

Anyway. fixed for now.

**Comment by koosemose** [comment]
Looks good, works fine, no problems seen, stylecop clean. Merged.

**Pull request merged**
