### PR TITLE
Merge pull request #1 from TeamPorcupine/master

### PR DESCRIPTION
**Pull request by pele90**
update from original

### CODE REVIEW

**Comment by mikejbrown** [comment]
Okay if it's a wrong tutorial directing people to do this then something should be done about it. See #1507 

And #1446 #1330 #1103 #717 #715 #591 #590 #491 #490 #475 #161 #160 #117

**Comment by bjubes** [comment]
What exactly causes these to occur?

**Comment by mikejbrown** [comment]
According to @UnknownSoldier1 on #1507 
>Well, Quill has made in his first tutorial for contributing to GitHub that you can update your local repository by making a PR from this repository to your own local repository. When making a PR it is a little bit confusing if you pull the changes the correct way around which might result in exactly this happening. At least that was the reason for me, I assume thats the issue of other people as well.

There is no reason for people to make pull requests from TeamPorcupine to their own repository. If you want to pull, you just pull.

**Comment by Tranberry** [comment]
won't that PR with predefined PR's help with this, I'm just guessing.

**Pull request closed without merging**
