### PR TITLE
Added fully operating accumulator with placeholder image

### PR DESCRIPTION
**Pull request by Grenkin1988**
P.S.: all number should be optimized later. (Input, Output)
If we wish later to have more thresholds, loading available threshold from prototype should be implemented

### CODE REVIEW

**Comment by Tranberry** [comment]
batterythingy

my proposed accumulator sprite

**Comment by vogonistic** [comment]
Very pretty placeholder =)

**Comment by vogonistic** [comment]
I'm merging this and we can make a new PR to update the graphics.

**Comment by Grenkin1988** [comment]
@Tranberry Please make new PR for graphics

**Pull request merged**
