### PR TITLE
Furniture Drag Types - Drag wall outlines in build mode

### PR DESCRIPTION
**Pull request by RodRitter**
I've added a property into the furniture XML to allow different dragging types for different furniture. By default, if no property has been set, it will fill the area. Add `<DragType>border</DragType>` to allow border dragging. This can be extended to allow other types of dragging in build mode.

Default (No property set) [Stockpile]:
image

Drag type set to border (`<DragType>border</DragType>`) [Basic Wall]
image

### CODE REVIEW

**Comment by WardBenjamin** [comment]
The code looks good, but this probably needs squashed into one commit since there's a bunch of extraneous merge commits. Nice work!

**Comment by Mizipzor** [comment]
I agree, more squashing.

**Comment by NogginBops** [comment]
You should make a guide to squashing... :P

**Comment by Mizipzor** [comment]
There are countless of guides online written by people way better at explaining than I am. [This is my favorite](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html), because its short and precisely to the point.

**Comment by RodRitter** [comment]
Is there no easier way to squash those commits without using git bash? I use source tree to manage everything. My brain doesn't work well on a Friday...

**Comment by WardBenjamin** [comment]
@RodRitter Yep! You can do it in SourceTree: http://blogs.atlassian.com/2014/06/interactive-rebase-sourcetree/

**Comment by Mizipzor** [comment]
If youre strictly following a guide isnt it easier to use the console since that is what all documentation refer to? But hey, whatever floats your boat.

**Comment by RodRitter** [comment]
I'll work from a clean master on my next PR. I don't see this as a big issue right now since my last 3 PR's were merged without a problem.

**Comment by quill18** [comment]
Neat!

**Pull request merged**
