### PR TITLE
Created a work priority tab.

### PR DESCRIPTION
**Pull request by dustinwloring1988**
Created a work panel.like in RimWorld where you can get job priorities.
It will display the Character's name.
The priorities you set don't affect anything yet and don't save.

Control + Left Click - Set To Min
Control + Right Click  - Set To Max
Left Click - Goes Down By One
Right Click  - Goes Up By One

### CODE REVIEW

**Comment by Dormanil** [comment]
Looking good, except it seems like the localization system somehow expects that the `4` and the `X` should have translations. 
snippet

Anyway... how about `right-click` to reduce priority? Also `Ctrl+left-click` to set priority to maximum and similarly `Ctrl+right-click` for priority to minimum?

**Comment by Dormanil** [comment]
Also, characters don't get automatically updated. If a new character spawned or an old one left, you will still see the same menu items.

**Comment by dustinwloring1988** [comment]
@Dormanil will do once I get home, Hum I get the list from World.current.charaters.count should I get it from some were else

**Comment by Dormanil** [comment]
Where you get that list from is probably fine, you just have to update your work panel every time that list changes.

**Comment by dustinwloring1988** [comment]
I do everytime the tab is opened it updates is there a chance that the charesters are not add right

**Comment by Dormanil** [comment]
Oh, I saw it updating every time it is opened, that is not the issue. The issue is: You had the tab open for a longer period of time and one of the characters died. You didn't notice that, and the tab doesn't update either, so when you try to change the priorities of that character, `NullReferenceException`s could be seen in the console.

**Comment by dustinwloring1988** [comment]
o ok will look at that also. Thanks for the help.

**Comment by dustinwloring1988** [comment]
@Dormanil - Fixed Thanks for testing it.

You can now do the following;
Control + Left Click - Set To Min
Control + Right Click  - Set To Max
Left Click - Goes Down By One
Right Click  - Goes Up By One

**Comment by NogginBops** [comment]
@dustinwloring1988 What happened to this? Did it get merged or was it dropped?

**Pull request closed without merging**
