### PR TITLE
Fix no name being shown

### PR DESCRIPTION
**Pull request by Ceddini**
Okay, finally. Here is the "quick" fix.

Oh, btw... Stupid regex. I don't like it!

### CODE REVIEW

**Comment by RodRitter** [comment]
I see you changed `lines.Length-1` to `lines.Length` - Are you sure thats not going to throw an out of bounds exception if it tries to get the last name?

**Comment by Ceddini** [comment]
@RodRitter The tooltip said the max is excluded, so I thought this would be correct

**Comment by RodRitter** [comment]
Nope, I just tested it - You might want to change it back :)

`c.name = lines[lines.Length];`

image

**Comment by Ceddini** [comment]
Fixed it, but this tooltip says differently :(

random_range

**Comment by RodRitter** [comment]
I think that's a bit misleading. I've tested it and it's definitely not exclusive. Good job nonetheless :)

**Comment by Ceddini** [comment]
Thank you very much. From now on, I will just go with what I know from java because there I have to use -1!

**Pull request merged**
