### PR TITLE
Power System fix

### PR DESCRIPTION
**Pull request by Grenkin1988**
Now that was really embarrassing :-(

### CODE REVIEW

**Comment by bjubes** [comment]
I'm confused as to why you used `ProjectPorcupine.Power` in your code after including it in a using statement. Shouldn't you just use on or the other? or is another namespace have a power class that is causing a conflict?

**Comment by Grenkin1988** [comment]
Have no idea why, but compiler refuse to use `System` without full path in `PowerSystemTest`

**Comment by JupiterJoe** [comment]
The compiler is confused between two things (System namespace and System class) that have exactly the same name.

**Comment by bjubes** [comment]
yeah, in retrospect `system` is a terrible name for a class

**Comment by bjubes** [comment]
maybe rename it to `powerSystem` or `powerNetwork`?

**Comment by quill18** [comment]
Agreed that a rename to PowerNetwork would likely be best.

**Comment by quill18** [comment]
Actually, the namespace should probably also be PowerNetwork.

**Comment by Grenkin1988** [comment]
Renamed to `PowerNetwork`

**Comment by bjubes** [comment]
If possible could you make your diff cleaner for PowerGridTest.cs. Its not essential if you can't, but currently git says you deleted and added 280 lines

**Comment by Grenkin1988** [comment]
@bjubes I moved it to `namespace ProjectPorcupine.PowerNetwork.Test` so I think this is just git gets insane

**Comment by bjubes** [comment]
Merged!

**Pull request merged**
