### PR TITLE
Delete button

### PR DESCRIPTION
**Pull request by Koljenka**
so this is the redone version of #89 so it looks exactly the same. I hope that this will be merged soon so that there wont be any conflict issues. :wink:

### CODE REVIEW

**Comment by ComputerOverlord** [comment]
You should upload a screenshot to comply with rules...

**Comment by Koljenka** [comment]
@ComputerOverlord look at the screenshots in #89 its the same.

**Comment by Koljenka** [comment]
delete

**Comment by ComputerOverlord** [comment]
@Koljenka Oh :P
I know but It looks different with the new changes so... Yeah it will look _mostly_ the same

**Comment by Koljenka** [comment]
delete this is the "new" version.

**Comment by ComputerOverlord** [comment]
I don't know why I even asked Haha...

**Comment by Koljenka** [comment]
but i think it looks way better with the new save dialog because now the button isnt squeezed so much but has alot of space :laughing:

**Comment by ComputerOverlord** [comment]
@Koljenka Yeah

**Comment by Koljenka** [comment]
sure

**Comment by Koljenka** [comment]
I thougt that that would be **very** useful.

**Comment by Koljenka** [comment]
sure

**Comment by Koljenka** [comment]
i think "File" has to be "file", right? :laughing:

**Comment by bjubes** [comment]
nitpicking but you probably put the "Delete File?" above "you cannot revert this action" and put the affirmative option on the right aka switch the yes and no buttons. That's the general appearance of most modals in almost every UI.

**Comment by Koljenka** [comment]
@bjubes  ok ill do that.
But its upper case in "Load File..." so i'll leave it like this.

**Comment by bjubes** [comment]
file can be uppercase because its the title of the window. as long as the words "Delete File" are above the other text, i think leaving it uppercase is fine

**Comment by Koljenka** [comment]
sure
there you go.

**Comment by Koljenka** [comment]
i hope that @quill18 adds this first and then #201 because i dont want to do this again. :smiley:

**Comment by Koljenka** [comment]
delete
Now Im really satisfied with how it turned out. :+1:

**Comment by ComputerOverlord** [comment]
@Koljenka Yeah, that would really suck

**Comment by quill18** [comment]
Merged!

**Comment by WardBenjamin** [comment]
Looks great!

**Comment by Koljenka** [comment]
yea 👍

**Pull request merged**
