### PR TITLE
Cosmetic changes to LocalizationTable class

### PR DESCRIPTION
**Pull request by Grenkin1988**
What do you think about this changes?
```line.Split('=');``` i think .NET know how to work with strings efficiently?

### CODE REVIEW

**Comment by Mizipzor** [comment]
You seem to have done the same cleanup I did in #362. :)

Maybe base your work on that? Or should we just see whoever gets merged first? XD

**Comment by Grenkin1988** [comment]
@Mizipzor Yes, you've done more in missing localization part, and I changed other parts

**Comment by Mizipzor** [comment]
I can probably merge your branch if you want. Or just replicate your changes, but then it would like look I committed them and its important to me that you get proper credit.

**Comment by RodRitter** [comment]
I've just merged the cleanup from #362 - If you can merge those changes in your code and solve the conflict, I can merge this.

**Comment by Mizipzor** [comment]
I just pulled his branch, there are merge conflicts but they are big and easy to see.

@Grenkin1988 Are you comfortable resolving merge conflicts? If not, this is an awesome learning experience. :) If you dont want to resolve but still want these changes in just toss your branch and start over based on latest master. Either way, I'm willing to help you with the Git wrangling, if you want.

**Comment by Grenkin1988** [comment]
Brobably this is it.

**Comment by Mizipzor** [comment]
Hm not really, you reverted most of my changes. :/

Consider installing and running StyleCop, thats what I did to guide my cleanup (StyleCop is the Microsoft style).

**Comment by Grenkin1988** [comment]
@Mizipzor Than I will start again later in the evening. Need to go.

**Comment by Mizipzor** [comment]
Very well, take care. :)

**Comment by UnknownSoldier1** [comment]
@Grenkin1988 By looking at your code for replacing my code with string.Split(), it seems that you implemented an exception if there are two or more '=' in a line. What I did was intentional, in case in any language for whatever reason an '=' is required for a localization that it still works.

**Comment by Mizipzor** [comment]
Its true that if the value itself contains a `=` then only the text between the first and second would be used, the rest would be skipped. This could easily be fixed by adding a max: `.Split("=", 2);`

**Comment by UnknownSoldier1** [comment]
Alright, that I didn't know actually.

**Comment by Grenkin1988** [comment]
@Mizipzor Could I close this PR and open new one? I am going to do total undo. Or it is neened for history tracking? (Never worked with git, I am using TFS at work)

**Comment by Mizipzor** [comment]
@Grenkin1988 If you want to start over that is absolutely what you should do. :)

**Comment by Grenkin1988** [comment]
Closing this as going to undo everything and start from beginning

**Pull request closed without merging**
