### PR TITLE
Added keyboard reaction

### PR DESCRIPTION
**Pull request by FilippoLeon**
This is a new script that shoul be added, I suggest, to a new controller named "Camera Controller" or something (that is supposed to be extended). This controller should handle all the main camera movements. This is a super small contribution to break the ice with the project.

What can also be added are keys for controlling time (once implemented), for zoom, etc.

Also: tab to switch character?

### CODE REVIEW

**Comment by Mizipzor** [comment]
You should probably configure MonoDevelop to follow the code style, details in [CONTRIBUTING.md](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/CONTRIBUTING.md). Also, doesnt the camera already do this?

**Comment by FilippoLeon** [comment]
Mhhh, I'm using VS15, so it should already be following the project's conf. 

But I see there is something wonky with tabs/spaces.

AFAIK the camera doensn't respont to WASD.

**Comment by bjubes** [comment]
I think its adding keyboard controls to move the camera, so u can move it if you have a laptop and no mouse making left click drag difficult. However I don't think this requires a seperate script

**Comment by WardBenjamin** [comment]
As of the current version, camera movement with WASD/Arrow Keys is either not implemented or broken.

**Comment by FilippoLeon** [comment]
@bjubes I know that there is no need for a separate script for a one-liner.

But I suggest the following: use this script as base to handle other keyboard presses, like speed change (when implemented), character change (e.g. with tab), ...

**Pull request closed without merging**
