### PR TITLE
Changed UI - Menus

### PR DESCRIPTION
**Pull request by buckeyestudios**
Changed the way the UI menus are. Now they are similar to RimWorld

### CODE REVIEW

**Comment by JosephBywater** [comment]
Screenshots?

**Comment by buckeyestudios** [comment]
https://drive.google.com/open?id=0B9eUB0oiQzwEb3NlbmZyb2pPQXM
https://drive.google.com/open?id=0B9eUB0oiQzwENlBKazMtTGpsYW8
https://drive.google.com/open?id=0B9eUB0oiQzwEb28weXZjUld5bm8

**Comment by JosephBywater** [comment]
👍

**Comment by vogonistic** [comment]
Is it hard to attach the popup-menu to the button that was clicked, so the Options buttons pops up close to the Options menu?

**Comment by satch3l** [comment]
Looks good. It's at least one step towards a better UI.

**Comment by buckeyestudios** [comment]
@vogonistic - no just wanted to see if people like this before i continued working on this and wanted to have this as a base if others had better ideas.

I also have a nice settings menu almost done with skins.... But will need to save some of the setting the user chooses into the save file.

**Comment by vogonistic** [comment]
@buckeyestudios You and @Tim-Ings should probably coordinate. He just posted #320, which has significant overlap.

**Comment by buckeyestudios** [comment]
@vogonistic   funny you said that as I was adding a comment on his post you posted this.....

**Pull request closed without merging**
