### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by omridevk**
Update README.md file with a reference to the playlist.

### CODE REVIEW

**Comment by quill18** [comment]
Two people will a similar quick fix! Have to decline one of them.

**Comment by omridevk** [comment]
yeah the other one is better :)

**Comment by omridevk** [comment]
@quill18 
Mind if I do some refactoring?

**Comment by quill18** [comment]
@omridevk It would be a pretty crummy open source project if I said no!

**Comment by omridevk** [comment]
Have to say good job and love your videos. Information that is very difficult to acquire online. A job well done indeed.

**Comment by Don42** [comment]
@quill18 Since people often disagree about formatting and style it would probably good to define those before there are conflicting pull requests.
I don't know if there are standard formatting guidelines for C#, but if there are, a link would probably be helpful.

**Comment by Koljenka** [comment]
please dont do it like this: "method() {" do it like this: "method{" just to add to that formatting thing.

**Comment by omridevk** [comment]
This is the C# convention:
https://msdn.microsoft.com/en-us/library/ff926074.aspx
@Koljenka one way or another does not really matter, as long as it is consistent across the entire code base. Choose one way, use it everywhere.

**Comment by quill18** [comment]
Yeah, I use everything in the C# convention (AFAIK)...except that I like to put my brace on the same line as the if.  E.G.:

`if (blah) {`
`    DoSomething();`
`}`
`else {`
`    DoSomethingElse();`
`}`

If the majority of people are religiously opposed to this, I could force myself to change. :)

**Comment by omridevk** [comment]
I would even go as far as saying that you should avoid using 
```
else
```
all together. 

As in  SmallTalk coding guide (only one way to avoid else statements):
http://c2.com/cgi/wiki?GuardClause
and (Martin Fowler refactoring book):
http://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html
Polymorphism is another great way to avoid elseif and switch cases.
Covered in a great Google Clean Code talk:
<https://www.youtube.com/watch?v=4F72VULWFvc>

**Pull request closed without merging**
