### PR TITLE
added double click to load and save only in code

### PR DESCRIPTION
**Pull request by alexisfcote**
Double clicking on a listitem now register like an okay was clicked.
Changed from the method with tags in scene.

### CODE REVIEW

**Comment by Koljenka** [comment]
this conflicts with #194 , just saying.

**Comment by WardBenjamin** [comment]
This should probably be closed now that #194 is merged.

**Comment by quill18** [comment]
This conflicts now. Please update from master, merge, and push again.

Sorry you lost the race. :(

**Comment by quill18** [comment]
@WardBenjamin I don't think it has to be closed -- as long as an update is made to remove the conflict it should be okay (though closing & redoing the PR also works.)

**Comment by WardBenjamin** [comment]
Fair enough @quill18. I don't think it's really a necessary feature now that #194 provides an easier and more obvious way to do it, but up to you!

**Comment by Koljenka** [comment]
#194 and #201 do completely different things

**Comment by quill18** [comment]
@WardBenjamin I'm confused -- I didn't think #194 did the same thing as this.

**Comment by Koljenka** [comment]
@quill18 #194 does not add the double click thing

**Comment by WardBenjamin** [comment]
Looks like I was incorrect, thanks for the.... correction :P

I was under the impression that this just would delete on double-click, but that's not what it's for.

**Pull request closed without merging**
