### PR TITLE
Trade foundation ui & model

### PR DESCRIPTION
**Pull request by sboigelot**
As requested by @vogonistic 

here is a small rimworld-like trade ui.

The UI work with models, the models are

- Trade
- Traders
- Inventory from the code base

The UI will NOT make the trade happen, this will be something to develop as part of the game, this merge request is here to facilitate future trade feature development.

Change in the scene were requiered to add a new dialog box.

image

Sample code to setup a new trade is available in DialogBoxTrade.cs

```
public void DoTradingTestWithMockTraders()
{
	Trader mockPlayer = new Trader
	{
		CurrencyBalance = 500,
		Name = "Player",
		SaleMarginMultiplier = 1f,
		Stock = new List<Inventory>
		{
			new Inventory("Steel Plate",50,10){ basePrice = 3f},
			new Inventory("Raw Iron",100,90){ basePrice = 0.2f},
		}
	};
	Trader mockTrader = new Trader
	{
		CurrencyBalance = 1500,
		Name = "Trader",
		SaleMarginMultiplier = 1.23f,
		Stock = new List<Inventory>
		{
			new Inventory("Steel Plate",50,40){ basePrice = 3f},
			new Inventory("Steel Plate",50,40){ basePrice = 3f},
			new Inventory("Oxygen Bottle",10,10){ basePrice = 50f},
		}
	};
	SetupTrade(new Trade(mockPlayer,mockTrader));
}

```

### CODE REVIEW

**Comment by RodRitter** [comment]
I think you should add the [WIP] tag in your title

**Comment by Mizipzor** [comment]
@RodRitter Cant you add a WIP label? :)

**Comment by RodRitter** [comment]
Naw, then he won't be able to remove it when he is ready to merge :P

**Comment by sboigelot** [comment]
It is ready to merge, the feature requested is just the UI & models.

This is a foundation to allow all of us to define trade features

**Comment by RodRitter** [comment]
Ok, I'm going to wait for a bit more feedback from the community first.

**Comment by sboigelot** [comment]
@RodRitter  no problem ,)

**Comment by koosemose** [comment]
Purely from a design standpoint, it looks functional purely as a base from which a trade system can be developed. It will certainly make it easier for future development on trading (i.e. the actual traders coming and and logistics related to that.) Presumably in the future it will be cleaned up and any tweaks made to more closely fit whatever future trading system we end up with.

**Comment by Mizipzor** [comment]
Im all for the wild west chaos thats currently going on. If it doesnt break anything, lets merge it and see if someone builds upon it. :)

**Comment by sboigelot** [comment]
@koosemose  yes that's the spirit :)

There was no conflicts one hour ago, don't know what changed, should I update my branch by merging the latest upstream master into it?

**Comment by RodRitter** [comment]
Yep, bring in the latest from remote master and merge it with yours. There will be files that have conflicts. You need to manage that code manually or use a tool to handle the merge conflict.

https://githowto.com/resolving_conflicts

**Comment by sboigelot** [comment]
The main problem is the unity scene, I copy my version of the scene to a _Scene_TradingSample scene and use the upstream file as the _scene_

If the merge is done, we can copy the trading dialog box from the trading sample scene to the main scene. Until then, we should keep them separate to avoid having merge conflict each time someone merge a PR in master.

**Comment by RodRitter** [comment]
Ok merged. Let's see what people can do with this.

**Comment by sboigelot** [comment]
Yheaaaa :D Thanks

**Comment by vogonistic** [comment]
Awesome!

**Pull request merged**
