### PR TITLE
Gui changes

### PR DESCRIPTION
**Pull request by relinu**

### CODE REVIEW

**Comment by Tranberry** [comment]
Would really appreciate a screen shoot

**Comment by relinu** [comment]
screenshot01

Nothing special, just a few changes ^^'

**Comment by relinu** [comment]
screenshot02

**Comment by SquareMan** [comment]
I like the pause menu a lot, but I worry that the new build menu might have some cropping issues when the screen gets smaller, perhaps the canvas should be set to scale? Thats a discussion for a another place and totally not the concern of this branch. Good work!

**Comment by quill18** [comment]
Your commit includes changes to 36 files -- due in part (but not exclusively) to end-of-line issues -- many of which are unrelated to your PR topic. Please check CONTRIBUTING.md and adjust your settings.

**Pull request closed without merging**
