### PR TITLE
Added text for power generator.

### PR DESCRIPTION
**Pull request by SanteriHetekivi**
I noticed that Power Generator (#78) does not have its name set in a button.

**Before**
image

**After**
image

This request fixes that text and also adds missing BuildingJob tags for Power Generator.

The name barely fits the button and I have already opened issue (#164) for button resizing.

### CODE REVIEW

**Comment by ComputerOverlord** [comment]
Good, simple, bugfix!

**Comment by quill18** [comment]
I'm afraid that branch has conflicts that must be resolved.

**Comment by SanteriHetekivi** [comment]
@quill18 Conflicts have been resolved.

**Comment by SanteriHetekivi** [comment]
@quill18 There are also #186, #236, #256 and #297 that fixes this problem, so if mine is conflicted again next time those does mostly the same thing.

So next time pulls are made hopefully this or any other does not have conflicts so the fix gets implemented and people don't keep fixing this one over and over again. :)

Sadly i live in Finland so I'm usually sleeping when pulls are made, so if there are conflict again in this one I will probably not be there to fix them at once.

Here hoping one of these PR gets trough without conflicts next time. :D

**Comment by SanteriHetekivi** [comment]
Currently fixing conflicts

**Comment by SanteriHetekivi** [comment]
@quill18
Now it is ready for merge.
Added @Ceddini 's changes from PR #186 based on conversation on issue #299

> That being said, if you want to, you can pull from my PR and take my changes. @Ceddini

**Comment by SanteriHetekivi** [comment]
So now this also contains changes from #186 containing German localization.

**Comment by SanteriHetekivi** [comment]
Git started to mess with my indentations and as a perfectionist that drove me crazy. 
That is why there are 22 commits. :)

Now they are perfect :D

**Comment by henninglive** [comment]
@SanteriHetekivi This can be fixed by doing a interactive rebase and squashing them together.

**Pull request merged**
