### PR TITLE
Add lua files to the auto-generated solution/project files

### PR DESCRIPTION
**Pull request by sboigelot**
As the title says, add the lua files to the auto-generation of the solution/project by the vs studio extension of Unity.

image

Note:
To anyone using this and VS 2013, I suggest you adding a VS extension to color the lua code and have auto completion (for instance https://visualstudiogallery.msdn.microsoft.com/7782dc20-924a-4726-8656-d876cdbb3417)

### CODE REVIEW

**Comment by mikejbrown** [comment]
Does this also work in Monodevelop? (sorry -- don't have time to test at the moment) If so, :shipit: :+1: :+1: :+1: .

**Comment by sboigelot** [comment]
@mikejbrown no idea, someone with monodevelop should try :)
This is just the c# project generation of Edit -> Project Settings -> Editor so it's just changing the `ProjectPorcupine.sln`

image

If your IDE reads the .sln, then it should work

**Comment by koosemose** [comment]
This works wonderfully in Monodevelop as well. And monodevelop even seems to have syntax highlighting for the Lua as well.

**Comment by sboigelot** [comment]
@koosemose thanks for the test :)

**Comment by TheRiven** [comment]
Tested on my VS Community 2015 and the Lua files do now show up and it also shows the syntax without me having to add anything :+1:

**Comment by koosemose** [comment]
Alright, all looks good any functional. Merged.

**Pull request merged**
