### PR TITLE
Added Metal Smelter

### PR DESCRIPTION
**Pull request by UnknownSoldier1**
I added a new type of furniture, the metal smelter. It will smelt Raw Iron (which is now produced by the Mining Drone) into Steel Plates.
Since I'm a terrible artist, the two textures i made are only dummies and should be replaced by somebody who has more tallent than me.

### CODE REVIEW

**Comment by NogginBops** [comment]
@UnknownSoldier1 Screenshot would be appreciated.

**Comment by UnknownSoldier1** [comment]
game screenshot

**Comment by Mizipzor** [comment]
1. Commit 3ab09cf shouldnt be part of this branch.
2. There are some music related changes that dont belong here.
3. Read [this](http://stackoverflow.com/questions/6406762/why-am-i-merging-remote-tracking-branch-origin-develop-into-develop) for how to get rid of the "merge remote-tracking branch" commits.

This is not required but it does make the pull request much cleaner. I would advice you to take this opportunity to learn some Git. Also, a clean pull request is much easier to evaluate.

**Comment by UnknownSoldier1** [comment]
Alright thanks, I think I'm gonna read this to make sure this won't happen with my next pull request.

**Comment by quill18** [comment]
Love the smelter, but will close this PR due to the conflicts and such. Definitely try to resubmit again once you have this resolved!

**Comment by UnknownSoldier1** [comment]
GitHub is messy right now, I think it is due to my local repository being outdated, but the GitHub client says that my repository is up to date, even though it clearly isn't. Trying to look into that, but I can't figure out the issue right now.

**Comment by UnknownSoldier1** [comment]
Updated PR at #165

**Pull request closed without merging**
