### PR TITLE
Headline now fits the text vertically

### LINKED ISSUE #1174: Headline Generator - scale the size of the text box
How would we scale the size of the text box to fit the current amount of text on screen.

### PR DESCRIPTION
**Pull request by kd7uiy**
Fixes #1174 This will limit the display box for the headline to what is visible.

capture

### CODE REVIEW

**Comment by frankitox16** [comment]
Great, I was about to say that they were too big :+1: good job!

**Comment by mikejbrown** [comment]
Why closed?

**Comment by kd7uiy** [comment]
I thought this was merged and deleted the branch. Woops... Fixing it now.

**Comment by kd7uiy** [comment]
Okay, couldn't re-open this, but I opened another, #1182 . One of these days I'll learn Git properly...

**Pull request closed without merging**
