### PR TITLE
Remove Namespace From Unit Tests

### PR DESCRIPTION
**Pull request by bjubes**
When unit tests have namespaces the unity editor gets ..weird
tests

This removes the namespaces in the power unit tests.
after
^ much better :)

unfortunately, most of the changes git notices are fixing indentation, only 4 lines were actually modified

### CODE REVIEW

**Comment by mikejbrown** [comment]
Sometimes the diff algorithm boggles me...

**Comment by vogonistic** [comment]
Add `?w=1` to the url and it'll ignore whitespace changes

**Comment by TomMalbran** [comment]
@mikejbrown Here: https://github.com/TeamPorcupine/ProjectPorcupine/pull/1160/files?w=0

I dont like how namespaces in C# require the curly braces.

**Comment by mikejbrown** [comment]
Good to merge as soon as Travis catches up :)

**Pull request merged**
