### PR TITLE
Ignoring .db files (attempt 2)

### PR DESCRIPTION
**Pull request by frankitox16**
Hopefully this time there's no conflict with the whitespaces...
otherwise, I don't know what's going on (As it seems that MonoDevelop
even with the given settings in CONTRIBUTING.mb kept using the previous
ones, I used VS and "formatted" the whole document). If this isn't the
case, then I guess there's something that I'm doing wrong and gotta look
better into.

### CODE REVIEW

**Comment by quill18** [comment]
I'm afraid there's still a conflict.  Make sure you pull in the lastest changes from the TeamPorcupine master into your branch -- you are likely out of date.

**Comment by frankitox16** [comment]
so, guess I shoud keep trying?

**Comment by bjubes** [comment]
I had a conflict with white spaces too. What I did was
1. get the latest master
2. Try to fix line endings in sublime under view > line endings in my feature branch 
3.  While on feature branch run 'git merge master' and fix conflicts from there

**Comment by Mizipzor** [comment]
@frankitox16 Your change is trivial so I think its easier to start over rather than merging or rebasing.

1. Close this pull request.
2. [Sync your fork](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging).
3. Create a branch with ´git checkout -b some_name´. Do not reuse your branch name (unless you delete it first) it important that it starts from your (current) master.
4. Push the branch and create a pull request as you've already done.

Its true that the whitespace in that file is messed up. It uses tabs but the project has specified to stick to spaces. That change, however, should happen in a separate pull request.

**Comment by frankitox16** [comment]
@bjubes unix line endings?

**Pull request closed without merging**
