### PR TITLE
Fixed enumeration modification error in cbJobCallbackComplete

### PR DESCRIPTION
**Pull request by NogginBops**
There was a problem with a lua function registering a callback which modified a currently enumerated list causing a enumeration modification error. This changes the iteration so that they iterate through a copy list.

### CODE REVIEW

**Comment by Mizipzor** [comment]
What was actually fixed here? Arent these lines equivalent? I would like a discussion here before its merged, because if this actually fixes something it might be hiding another bug.

**Comment by dusho** [comment]
List cbJobCompletedLua (that is looped through using foreach) is modified (new item added) by code in LUA script:
`j.RegisterJobCompletedCallback("MetalSmelter_JobComplete")`
So what NogginBops submitted actually fixes the problem.
But ye, the question is whether it shouldn't be safer to enumerate through copy of list (as scripts can add of remove jobs):
`foreach (string luaFunc in cbJobCompletedLua.ToList())
            {
                FurnitureActions.CallFunction(luaFunc, this);
            }`

**Comment by Mizipzor** [comment]
Ah, of course, why didnt I think of that. Yes, continue iterating on a modified collection is not allowed, forcing the developer to make a decision. This is a tricky case, because if:

1. The item is added at the beginning and wont be processed and also offset index by one making the current item being process twice.
2. The item is added to the end and will be processed, which might be what we want.

But, neither of these are apparent. And someone might do something similar but use 1) leading to weird bugs. 

I would be okay with merging this. I just wanna wave the red flag a bit.

**Comment by quill18** [comment]
Would a better fix be to make a copy of the list and iterate over that?  That would ensure that all callbacks present at the beginning of the update would get processed exactly once.

Newly-added callbacks wouldn't get processed until the next frame... which is probably more correct since they probably don't want to be told that already finished is "completed". They're probably looking to be informed about the newly generated job being completed.

**Comment by Mizipzor** [comment]
@quill18 Indeed, the norm as far as Im aware is to make a copy (with linq `.ToList()`) if you need to change to source collection as you iterate. If you **really** need to handle new items added to the collection as it is enumerated, I'd argue that's code smell.

**Comment by NogginBops** [comment]
Ok, then I will change it to that. @Mizipzor @quill18

**Comment by dusho** [comment]
then same should be applied to all the enumerations with LUA calls, right
Job.cs, ln 20; Job.cs, ln 218, ...

**Comment by NogginBops** [comment]
@dusho Will do that!

**Comment by Mizipzor** [comment]
@NogginBops Please add [WIP] or something to the tile so it isnt merged until its complete. We would add a label for this but you cant add or remove labels yourself.

**Comment by dusho** [comment]
actually there is some code duplication there.. ln.194-204 and ln.211-222, so maybe it can be unified there.. then have cbJobWorkedLua.ToList() and cbJobCompletedLua.ToList() only...

**Comment by quill18** [comment]
Looks like there's some mix-ups between cbJobWorkedLua and cbJobCompletedLua in there.

**Comment by NogginBops** [comment]
@quill18 Realized that at the moment after the push

**Comment by NogginBops** [comment]
Now this should be working!

**Pull request merged**
