### PR TITLE
[WIP] Utility Objects

### PR DESCRIPTION
**Pull request by SteelFall**
This does not yet contain pipes but is a base for utility objects. Most of the scripts are just adaptations of the furniture scripts and will be modified as needed in the future.

### CODE REVIEW

**Comment by NogginBops** [comment]
You shouldn't create a new UtilitiActions class, use the LuaUtilities class instead instead

**Comment by SteelFall** [comment]
@NogginBops Ah yes, I saw that when I encountered some conflicts. Just forgot to remove the class.

**Comment by SteelFall** [comment]
I appear to still need it for parts of the BuildModeController but I will change the UtilityActions class to look like the updated FurnitureActions class.

**Comment by SteelFall** [comment]
Trying to get things fixed has started to break more things.

**Comment by SteelFall** [comment]
Encountering technical difficulties which removed my classes and will not let me revert to a stable commit. Will redo everything tomorrow but for now this PR is closed.

**Pull request closed without merging**
