### PR TITLE
[WIP] Uberlogger

### PR DESCRIPTION
**Pull request by Mizipzor**
Ok, this is a big one. Trying to improve our logger I stumbled across [UberLogger](https://github.com/bbbscarter/UberLogger). It's MIT licensed, yes I checked. Should we use it?

* Specifically I was trying to solve #453, which is something UberLogger does.
* Though we sadly lose the Verbose level, which was my own concept. :(
* However! This one has a custom console window in the editor that appears to be much better at handling spam. 
* And, it already has channels, something that was next on my list, which helps to cut down on noise. 
* I also has an in game console, which I find rather neat.

This **does not** need to be merged if you want to try it out for yourself. Simply pull the branch from my repository. 

Thoughts?

### CODE REVIEW

**Comment by Sommerbo** [comment]
I like it! A logger isn't rocket science and using a self-contained module module is good.

**Comment by bjubes** [comment]
if anyone doesn't know how to test this PR, I made a quick tutorial in the wiki

**Comment by Mizipzor** [comment]
This will probably be difficult to merge since I have to touch *every* line that logs. I wont work on the conflicts until the decision to merge this have been made.

**Comment by quill18** [comment]
In-game console + file logger? Sounds great to me.

:+1:

**Comment by Mizipzor** [comment]
I'll take that as a go ahead.

**Pull request merged**
