### PR TITLE
Solar Panel

### PR DESCRIPTION
**Pull request by abackwood**
Adds a Solar Panel furniture to the game.

The solar panel is large and inefficient, only producing 3 power for a 2x3 tile coverage. It can only be built outside, though it is (for now) the only furniture that can be built on ladders. It requires no work from characters.

Power supply is entirely determined by Lua function, so the `<Power>` tag doesn't technically do anything.

They include an `efficiency` parameter that is a modifier on the base power output. In the future, this can be changed if for whatever reason the panels are more or less efficient in some situations.

Sprite by @Yurgeta

### CODE REVIEW

**Comment by Mizipzor** [comment]
How do I build this? I put down some ladders but were not allowed to put down the solar panel. Bug?

**Comment by abackwood** [comment]
Some code got reverted for reasons unknown to me. Fixing now

**Comment by Mizipzor** [comment]
Yay! Testing actually prevented something, heh.

**Comment by abackwood** [comment]
This should be fixed now

**Comment by Grenkin1988** [comment]
Please undo changes to Settings.xml

**Comment by Mizipzor** [comment]
While testing this it seems the workers only build floors, never ladders. :/

**Comment by abackwood** [comment]
Ladders cost 1 steel to make. Not sure who added that, but there you go

**Comment by abackwood** [comment]
I also accidentally broke the link with the sprite when i made it meet style standard. Will fix in a moment when im at my laptop again

**Comment by Tranberry** [comment]
maybe solar panels should generate power based on new game parameters eg. close to star gives much power and far from a star almost no energy.

**Comment by abackwood** [comment]
This seems to work perfectly on my end now. Not sure what was going on yesterday :smile:

**Comment by Tranberry** [comment]
can't see any link to the issue..

**Comment by Mizipzor** [comment]
I finally figured out how to build the solar panel. :)

**Pull request merged**
