### PR TITLE
[help] Added MusicController and SpaceTheme

### PR DESCRIPTION
**Pull request by Ferr013**
I 've commited only the .wav file and the script.
[help] Still need someone able to implement it in the game without messing up the scene as I did in my previous attempts.

### CODE REVIEW

**Comment by MANDAL0R3** [comment]
I could be wrong about this but i think its better to wait until we can import the sounds/music from StreamingAssets.

**Comment by Sommerbo** [comment]
I agree with @MANDAL0R3 use of "Resource" folder should be minimal. Music and sound should reside in /Assets/StreamingAssets/Music

**Comment by Ferr013** [comment]
I moved the file from Resources to StreamingAssets. I'll leave the code fixing to someone more experienced.

**Comment by quill18** [comment]
Since .WAV files are so large (due to being uncompressed), I'm *thinking* we should change it out for a compressed version instead.

Please refer to issue #795, which I just opened up, for a discussion.

**Comment by quill18** [comment]
Also, you may want to join the conversation over at Music style/feel for Project Porcupine #631

**Comment by Ferr013** [comment]
@quill18 Thank you for the advise! I've heard that mp3 has some problem with looping, because it add some kind of information on the head or the end of the file that interrupts for some (perceivable) istant the music when it starts over. Do you have any suggestion about the codec to adopt in this case? 
I'll look up the conversation right now!

**Comment by longtomjr** [comment]
@Ferr013 Check out here #795 We will use .ogg files it seems.

**Comment by Ferr013** [comment]
I'm trying to load from StreamingAssets, but it throws a null reference exception.
Can anyone help me figure it out please?

`#region License
// ====================================================
// Project Porcupine Copyright(C) 2016 Team Porcupine
// This program comes with ABSOLUTELY NO WARRANTY; This is free software, 
// and you are welcome to redistribute it under certain conditions; See 
// file LICENSE, which is part of this source code package, for details.
// ====================================================
#endregion

using UnityEngine;
using System.Collections;

[RequireComponent (typeof (AudioSource))]
public class MusicController : MonoBehaviour
{
    AudioSource backgroundMusic;
    public string defaultTrack = "SpaceTheme";

    void OnEnable()
    {
        PlayTrack(defaultTrack);
	}

    public void PlayTrack(string title)
    {
        backgroundMusic = GetComponent<AudioSource>();
        AudioClip ac = LoadMusic(title);
        backgroundMusic.clip = ac;
        backgroundMusic.loop = true;
        backgroundMusic.Play();
    }

    private AudioClip LoadMusic(string title)
    {
        string filePath = Application.streamingAssetsPath;
        filePath = System.IO.Path.Combine(filePath, "Music");
        filePath = System.IO.Path.Combine(filePath, title + ".ogg");

        byte[] dataAsByteArray = System.IO.File.ReadAllBytes(filePath);
        Debug.Log(dataAsByteArray.ToString());
        float[] dataAsFloatArray = ConvertByteToFloat(dataAsByteArray);

        AudioClip audioClip = new AudioClip();
        audioClip.SetData(dataAsFloatArray, 0);

        return audioClip;
    }

    private float[] ConvertByteToFloat(byte[] byteArray)
    {
        float[] floatArray = new float[byteArray.Length / 4];
        for (int i = 0; i < floatArray.Length; i++)
        {
            if (System.BitConverter.IsLittleEndian)
                System.Array.Reverse(byteArray, i * 4, 4);
            floatArray[i] = System.BitConverter.ToSingle(byteArray, i * 4) / 0x80000000;
        }
        return floatArray;
    }
}`

**Comment by mattpott** [comment]
I have got it to play a noise but it is not music. Instead of using

`new AudioClip();`
use
`AudioClip.create()`
This is what i used to make sounds 

`AudioClip audioClip = AudioClip.Create(title, dataAsFloatArray.Length, 1, 44100, false);`

**Comment by mattpott** [comment]
Looks like we need to use a solution something like this. http://answers.unity3d.com/questions/499028/onaudioread-buffer-changing-sizes.html

**Comment by Ferr013** [comment]
@mattpott Thank you very much! Now it works fine!
I've added a prefab but not in the scene to avoid messing up things.

**Comment by mattpott** [comment]
At the moment I am not getting any sound when I test this unless I add the script from with in the editor.

**Comment by mattpott** [comment]
Also one potential problem with use nvorbis is that the licence is not compatible with the GPL licence we are using. https://nvorbis.codeplex.com/license

**Comment by svmnotn** [comment]
@Ferr013 what is the state of this PR? Also please fix the conflicts

**Comment by mattpott** [comment]
We may have to revert this back to using the unity system for loading music from the assets folder and later down the line we can move this back to streaming assets.

**Comment by sboigelot** [comment]
This branch has conflicts that must be resolved

**Comment by sboigelot** [comment]
@Ferr013 What is the status of this PR on your side?

Maybe you should make a PR with just the music files in the streaming asset?

**Comment by Ferr013** [comment]
Sorry for the lack of care about this project. Here is what I can do, if it can't be of any help, I'll open a PR with only the music.

**Comment by sboigelot** [comment]
@Ferr013 no problem about the lack of care, we all have life ;) It would be great if you could just make a pr for the music indeed. I would do it, but it would be better with your name on it for posterity.

**Comment by sboigelot** [comment]
We now have a PR allowing us to load sound files from the streaming asset. Closing this PR.

**Pull request closed without merging**
