### PR TITLE
Fixed forgotten txt & lang file extension in .gitattributes and normalized line endings.

### PR DESCRIPTION
**Pull request by QuiZr**
This leaded to problems in committing same .txt files but with different line endings like in #165.
Never ending line endings story... >.>

### CODE REVIEW

**Comment by WardBenjamin** [comment]
Looks good! I would also add .md.

**Comment by henninglive** [comment]
This does not fix the end-of-line problem for me, but i think i have i a theory of what's happening. The text files in the font directory contain CRLF line endings since they were added to the repository before end-of-line normalization was enable through #41. Normalization ensures that all files that Git considers to be text will have normalized LF line endings in the repository, but when checking files in and out the line endings will be converted to the native line ending for your platform.

When @quill18 enabled normalization he forgot to normalize the existing files in the repository. The fix for this is to allow someone to commit the normalized files.

From [git documentation](https://git-scm.com/docs/gitattributes):
> When text=auto normalization is enabled in an existing repository, any text files containing CRLFs should be normalized. If they are not they will be normalized the next time someone tries to change them, causing unfortunate misattribution.

**Comment by vogonistic** [comment]
I vote we add the pesky .txt files in the Fonts and Music directories to this story and get it sorted out once and for all. It's sad to see so many PR's be rejected.

**Comment by QuiZr** [comment]
@henninglive Yeah, I think that this is our problem.
@vogonistic I've added those .txt files - this should be now resolved once and for all (as long as this request get's accepted)

**Comment by Raketfart** [comment]
Yes please! This hopefully would solve all my git problems

**Comment by WardBenjamin** [comment]
This definitely needs merged @quill18. Normally .txt files would be recognized as text by git, but since we're using a custom .gitattributes file they're being recognized as binary, and the line endings are being changed per-PC, which is leading to a lot of extraneous line changes in pull request.

**Comment by Mizipzor** [comment]
Yes, this is a problem in many pull requests. It should be a priority.

**Comment by vogonistic** [comment]
@QuiZr Can you fix the conflict so we can get this merged?

**Comment by QuiZr** [comment]
Done

**Comment by vogonistic** [comment]
@quill18 This one needs merging for 🎉 😻 .

**Pull request merged**
