### PR TITLE
Code Driven Dialog Boxes [Ready]

### PR DESCRIPTION
**Pull request by dustinwloring1988**
I know this is a rather big merge but I think it will be for the better since it was focused on making the UI more code driven like @quill18, and I think most of us, wanted from the start.
 
- All dialog boxes are now code driven.
- KeyboardController is not a monobehaviour.
- DialogBoxManager now is code driven
Other small changes to make the UI more code driven

After this get accept I should have another ready tomorrow after work that will finish up making the UI "more"code driven.
YAY FINALLY!!!!!!!!!!!

### CODE REVIEW

**Comment by bjubes** [comment]
Please explain exactly how to make a dialog box in your new system. If this change does go through we all need to know how to work the new UI

**Comment by dustinwloring1988** [comment]
First off sorry im on my phone I will make a pdf with picture if it gets accepted.

How To make a new Dialog Box
- Make a empty scene.
- Make your dialog box in here then save the prefab to the Resource Folder.
- Delete the new scene you made.
- Open the DialogBoxManager and copy a box of code that made and input your new info there.

How to open your dialog box(from a button)

- Put a script on your dialog box the derived from DialogBox.
- Get a refreance to DialogBoxManager.
- Call that with get component your refreance name for DialogBoxManager. Then the refreance your script name with "." showdialog.
- Done.

**Comment by dustinwloring1988** [comment]
@bjubes  - done
Next commit I do will have the menu update and it now uses a gride layout this will be nice for rescaling.

**Comment by Mizipzor** [comment]
Marked as [WIP], more commits incoming.

**Comment by dustinwloring1988** [comment]
No, it not a work in progress spliting up the uploads as to keep the changes smaller.

**Comment by dustinwloring1988** [comment]
Hoping this will get accepted in the next couple hours then I can have a fresh branch to work on the other changes when I get home and all will be done tonight. This way by this time tomorrow no more SCENE changes.YAY!!!!!!!!!!   👍 :)

**Comment by dustinwloring1988** [comment]
I will be closing this pull in about 2.5 hours from now. I just though getting the UI out of the SCENE was IMPORTANT.

**Comment by WardBenjamin** [comment]
@dustinwloring1988 This can't be merged because it conflicts. If you can fix these then we can properly look at it and (hopefully) merge it.

**Comment by dustinwloring1988** [comment]
When I get home I will fix it once that is it I'm not going to keep fixing it over and over it's been up for 24 hours and needs posted or it's obvious that nobody wants it

**Comment by Mizipzor** [comment]
You have to understand that this young project is moving extremely rapidly, everything is volatile. Scene changes is a known problem and this is and extreme example. If you're tired of playing catch up with the other work, maybe find someone that can pick this up? 

Or maybe find someone to just test it. While there are a few us that can actually merge it, *anyone* can test it. Finding someone thats willing to pull your branch, test it, and come here and formally vouch for it would speed it up greatly.

**Comment by dustinwloring1988** [comment]
@WardBenjamin  @Mizipzor   It works now

**Comment by dustinwloring1988** [comment]
Please commit so I can finish the UI stuff so we dont have conflicts with the SCENE anymore it is driving me crazy

**Comment by svmnotn** [comment]
Seems to \/
alt text

**Comment by svmnotn** [comment]
Other than the following:
- the `temp_trade` button in options
- if any changes are made to the settings you get `UnassignedReferenceException`

Not sure if these are in the scope but they do work in master.

**Comment by dustinwloring1988** [comment]
Those will be the first 2 I fix just I just dont want to make this commit change any more files

**Comment by dustinwloring1988** [comment]
@svmnotn   -  Thanks for testing it

**Comment by WardBenjamin** [comment]
Looks good! Please do fix those issues though.... better to get this merged now though. Merging!

**Pull request merged**
