### PR TITLE
[WIP] Mod manager

### LINKED ISSUE #1713: Mod Selector and Saving
I'm working on a mod selector, are these good features?
* Selection menu
* JSON mod data
* ~image~, title and description
* active mods saved in save file and settings
* ~`graphical` setting makes mod not get saved with save file and load after other mods~
* Load order editable in mod selection menu
* `doNotSave` bool makes mod not be included in save

### PR DESCRIPTION
**Pull request by Dan54**
### The issue this fixes

Closes #1713 

### What this PR does

This adds:
* Mod selection menu (mods not loaded until scene change or reload)
* JSON mod data
* Title and description
* Active mods saved in save file and settings
* Mod load order editable in mod selection menu
* `doNotSave` bool makes mod not be included in save
* `ModUtils.IsModLoaded(string modName)`
modmenu
mod warn

### Additional Changes

* SoundController - bug fixes
* AudioManager - bug fix
* DialogBox - bug fix
* UIMenuController - bug fix
* OverlayMap - accident

[Test Mods.zip](https://github.com/TeamPorcupine/ProjectPorcupine/files/671944/Test.Mods.zip)

### CODE REVIEW

**Comment by UnknownSoldier1** [comment]
I really like the button design, looks really nice!

**Comment by koosemose** [comment]
You've got a lot of changes unrelated to this PR. Please keep the changes focused on the purpose of the PR, and if any changes are required in systems not directly related please note them in your post.

Additionally, if you could add some sample mods, that would greatly aid testing this PR.

**Comment by BraedonWooding** [comment]
@UnknownSoldier1 hehe its my design he used my menu :P

**Comment by UnknownSoldier1** [comment]
@BraedonWooding Okay I didn't know that, I haven't been active here for a while...

**Comment by BraedonWooding** [comment]
It crashes upon startup.  Your lists haven't been initialized.  Also just clarifying you shouldn't be using my menu in the end, since it was made for mod options, such as 'enable this part of this mod' or whatever, stuff for mods to implement (have a look at SettingsMenuFunctions for more under StreamingAssets/CSharp/SettingsMenuFunctions.cs.  You can use all UI elements (that were made by me :P, so they aren't the best quality tbh), but you will have to implement it separately, I highly recommend that you still use the SettingsMenu component system purely because it can handle the whole mod order stuff but use the system in the new mod menu.  Anyways looks good, normally with things like this you need a WIP tag (just [WIP] in your title), a little list of checkboxes of progress, and since you change a lot of different files just a little description on each change that is not relevant or that changes currently functionality :D.

**Comment by Dan54** [comment]
I will redevelop most of this and create a new pr.

**Comment by Dan54** [comment]
New PR Here #1725

**Pull request closed without merging**
