### PR TITLE
Power system initial prototyping with tests (reopened)

### PR DESCRIPTION
**Pull request by Grenkin1988**
This is reopen of #761

On next PR I am going to implement:
1. Parse `Furniture` and enchance it with `PowerRelated`
2. Change `PowerSystem` with `LivePowerSystem`

Firsts part of work for #602

### CODE REVIEW

**Comment by Grenkin1988** [comment]
@vogonistic @NogginBops OK, I'll put code in namespase should it be Power of PowerSystem?

**Comment by NogginBops** [comment]
I think it should be power.

**Comment by vogonistic** [comment]
I vote `Power`. Do you want to do it here? Otherwise I'll merge it now.

**Comment by Grenkin1988** [comment]
@vogonistic @NogginBops OK, that it is going to be:
```
namespace Power 
{
    public class Connection { }
    public class Grid { }
    public class System { }
}
```

**Comment by vogonistic** [comment]
That looks fantastic!

**Comment by Grenkin1988** [comment]
@vogonistic I will get to my computer only in 8 hours. Probably on next PR :-)

**Comment by vogonistic** [comment]
Just to be explicit, merge this PR now and you'll include the namespace in next PR?

**Comment by Grenkin1988** [comment]
@vogonistic Yes, I will make next PR for namespase. After that I am going to make this work

**Comment by vogonistic** [comment]
Had to do a manual merge due to a weird .meta issue, but I went with it anyway. Have to manually close this PR.

**Comment by Grenkin1988** [comment]
@vogonistic Thanks

**Pull request closed without merging**
