### PR TITLE
Readd ProjectSettings.Asset

### PR DESCRIPTION
**Pull request by koosemose**
Per discussion in #1488 this readds ProjectSettings.Asset, which will allow us to set build version, Company Name, Application Name, Game Icon, and api compatibility level.

### CODE REVIEW

**Comment by NogginBops** [comment]
How will different unity versions be handled with this?

**Comment by dusho** [comment]
isn't Unity version held within ProjectVersion.txt?
I have there:
```
m_EditorVersion: 5.4.0f3
m_StandardAssetsVersion: 0
```

**Comment by koosemose** [comment]
If there is anything that changes based on version used to open, we'll just have to rely on people not committing it if they don't intentionally change it, there's just too many settings we need to have set consistently for the project to leave it out.

**Comment by NogginBops** [comment]
@koosemose @dusho :+1:

**Comment by bjubes** [comment]
Going ahead with this merge. Project settings is needed to consistently set settings within unity. Unfortunately some other information such as editor version can also make its way into the file. If we standardize on a unity version, it shouldn't be an issue.

**Pull request merged**
