### PR TITLE
Repatriate en_us.lang in main repository (Fixes #1197)

### LINKED ISSUE #1197: Repatriate localisation file or not
Some time ago the localisation file have been moved to a different repository:

https://github.com/QuiZr/ProjectPorcupineLocalization/tree/Someone_will_come_up_with_a_proper_naming_scheme_later

This has been done at a time where localisation was new, a lot of PR were coming in and the gatekeeper were overflowed by them.

But currently it force everyone that add a single line of text to do it in a different PR, on a different repo.

Is this still something we want?

### PR DESCRIPTION
**Pull request by sboigelot**
Add exception to the gitignore for

!/Assets/StreamingAssets/Localization/en_US.lang
!/Assets/StreamingAssets/Localization/en_US.lang.meta

Add exception for the localization downloader for en_US.lang*

### CODE REVIEW

**Comment by sboigelot** [comment]
Fixes #1197

**Comment by kd7uiy** [comment]
I still think we should just pull the entire repository in to this one, but maybe that's just me...

**Comment by sboigelot** [comment]
same for me but this is an un-discussed start

**Comment by mikejbrown** [comment]
I think this was the minimal action that everyone agreed to, so may as well do it now. Tested, nothing obviously breaking. :+1::+1::+1::+1:

**Comment by QuiZr** [comment]
Yeah - It will break stuff: ClearLocalizationDirectory function - after fresh pr in localization repo (which @quill18 still didn't move to the TeamPorcupine account) en_US.lang will be deleted and replaced by nothing.

**Pull request merged**
