### PR TITLE
Saying that you need Unity 5.4 in README

### PR DESCRIPTION
**Pull request by vringar**
Just a little something that would have helped me out.

### CODE REVIEW

**Comment by Mizipzor** [comment]
Its already stated in the contributing.md file, i dont think it needs to be there as well.

**Comment by vringar** [comment]
I just wanted to check it out, so i didnt read the contributing rules.
Other might do the same

**Comment by Tranberry** [comment]
@Mizipzor I think it does fit there

**Comment by mikejbrown** [comment]
No real reason not to have it here, right?

**Comment by WardBenjamin** [comment]
Thanks!

**Comment by mikejbrown** [comment]
@vringar Congrats on your first successful PR! :tada:

**Comment by vringar** [comment]
:tada: :balloon: :tada:

**Comment by vringar** [comment]
@mikejbrown thanks

**Pull request merged**
