### PR TITLE
Added delete save

### PR DESCRIPTION
**Pull request by Koljenka**
This adds a small button in the top right corner of the LoadGame dialog which deletes the selected savegame.

### CODE REVIEW

**Comment by Tranberry** [comment]
is this compatible with #65 ?

**Comment by Koljenka** [comment]
yes it should.

**Comment by Koljenka** [comment]
delete

**Comment by Koljenka** [comment]
delete
so it looks like this now the X is always on the line of the selected savegame.

**Comment by quill18** [comment]
This is a good feature, but it now conflicts with #65, which I have merged in.  Please pull in the updates and re-apply.

**Comment by Koljenka** [comment]
@quill18 I will do that right now ;).

**Comment by Koljenka** [comment]
ok there is still a conflict in the scene but im working on it.

**Comment by Koljenka** [comment]
So i dont know how to get rid of the merge conflicts in the scene so im going to start from scratch tommorow... :disappointed:

**Comment by bjubes** [comment]
you may want to try using a merge conflict tool like kdiff3. It gives you a GUI to help see exactly what is conflicting. May not be terribly helpful for scene related stuff since its not actual code, but maybe it will help

**Comment by quill18** [comment]
Closing this due to conflict.  Please make a new PR when you have updated to the latest master and resolved the conflicts.

**Comment by Koljenka** [comment]
i fixed it in #194 .

**Pull request closed without merging**
