### PR TITLE
StyleCop + add missing meta

### PR DESCRIPTION
**Pull request by sboigelot**

### CODE REVIEW

**Comment by koosemose** [comment]
Looks good, Merged.

**Comment by TomMalbran** [comment]
It seems that this PR added some additional meta files.

**Comment by sboigelot** [comment]
@TomMalbran it's in the title :) Are they bad meta files?

**Comment by TomMalbran** [comment]
Assets/Scripts/Models/Inventory.meta : we dont have an inventory folder
Assets/Scripts/UI/DialogBox/Job List.meta : We dont have a Job List folder

**Comment by sboigelot** [comment]
This is due to folder renaming. We should avoid this, git doesn't like it much :s

**Comment by sboigelot** [comment]
I still have plenty missing meta on master, what about you?
image

**Comment by TomMalbran** [comment]
Those meta files are there. I just have 2 meta files that Unity decided to delete, since there are no files/folders for them. You can check the files in GitHub, and see that those files

screen shot 2016-09-12 at 2 34 36 pm
 are there.

**Pull request merged**
