### PR TITLE
Adds Power Generator to Localization

### PR DESCRIPTION
**Pull request by DevOrc**
Adds a Power Generator Localization Name
Also adds it to the English Lang file

### CODE REVIEW

**Comment by Ceddini** [comment]
The translation is already part of #169 with many different languages.

**Comment by DevOrc** [comment]
Yes, but it currently has a conflict

**Comment by SanteriHetekivi** [comment]
@DevOrc No it does not?
For me it says: This pull request can be automatically merged by project collaborators

**Comment by Ceddini** [comment]
@DevOrc @SanteriHetekivi Same for me, no conflicts.

**Comment by DevOrc** [comment]
Ok, maybe I am just crazy

**Comment by DevOrc** [comment]
Ok, I am probably crazy

**Pull request closed without merging**
