### PR TITLE
[Done]New cloning pod With Animation

### PR DESCRIPTION
**Pull request by longtomjr**
Any help would be appreciated, I don't know what I am doing. :p 
Sprite by @Tranberry ! 
I want a slow animation when the cloning pod is bieng worked :)

### CODE REVIEW

**Comment by MANDAL0R3** [comment]
I approve of the new Sprite :D

**Comment by longtomjr** [comment]
I just want to give special mention to @MANDAL0R3 and @TomMalbran for really helping me out understanding the code and contributing snippets :)

**Comment by Raketfart** [comment]
Works on my maching :+1:
Very nice

**Comment by Dormanil** [comment]
Sent you a PR that makes the sprites work with the newly merged SpriteManager differences.

**Comment by longtomjr** [comment]
has been optimized and cleaned up. Is ready to go. Needs testing again please :)

**Comment by longtomjr** [comment]
to test this PR: `git fetch upstream pull/1005/head:new_cloning_pod`
more info here
https://github.com/TeamPorcupine/ProjectPorcupine/wiki/How-to-Test-a-Pull-Request

**Comment by MANDAL0R3** [comment]
Finally may my first sprite i created in my life be put to rest in the recycling bin lol

**Comment by Dormanil** [comment]
I get this error spam as I try to build a Cloning Pod:

snippet

**Comment by longtomjr** [comment]
Fixed the error, PLease test again :)
Thanks for testing

**Comment by Dormanil** [comment]
Looking good. 
The sprites are now loading and don't throw errors now!

**Pull request merged**
