### PR TITLE
[ART] Updated Iron and Steel sprites

### PR DESCRIPTION
**Pull request by TheRiven**
Time to stop being lazy and contribute again :sleeping: 

Replaced Iron ore and Steel sprites with ones that are more in keeping with the "current" art style.

ironset_1
ironset_2

Also changed the XML for the Steel sprite to work with the new size.

NOT included in this update is the new Iron ore mining "spot" sprite as this is not currently implemented into the game.
ironset_0

However if people feel it should be included in this PR rather then a later one please say so and I will add it in.

Referencing #607

### CODE REVIEW

**Comment by TheRiven** [comment]
Apparently there is another PR for Iron and Steel (also Uranium which I have produced some sprites for but not yet put into a PR) #1008 

So if people would have a look at that one as well and see what they think that would be great.

**Comment by Raketfart** [comment]
Looks great. I prefer this raw Iron!

**Comment by Tranberry** [comment]
I'm biased towards your submission. I believe this fits best with the current direction of the game, luckily I'm in no authority to be a nepotist.

**Comment by longtomjr** [comment]
I vouch for this. It replaces art that is needed. It is also great. I thank the heavens everyday for having this to lay my eyes upon. Also, glad @TheRiven stopped playing EU4 and committed this :P

**Comment by Mizipzor** [comment]
Thats enough for me. Merged.

**Pull request merged**
