### PR TITLE
Fixes heater quest bug

### PR DESCRIPTION
**Pull request by kd7uiy**
The heater quest cannot be finished without this small fix.

### CODE REVIEW

**Comment by bjubes** [comment]
why is heater lowercase while every other furniture is capitalized?
Is heater just named inconsistently?

**Comment by kd7uiy** [comment]
Because... Reasons? I agree with you, I'll switch it around.

**Comment by sboigelot** [comment]
This branch is breaking the Heater sprite
image

It's still working on master

**Comment by Grenkin1988** [comment]
@kd7uiy You should rename this also
image

**Comment by kd7uiy** [comment]
That's what I get for not properly testing it... Thanks guys!

**Pull request merged**
