### PR TITLE
Remove old Cloning Pod, correcting center point 

### PR DESCRIPTION
**Pull request by kd7uiy**
capture

### CODE REVIEW

**Comment by Geoffrotism** [comment]
Why is the cloning pod 2x3? Is clearly is two tiles wide but it only goes back one tile according to the size of the base. It's just really tall.

**Comment by TomMalbran** [comment]
The graphic is technically 2x3. Anything smaller and it will get clipped. I think that it should be change to either be 2x2 or a different thing.

**Comment by Geoffrotism** [comment]
The graphic might be 2x3 in pixels but the visual representation makes it look like a 2x1. Basically it looks like you should be able to place some on the tile in the middle of that room.

**Comment by TomMalbran** [comment]
But we don't have support for layers, so placing anything behind will not work, and we might not even need to support them with the right perspective. The real issue is that the perspective is kind of wrong in that graphic, is too facing forward for our game.

So this change is fine for how the game works and how the graphic was done.

**Comment by dusho** [comment]
We don't need layers to solve overlaps of overreaching tiles.. Do we? Just need to set render order of furniture according to Y position - same as we have for characters.

**Comment by Raketfart** [comment]
I agree with dusho. We should probably set sortorder on furniture anyway, so characters can walk behind furniture

**Comment by kd7uiy** [comment]
capture

**Pull request merged**
