### PR TITLE
[Small] Update Unity 5.4 download link to stable

### PR DESCRIPTION
**Pull request by hcorion**
The download link goes to a unity beta download, which is for 5.5.0. Unity 5.4 is now stable.

### CODE REVIEW

**Comment by hcorion** [comment]
Also deleted fmod64.dll.meta from the old location.

**Comment by koosemose** [comment]
Is there a link we can use that would directly lead to the project required version, as the store link seems to only be a slight improvement, since it will change as "current version" changes, and we may not wish to do so, depending on changes made.

**Comment by hcorion** [comment]
Is this something we want though? being that it took this long to change the download link from a generic beta version of unity to a generic stable version. I think it would be more maintainable if we just pointed them to the latest stable version. 
Regarding your question, the closest thing I could find was the Unity download archive, but as far as I can see I can't find a way to point to a specific version without alienating users on other OS (i.e., pointing to a windows .exe) https://unity3d.com/get-unity/download/archive

**Comment by BraedonWooding** [comment]
You could always do something like:Download current unity [5.4]:Windows: www.windowsDownload.whateverMac: www.macDownload.whateverLinux (no linux build yet, except for an experimental).

**Comment by zwrawr** [comment]
I like @BraedonWooding's suggestion. Here it is with the correct links

Download **Unity 5.4.2** [Windows](https://unity3d.com/get-unity/download?thank-you=update&download_nid=43049&os=Win) | [Mac](https://unity3d.com/get-unity/download?thank-you=update&download_nid=43049&os=Win)

**Comment by BraedonWooding** [comment]
Yeh, that looks really good!  A definite improvement on the current one.

**Comment by koosemose** [comment]
Looks good to me

**Comment by BraedonWooding** [comment]
Note: @zwrawr make sure you do another commit to make the changes said in your comment.

**Comment by hcorion** [comment]
Well, if we're going to be providing separate downloads for each OS, why not provide a linux link as well?

**Comment by hcorion** [comment]
Ok, I have changed it based on @zwrawr 's input. You can look at the new version here: https://github.com/hcorion/ProjectPorcupine/blob/change-download-link/README.md
I'm thinking a squash and merge would be the best for this PR.

**Pull request merged**
