### PR TITLE
Added all Furniture_OnCreated sounds

### PR DESCRIPTION
**Pull request by Jaytheway**
### List of added sounds

Deconstruct Furniture (3 variants, not implemented)
Door - also there are not implemented Door_Open and Door_Close sounds
Airlock Door
Floor (5 variants)
Heater
Berth
Small Landing Pad
Oxygen Compressor
Oxygen Generator
Air Pump
Vent
Fission Reactor
Power Cell Press
RTG
Accumulator
Solar Panel

Ambiance - sample for future implementation testing.

...basically OnCreated sounds for all Furniture that we currently have (except ladder and bed)

Also there is a Default_Furniture_OnCreated sound that we need to swap with currently used Error sound.

### CODE REVIEW

**Comment by BraedonWooding** [comment]
These are sweeeeet.  Nice man :D.

**Comment by Jaytheway** [comment]
Wow, thank you Braedon! I'm probably gonna be tweaking them as I add new ones for the dynamic events, such as mining, fire, emergency etc.

**Comment by hcorion** [comment]
👍 Awesome

**Comment by koosemose** [comment]
Just so that Unity doesn't complain, if you could just open the project in Unity, and commit the changes so the meta files generate, that would be appreciated.

**Comment by Jaytheway** [comment]
Pushed meta files, although for some reason it added changed `ProjectSettings/ProjectSettings.asset`.
I don't even know why is it changed.
How do I delete it from the latest commit push?

**Comment by hcorion** [comment]
Here is the easiest way, just [download the old one](https://github.com/TeamPorcupine/ProjectPorcupine/raw/master/ProjectSettings/ProjectSettings.asset), replace the file, git push, done.

**Comment by Jaytheway** [comment]
Thanks @hcorion, just did that :)

**Comment by koosemose** [comment]
Unfortunately ProjectSettings occasionally changes randomly (not really random, but due to no obvious changes), but we have to include it because otherwise we can't set certain important settings for the project. So it's just one of those things we have to be mindful of to try not to commit.

**Comment by Jaytheway** [comment]
Well, I'm gonna watch out next time. 

I guess this can be merged now (?)

**Comment by koosemose** [comment]
Merging. Could you create an issue with listing the sounds you've implemented that don't have hooks yet? Otherwise I'm likely to forget about it completely over the holidays.

**Pull request merged**
