### PR TITLE
Currency Prototypes

### PR DESCRIPTION
**Pull request by TomMalbran**
Converted the currencies into prototypes used by the player and the trader. The starting balance was moved (temporarily) to World Generator, until we have Scenarios.

Ping @sboigelot since you are working on the Trading system.

### CODE REVIEW

**Comment by sboigelot** [comment]
@TomMalbran I can't look at the code for now, but I agree with the concept! 👍  (I'll check the code later tonigth if no-one do it before me, anyother GW, feel free to merge if the code works good)

**Comment by koosemose** [comment]
Conflicts

**Comment by TomMalbran** [comment]
Fixed.

**Comment by koosemose** [comment]
Was it intentional to change the trade dialog from showing the short name to showing the full name of the currency?

**Comment by TomMalbran** [comment]
Fixed the conflicts.

@koosemose No, there was an issue when cloning the currency. Good catch.

**Comment by koosemose** [comment]
Looks good, no stylecop issues. Merged.

**Pull request merged**
