### PR TITLE
Fixing doors: Update surrounding furniture when create and removing furniture

### PR DESCRIPTION
**Pull request by Raketfart**
When placing or removing furniture, all surrounding furniture gets
updated. Regardless if they are same type or connects to neighbours.
This also works for furniture larger than 1x1.

So when placing a wall north/south of a door, will now make the door rotate correctly.
Still not a perfect solution for rotating furniture like this.

### CODE REVIEW

**Comment by BeefEX** [comment]
Please call cancelJobs() on deconstructed furniture as well. This is much better than mine.

**Comment by Raketfart** [comment]
Thanks, I added cancelJobs along with a check for furniture null (not sure if that's necessary)

**Comment by rfmsimoes** [comment]
Hi,

Your change in FurnitureSpriteController is ulesse ,because the IF you paste is executed in here:
          -> furn_go.GetComponent<SpriteRenderer>().sprite = GetSpriteForFurniture(furn);

The GetSpriteForFurnite will do that IF !!

In Furniture.cs I think you shouldn't remove the validation  if (obj.linksToNeighbour) because is if you have one furniture that doesn't have same behaviour like wall...you don't need to check the neighbours, for example 2 chairs....they don't link each other because they are distinct furnitures

**Comment by Raketfart** [comment]
I guess the linksToNeighbour check can stay in, because it's the wall that is placed last. 
I agree that the furn.objectType == "Door" is a temporary fix. We'll have to see how we fix rotatable furniture like doors properly.

**Comment by BeefEX** [comment]
@Raketfart I wanted you to add it because it was the other change i did in my fix, and this is better so i will close mine, but then cancelJobs() fix wouldnt be done at all :smile:

**Comment by Raketfart** [comment]
@BeefEX Yes, I understand, and thanks for the comment. I call cancelJobs() in Deconstruct(), so I hope that's alright.

**Comment by Raketfart** [comment]
Weird conflict. I'll try to add a new PR

**Pull request closed without merging**
