### PR TITLE
Ignore ProjectSettings.asset

### PR DESCRIPTION
**Pull request by BraedonWooding**
As the title says, update the .gitignore to ignore project settings.  Won't affect current PRs, but future.

### CODE REVIEW

**Comment by hcorion** [comment]
While your at it you could ignore .DS_Store

**Comment by BraedonWooding** [comment]
I can't find any .DS_Store (I know it exists but search is revealing nothing), can you give me an file address for it?

**Comment by hcorion** [comment]
Just add `*.DS_Store` it is a Mac only file that is created whenever you open up a folder in the file manager.

**Comment by BraedonWooding** [comment]
Ohhh got it !

**Comment by koosemose** [comment]
We cannot ignore ProjectSettings. If we do any new developers (who don't already have the current ProjectSettings, will be unable to compile.

**Comment by BraedonWooding** [comment]
Oh okay fair point

**Pull request closed without merging**
