### PR TITLE
Fix caracter names parse text file

### PR DESCRIPTION
**Pull request by Ohda**
The names of my caracters was the whole text file.

### CODE REVIEW

**Comment by JupiterJoe** [comment]
Rather than `File.ReadAllText `and `Regex.Split` you could use `File.ReadAllLines` to read all lines into the array directly. It takes care of `\r`, `\r\n` and `\n` line endings.

**Comment by Ohda** [comment]
Thanks !

**Comment by svmnotn** [comment]
@Ohda are characters able to do jobs after this for you? Because they are just siting there when I use your pr.

**Comment by svmnotn** [comment]
Never mind that, it now \/
alt text

**Comment by vogonistic** [comment]
Excellent! Merged! (I'm on a Mac)

**Pull request merged**
