### PR TITLE
Made PendingJob selectable.

### PR DESCRIPTION
**Pull request by herrflockig**

### CODE REVIEW

**Comment by svmnotn** [comment]
alt text

Also, I <3 this change!

**Comment by vogonistic** [comment]
This PR has merge conflicts, please fix them and then remove `[conflict]` from the title. Thanks!

**Comment by Mizipzor** [comment]
Something went very wrong here. 332 changes files is not expected. :)

**Comment by herrflockig** [comment]
Yeah, I'll retry.

**Comment by herrflockig** [comment]
This one got borked... head over to #963 to get the new one

**Comment by TomMalbran** [comment]
@herrflockig Close this PR please, since it is not required anymore.

**Pull request closed without merging**
