### PR TITLE
adds License Headers to Other scripts that were missing them

### PR DESCRIPTION
**Pull request by zwrawr**

### CODE REVIEW

**Comment by Mizipzor** [comment]
I just realized we are wrapping the headers in a `#region`. Why? The convention is that the license starts on the very first line. If collapsing is what you want any decent editor can do that on comment blocks anyway. Oh well, not important. It bugs me but I can live with it.

**Comment by WardBenjamin** [comment]
Looks good, thanks!

**Comment by zwrawr** [comment]
@Mizipzor no idea why that is the pattern but that is what all the other headers are like so these should be consistant

**Comment by Mizipzor** [comment]
@zwrawr you are absolutely correct, consistency trumps good.

**Pull request merged**
