### PR TITLE
Feature/better trade ui

### PR DESCRIPTION
**Pull request by sboigelot**
Very small PR to align the trade interface in a grid and make it readable

image

### CODE REVIEW

**Comment by sboigelot** [comment]
Hem @vogonistic I still can't get a clean state of my branches.

I tried fast forwarding with

```
git checkout master
git pull --ff-only upstream master
git push 
```

I also tried a hard reset:

 ```
git fetch upstream
 git reset --hard upstream/master
```

But I still have a million on merge on my PR. Any idea how to fix this?

**Comment by vogonistic** [comment]
For one particular PR, what you can do is check out the PR branch and rebase it on top of upstream master.

`git rebase upstream/master`

If you run into problems and can't solve the merge issues, you can always do `git rebase --abort` to return to before you started the rebase. `git status` contains the relevant commands while in a rebase or merge.

Now, assuming that the rebase worked, you need to push it to your fork, which will complain because it already exists, but you can do a force push by adding the `-f` flag and it'll be ok.

**Comment by vogonistic** [comment]
When you create a new branch (lets call it `vogon`), do it like this: `git checkout -b vogon upstream/master`

That way, it'll be created at the same place that `upstream/master` is.

**Comment by sboigelot** [comment]
@vogonistic thanks a lot for all the info

I tried the rebase on this PR, I don't think it changed anything. Here is my bash for reference
There was no merge issue

```
sboig@DESKTOP-S99267F MINGW32 /d/git/ProjectPorcupine (feature/BetterTradeUI)
$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: Auto font license edition
Using index info to reconstruct a base tree...
M       Assets/Resources/Fonts/Cubellan_v_0_7/Cubellan_License_SIL_OFL.txt
M       Assets/Resources/Fonts/Cubellan_v_0_7/Read_Me.txt
M       Assets/Resources/Fonts/osp.foundry.alfphabet/OFL-FAQ.txt
M       Assets/Resources/Fonts/tgl/OFL-FAQ.txt
M       Assets/Resources/Fonts/tgl/Open Font License.txt
.git/rebase-apply/patch:121: trailing whitespace.
fonts, including any derivative works, can be bundled, embedded,
.git/rebase-apply/patch:237: trailing whitespace.
        "Cubellan", "Cubellan Bold", "Cubellan Italic"
.git/rebase-apply/patch:238: trailing whitespace.
        and "Cubellan Small Caps"
.git/rebase-apply/patch:239: trailing whitespace.
        Are currently in early beta stage.
.git/rebase-apply/patch:242: trailing whitespace.
        What comes to shape and spacing, there are few obvious
warning: squelched 23 whitespace errors
warning: 28 lines add whitespace errors.
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: Gridify the trade panel

sboig@DESKTOP-S99267F MINGW32 /d/git/ProjectPorcupine (feature/BetterTradeUI)
$ git push -f
Everything up-to-date

```

I always branch from my own master, that must be the issue. For my next PR I will branch from the upstream/master and see the result.

**Comment by vogonistic** [comment]
Please never, never, never ever work from your master. It leads to all kinds of complicated configurations. If you want to, I can teach you how to create a new branch right before to create a PR if you really, really want to work from your master.

**Comment by sboigelot** [comment]
> Please never, never, never ever work from your master. It leads to all kinds of complicated configurations. If you want to, I can teach you how to create a new branch right before to create a PR if you really, really want to work from your master.

yep I understand now the issue I keep having. I will close this PR and re-create a branch from the upstream/master with the 2 file change. Let's see if it improve.

I don't really want to work from my master, I just want to have clean PR :)

**Comment by sboigelot** [comment]
@vogonistic Yes that was the solution, I was always branching from my fork master and not from the upstream/master. Now my PR will be much cleaner : #1069

Thanks again for the help!

**Pull request closed without merging**
