### PR TITLE
Moved non-Controller files into Models

### PR DESCRIPTION
**Pull request by TomMalbran**
PR #1353 organized the Controllers folder, but in Controller we had several classes that were not Controllers. This PR moves them to the Models folder. And yes, the Models folder is really big, but that is because our Models are also Services and Repositories, and we should probably split the Models folder in those groups. For now, the Controller folder only contains Controllers.

Also, I think that we shouldn't have spaces in in file/directory names since it makes it use quotes in the console and can be an issue for contributors that don't know it.

### CODE REVIEW

**Comment by kd7uiy** [comment]
As long as you didn't move anything to the root /Models folder, I'm okay with that;-)

I'm not sure if Camera, SpriteManager, KeyboardManager, and maybe even Settings belong in the Model folder.

**Comment by TomMalbran** [comment]
CameraData is fine in Model since it holds the Camera Data. But I agree with all the others. The issue is that they also didn't belong where they were before. They should be in Services, as long as many of the other managers, but we don't have that yet. There hasn't been much discussion in #1140. I have a branch which moves some of the files, but haven't made a PR yet.

**Comment by kd7uiy** [comment]
Okay, I didn't really look at the CameraData, I see what you mean.

**Comment by mikejbrown** [comment]
:+1:

**Pull request merged**
