### PR TITLE
Fix for [BUG] KeyNotFoundException in Parameter.cs

### LINKED ISSUE #725: [BUG] KeyNotFoundException in Parameter.cs
Getting this whenever building the metal smelter:

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2<string, Parameter>.get_Item (string) <0x00341>
Parameter.get_Item (string) (at Assets/Scripts/Models/Parameter.cs:62)
(wrapper dynamic-method) System.Runtime.CompilerServices.ExecutionScope.lambda_method (System.Runtime.CompilerServices.ExecutionScope,object,object[]) <IL 0x00020, 0x000ed>
MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) <IL 0x00049, 0x00231>
MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor.PerformOverloadedCall (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) <IL 0x00050, 0x0028e>
MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor/<>c__DisplayClass33_0.<GetCallback>b__0 (MoonSharp.Interpreter.ScriptExecutionContext,MoonSharp.Interpreter.CallbackArguments) <IL 0x00014, 0x00075>
MoonSharp.Interpreter.Interop.BasicDescriptors.DispatchingUserDataDescriptor.ExecuteIndexer (MoonSharp.Interpreter.Interop.BasicDescriptors.IMemberDescriptor,MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue) <IL 0x000aa, 0x006c2>
MoonSharp.Interpreter.Interop.BasicDescriptors.DispatchingUserDataDescriptor.Index (MoonSharp.Interpreter.Script,object,MoonSharp.Interpreter.DynValue,bool) <IL 0x00024, 0x0013f>
MoonSharp.Interpreter.Execution.VM.Processor.ExecIndex (MoonSharp.Interpreter.Execution.VM.Instruction,int) <IL 0x000f9, 0x007a1>
MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop (int) <IL 0x00572, 0x01d21>
MoonSharp.Interpreter.Execution.VM.Processor.Call (MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue[]) <IL 0x00077, 0x00388>
MoonSharp.Interpreter.Script.Call (MoonSharp.Interpreter.DynValue,MoonSharp.Interpreter.DynValue[]) <IL 0x000a4, 0x00594>
MoonSharp.Interpreter.Script.Call (MoonSharp.Interpreter.DynValue,object[]) <IL 0x00026, 0x001af>
MoonSharp.Interpreter.Script.Call (object,object[]) <IL 0x00009, 0x0008c>
FurnitureActions.CallFunctionsWithFurniture (string[],Furniture,single) (at Assets/Scripts/Models/FurnitureActions.cs:61)
Furniture.Update (single) (at Assets/Scripts/Models/Furniture.cs:110)
World.Update (single) (at Assets/Scripts/Models/World.cs:230)
WorldController.Update () (at Assets/Scripts/Controllers/WorldController.cs:127)
```

Refers to the return line here:

```
    // Iterator to simplify usage, this works properly in Lua
    public Parameter this[string key]
    {
        get
        {
            return contents[key];
        }
```
Should there be a default value here?

### PR DESCRIPTION
**Pull request by mikejbrown**
Fixes #725 
Related #740 #743 

Would be better to get a Lua line number. Is that possible at all?

### CODE REVIEW

**Comment by koosemose** [comment]
Nice and simple. I'll probably be looking into having a flag of some sort set on a Parameter when it is created this way, to allow the caller to request a specific default value. But this will at least prevent the current issues, with the side effect of providing default values of 0.

**Comment by mikejbrown** [comment]
@koosemose if you want to PR on top of my PR so as to keep it all together I'd be fine with that :smile:

**Comment by koosemose** [comment]
I'll be honest, I'm still very much a Git newb, and have no idea how to do that, I've got standard PRs to a repo, and conflict resolution down, and that's about it.

**Comment by mikejbrown** [comment]
I've never done it myself before (that's what all the testing up there ^^^ is about). Here's the workflow.

The great thing about git is a branch is a branch is a branch. Names like "master" are only special because of convention... there is nothing special about them under the hood. The same applies for Github pull requests which are essentially nothing but branches. In particular this PR automatically tracks a branch in my fork mikejbrown/ProjectPorcupine/fix-725-.... If you want to collaborate on a PR you can just collaborate using forks & PRs as you normally would, only targeting the branch behind the PR instead of TeamPorcupine/ProjectPorcupine/master as you normally would. There is a handy shortcut to make this easier.

Assuming you have _your_ fork set up as `origin` and TeamPorcupine/ProjectPorcupine set up as `upstream` (as suggested by quill18), if you run

```
git fetch upstream pull/746/head:local-branch-name
```
that will fetch the PR branch into a _local_ branch (on your computer) called local-branch-name (it can be whatever you want). (You can change the number 746 -> any other pull request to work on any one you want. You can get the complete list by running `git ls-remote upstream`.) Now check it out like any other branch:

```
git checkout local-branch-name
```

Now that you have the PR as a local branch you can make any changes you want to it, test it, and commit it. Then you can push it to _your_ fork of the project with
```
git push --set-upstream origin local-branch-name
```
which will create a copy under a branch named `local-branch-name` on your fork.

Now if you go to your fork on Github and make a PR as usual, you need to tell Github to base the PR on _my_ fork. So set the base fork to mikejbrown/ProjectPorcupine and set the base branch to fix-725-.... Set the head fork to your repo (should be the default) and the head branch to whatever you named your branch. If all these options aren't showing up click "If you need to, you can also compare across forks." Now create the PR.

All this does is create a new PR on _my_ fork, affecting the branch that Github recognizes contains the changes for _this_ PR. When I merge it in the changes get merged here and become part of the PR. This is how a group of people can all make commits to a single PR.

Wheew... that was fun to figure out. Hope it helps!

**Comment by mikejbrown** [comment]
Added a section on that workflow on the wiki https://github.com/TeamPorcupine/ProjectPorcupine/wiki/Working-with-Someone-Else's-Pull-Request

**Comment by koosemose** [comment]
Very nice, and nicely written as well, thank you.

It occurs to me, with how it is now, it is creating a new Parameter and not storing it, meaning if they expect to set it, they're going to be setting a brand new one every time, that may lead to unexpected behavior. Should we go ahead and go all the way and have lazy creation (go ahead and add the new Parameter to contents) so it behaves how they most likely expect it?

**Comment by mikejbrown** [comment]
@koosemose Thanks :smile:. And good catch... probably should do that. The tricky bit might be determining whether the new value should be a single parameter or group parameter?

**Comment by koosemose** [comment]
Not really, just stuff the valueless parameter into contents, it will have empty string value, and return 0 from ToFloat, and the new ToFloat that lets you set a default will return that default instead. As soon as someone attempts to access a key in the new Parameter, it will again create a new parameter and stick it in there. And if someone sets a value it will no longer return default values...

and I just realized how I have it set up combined with your code, it means by default the lazy creation will always have contents... and others won't and will likely throw an error if someone tries to access contents on one that doesn't have it.... I need something a little more stout

**Comment by koosemose** [comment]
It should work if HasContents is changed to return true if contents.Count > 0. Then we always create contents... I think that will do it.

**Comment by mikejbrown** [comment]
That seems to fix #725 now. Probably fixes #740 and #743 as well. Anyone care to vouch that everything is working? :smile_cat:

**Comment by mikejbrown** [comment]
PR #773 adds unit tests for Parameters. It was necessary to make some changes to Parameters to get the tests to pass. Don't know if these will conflict with your changes here, @koosemose, but some tests will have to be changed if lazy evaluation is merged in anyway so we can deal with both sets of changes together if/when it comes. Any thoughts on the tests so far?

**Comment by mikejbrown** [comment]
The fixes to `WriteXmlParamGroup` from #773 don't conflict with this so I just went ahead and applied them here. Probably able to remove the [WIP] tag :question:

**Comment by koosemose** [comment]
All my tests have went well for the new system, seems at a good point for a Gatekeeper to check it out.

**Comment by vogonistic** [comment]
@mikejbrown Testing it by building a Mining Drone and a Smelter, I get a spam of this error:

```
ScriptRuntimeException: cannot access field SetParameter of userdata<Furniture>
MoonSharp.Interpreter.Execution.VM.Processor.ExecIndex (MoonSharp.Interpreter.Execution.VM.Instruction i, Int32 instructionPtr)
MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop (Int32 instructionPtr)
```

Can you take a look and see what's going on?

**Comment by vogonistic** [comment]
After merging a bunch of other PR's I can't reproduce this anymore. Merging.

**Pull request merged**
