### PR TITLE
Prototype Manager Update

### PR DESCRIPTION
**Pull request by TomMalbran**
I moved the load functions outside of the constructor. All the prototypes are loaded by the ModsManager, since that is how it will work in the near future. This makes it possible to test with the PrototypeManager, since you can create an instance and then load the prototypes you want manually.

I also changed some of the function names to make them shorter.

### CODE REVIEW

**Comment by TomMalbran** [comment]
The 3 unit test failing are from the Scheduler, because the Prototypes are now empty, but I believe that those should be fixed in #1132. But at the same time this change should make fixing them in #1132 a lot easier.

**Comment by mikejbrown** [comment]
Gatekeepers: If you prefer to go this route you could close #1132 (as this makes that one largely irrelevant) and we'll make the needed fixes here so we have one working PR instead of two broken ones.

**Comment by TomMalbran** [comment]
@mikejbrown I can also make a pr to your code changing only the loading and keep this one with just the functions names. And you could then fix the tests. Or you can just copy the loading fix and I can remove it from this pr.

**Comment by mikejbrown** [comment]
I think we should close #1132 and get the tests working on this.

**Comment by mikejbrown** [comment]
https://github.com/TomMalbran/ProjectPorcupine/pull/1 addresses the unit tests

**Comment by kd7uiy** [comment]
Okay, so this failed the CI tests. I'm not understanding why it failed, perhaps someone could illuminate me on that?

**Comment by mikejbrown** [comment]
@kd7uiy This breaks the `SchedulerEditorTest`s because they use the `PrototypeManager`. I have a PR on this https://github.com/TomMalbran/ProjectPorcupine/pull/1 that should fix the issue. @TomMalbran just needs to merge it in.

**Comment by bjubes** [comment]
@kd7uiy  when my pr #1151 is merged it will say at the bottom of the Travis log exactly which unit test failed. for now you can expand the XML file travis logs and find it manually.

**Comment by mikejbrown** [comment]
This has merge conflicts now.

**Comment by TomMalbran** [comment]
Fixing them right now.

@mikejbrown The test fix is way better now, the code looks much cleaner. Soon we will be able to do the same with the Lua functions.

**Comment by TomMalbran** [comment]
Conflicts resolved. Waiting on Travis now.

**Comment by mikejbrown** [comment]
Works for me. Happy to merge as soon as Travis passes.

**Comment by TomMalbran** [comment]
All Travis checks passed.

**Comment by mikejbrown** [comment]
Merged!

**Pull request merged**
