### PR TITLE
Added job description and show it in selected tooltip

### PR DESCRIPTION
**Pull request by jdlaroche**
I added a description to each job that is created in the c# code and in the lua files. I also added a job description field in the selectable interface and I query it for the character.

I think the whole selectable tooltip should be reworked because the current design is not ideal, but this new feature is aligned with the current design and should be alright until we have a discussion about the future of this tooltip.

### CODE REVIEW

**Comment by jdlaroche** [comment]
This is allowing us to see what a character is doing, which makes debugging a lot easier and is also something that the user will want to see!

**Comment by jdlaroche** [comment]
I see that there is now a conflict :( i'll look at it tonight if possible

**Comment by jdlaroche** [comment]
I fixed the conflict. Can now be merged

**Comment by svmnotn** [comment]
@jdlaroche currently a job can't be selected, at least until #705 is merged. Therefore this can't be tested in game.

**Comment by jdlaroche** [comment]
it is showing the job description of the job owned by a character in the selection tooltip when you select a character. it is testable in game and works


Sent from my Bell Samsung device over Canada's largest network.<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: "Victor M. Suarez" <notifications@github.com> </div><div>Date: 2016-08-23  9:06 PM  (GMT-05:00) </div><div>To: TeamPorcupine/ProjectPorcupine <ProjectPorcupine@noreply.github.com> </div><div>Cc: Jean-Dominic Laroche <galdo_12@hotmail.com>, Mention <mention@noreply.github.com> </div><div>Subject: Re: [TeamPorcupine/ProjectPorcupine] Added job description and show it in selected tooltip (#656) </div><div>
</div>
@jdlaroche currently a job can't be selected, at least until #705 is merged. Therefore this can't be tested in game.

**Comment by svmnotn** [comment]
@jdlaroche when one selects the character right now it just shows all the names in the .txt file so it is not possible to test it without altering that file.

**Comment by svmnotn** [comment]
However once the file is altered (which hopefully won't be needed after #687) it \/
alt text

**Comment by jdlaroche** [comment]
svmnotn... did you try it? I made it so I know what it does... It is kind of related to #705 as both are representing the job with a different implementation, but it is working without 705

image

**Comment by svmnotn** [comment]
@jdlaroche I think you may have missed my latest comment. Also I don't think they do quite the same thing, in fact I would much like for both to be merged as #705 tells the user what the Job is missing, whilst this one tells the user what the character is doing.

**Comment by jdlaroche** [comment]
@svmnotn  sorry if I looked rude. I just want to highlight the fact that this PR can be merged and add a functionality without #705 or #687. I just pulled the latest version and tested it :)

**Comment by svmnotn** [comment]
@jdlaroche no problem, but I am wondering how you got the characters to not display every name in the list... (Maybe it is just because I am in linux so the line endings may not match.)

**Comment by jdlaroche** [comment]
This is probably it :) It works well here (win 10) as you can see on the screenshot

**Comment by vogonistic** [comment]
@jdlaroche You should open an issue and discuss how to do the tooltips. Any and all ideas are welcome!

Merged!

**Pull request merged**
