### PR TITLE
Adapt the look of the Settings menu

### PR DESCRIPTION
**Pull request by sboigelot**
image

New updated version

image

### CODE REVIEW

**Comment by alexfriesen** [comment]
hey nice! I wanted to do the same :)
maybe you can add some space to the corners, it looks a little bit squashed.

**Comment by TomMalbran** [comment]
It needs more space between the content and the border.
The Settings title is a bit to high, should look closer to the options dialog.
The buttons are missing the bottom border or something. Is hard to distinguish them from the background.

Other than that it looks great.

@alexfriesen Maybe you can later replace the dropbox, checkboxes and slider?

**Comment by Tranberry** [comment]
I wish this was not made in unity, but it is a good step in the right direction :+1:

**Comment by Ohda** [comment]
If you rework on it you can try :
- set the same font size on all labels (Arial 14 ? use the one on save/cancel button)
- Right align on all labels. (The double dots at the end should be on the same x position.)

**Comment by sboigelot** [comment]
I'll be working on it later taking all your suggestion into account.

**Comment by sboigelot** [comment]
Advice applied :)

**Comment by TomMalbran** [comment]
The new version looks much better. I approve it.

**Comment by sboigelot** [comment]
@TomMalbran you are right it should be 19 font size, updated

**Comment by TomMalbran** [comment]
@sboigelot It should no longer be [WIP] since it looks done.

**Comment by sboigelot** [comment]
@TomMalbran oups :)

**Pull request merged**
