### PR TITLE
Main Menu Button

### PR DESCRIPTION
**Pull request by Ohda**
- Add a new menu when you clic on Quit. So you can quit to main menu.

### CODE REVIEW

**Comment by bjubes** [comment]
can you upload a picture?

**Comment by koosemose** [comment]
Perhaps it's just me, but I think just having a Quit To Desktop and Quit To Main Menu button on the options menu, rather than having to use click on a separate dialog after choosing quit

**Comment by Ohda** [comment]
I can do that if you want, but it was feeling good to me to replace the "are you sure you want to quit panel" by this.

**Comment by BraedonWooding** [comment]
I actually quite like this window its a better alternative then the are you sure window.

**Comment by dusho** [comment]
ye.. if there are more than 2 options, it shouldn't use OK/Cancel layout maybe..
maybe just having:
**Resume
Main Menu
Quit Game**
vertically would be better?

**Comment by Ohda** [comment]
I will try something like that tonight.

**Comment by Ohda** [comment]
Update the original post

**Comment by ComputerOverlord** [comment]
Why are you yelling at yourself to update it?

**Comment by koosemose** [comment]
Looks good, stylecop clean, and everything seems to work as expected. Merged.

**Pull request merged**
