### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by Aiwha**
Added French.

### CODE REVIEW

**Comment by Aiwha** [comment]
I fell like I fucked up something. Only wanted to change fr_FR.lang.
And I realised I didn't add the power generator translation. Is there a way to un-request the pull request?

**Comment by Tranberry** [comment]
Why are the font licenses changed? /sorry for n00b question

**Comment by NogginBops** [comment]
@Aiwha You could close your current request and open a new one.

**Comment by emilkris33** [comment]
@Aiwha You need to open up unity with your translation added so it can generate .meta files. Else everybody that gets your code will generate .meta files and we will have conflicts:

**Comment by Aiwha** [comment]
@NogginBops Thanks!
@Tranberry Well… no idea.
@emilkris33 Thanks! I have not Unity. I think I'll wait until a solution is found in #153, that'll be easier.

**Pull request closed without merging**
