### PR TITLE
[StyleCop warnings][Conflicts] Added WorldFactory, creates Worlds in code.

### LINKED ISSUE #828: Create a world through code
Right now some of our code makes difficult assumptions. Like that there ever would be only one world which will be created once and live until the game shut down. It also relies on the scene being set up with some game objects and controllers already in place.

I think this needs to change for several reasons. I'm gonna pick up #459 and to do that I need to solve this first. Any help appreciated.

### PR DESCRIPTION
**Pull request by Mizipzor**
Very useful for tests.
Arguably how it should be handled in the main scene as well. 
There is however not yet a clean way to destroy a world.

Added a `Tests` folder. The scene is supposed to be as empty as possible. I allowed `Main Camera`, `EventSystem` and `Canvas` as they are not made by us. Other than that there a single `GameObject` with a `WorldFactoryBehaviour` which wraps `WorldFactory`.

There are some things i havent solved yet, like how to give a behavior a certain prefab.

Next step is to cleanly take down a world, which should result in the same empty scene.

Fixes #828.

### CODE REVIEW

**Comment by relinu** [comment]
#834 adds removeAll to SpriteControllers which lets you delete the sprites

**Comment by Mizipzor** [comment]
@relinu Awesome, thanks.

**Comment by Sommerbo** [comment]
@Mizipzor Consider using UberLogger instead of unity's log. And class name "WorldFactory" is epic!

**Comment by Mizipzor** [comment]
@Sommerbo Doesnt UberLogger hook into and replace the regular log calls? Or have I already forgotten how it works?

**Comment by Sommerbo** [comment]
@Mizipzor No you must use `Debug.ULog` or `Debug.ULogChannel`, itis  better that way since UberLogger truncates multiline log messages.
UberLogger also passes all log messages to Unity console so you can choose several ways to view messages. Personally I like UberLoggers channel system, makes it easy to concentrate on one issue

**Comment by Mizipzor** [comment]
I stand corrected. :)

**Comment by vogonistic** [comment]
You have StyleCop errors, can be merged when those are fixed.

**Comment by bjubes** [comment]
@vogonistic I checked this PR out, for me it doesn't have any violations even after merging in master....?

**Comment by vogonistic** [comment]
@bjubes Really? Unless we've changed the rules the last 3 days I think you need to check your StyleCop setup. I get these StyleCop warnings:

WorldFactory.cs:1 Missing header
WorldFactory.cs:2 System using directives before other using directives
WorldFactoryBehavior.cs:1 Missing header
WorldFactoryBehavior.cs:9 Method must have access modifier

**Comment by svmnotn** [comment]
can confirm the StyleCop issues that @vogonistic pointed out, @Mizipzor please fix :)

**Comment by Mizipzor** [comment]
I struggle to find time for this project. What do you think of this? Should I continue on it or merge as it is (after fixed conflicts)? Or let someone else pick it up?

**Comment by sboigelot** [comment]
I'm sorry but I don't see much in this PR for now. It's not link to anything else in the code and doesn't do much. If you don't have time, I think it will be better to close it. When someone else will be able to tackle the issue, that person will be more free in his/her implementation.

So it's up to you: if you have time to continue, let us know, if not, close it ;)

**Comment by kd7uiy** [comment]
I'm not quite sure what this is actually supposed to do either. I like the idea of having a test scene, but I don't think this quite does the trick...

**Comment by TomMalbran** [comment]
I don't even think that this is the best solution for #828. Instead of creating world controllers, we should create Worlds, and have a WorldManager that manages them. We should then change all the Controllers to be able to work when we switch from one world to another. Everything in a controller that keeps state of something specific to the current world should be moved to another class that is part of the world manager.

**Comment by sboigelot** [comment]
this is a very old PR with no update and the author doesn't have time for now, I'm closing it for now. Feel free to re-create it if you update it!

**Pull request closed without merging**
