### PR TITLE
Fix for Metal Smelter and Cloning Pod (also code clean up)

### PR DESCRIPTION
**Pull request by Randshot**
I mainly fixed the metal smelter.
While I was at it, I also reformatted the whole file to make it readable.

### CODE REVIEW

**Comment by svmnotn** [comment]
Maybe split all the formatting to a different pr?

**Comment by abackwood** [comment]
What did you change about the smelter? Between the style fixing I can't really tell

**Comment by vogonistic** [comment]
@abackwood Pro-tip, add `?w=1` to the changes url and it won't show whitespace changes

**Comment by vogonistic** [comment]
That said, @Randshot you should describe what was wrong with the smelter and what you did to fix it.

**Comment by svmnotn** [comment]
I've been trying to figure it out... but... I can't reliably test due to characters just not working.

**Comment by abackwood** [comment]
Seems to work okay (apart from bug #699), but until I know what it's meant to do, I can't really say much about it

**Comment by vogonistic** [comment]
When you've fixed the conflicts and described it better, remove `[conflict]` from the title. Thanks!

**Comment by Randshot** [comment]
I was in a bit of a hurry while creating the PR, so I couldn't describe what I changed.

I didn't like the 'ugly hack' that someone created, which involved setting a new parameter 'smelting' to check whether the metal smelter was working or not.
The problem with this approach is however, that the metal smelter will only start working, when an inventory of Raw Iron with a stack size of 50 is placed on the spawn spot.
I don't think however that that was how it was meant to work.
I also added the callback to MetalSmelter_Worked again, which someone had removed for no to me apparent reason.

**Comment by abackwood** [comment]
I thought the smelting was more responsive. Like I said, it all works.

Backwood seal of approval :)

**Comment by Randshot** [comment]
So, it now works like a charm for me.
I added that the metal smelter only starts smelting if there is at least an inventory with a stack size of 5, else it would also start smelting, even if there was only one raw iron.
This was no problem before, because it would only start once the job was completed which means when the 50 raw irons were delivered.

**Comment by Randshot** [comment]
While I was testing this PR, I noticed that the cloning pod didn't work.
The problem was with the job creation which didn't match any Constructor.
I thought I would add this in this PR.

**Comment by Randshot** [comment]
I know that I shouldn't change so many things in one PR but I have modified almost the whole file anyway, so I decided to declare variables as local, if they aren't needed outside of it's context.
Just as side note, variables in Lua are by default global (public) when declared and if you want them to be only accessible in the current context, you have to do so manually by making them local (private).
I personally think that using local variables is much cleaner and less prone to weird bugs, than having all of them global. We do it in C#, so why not in Lua?

**Comment by Randshot** [comment]
I decided to cancel the metal smelter job in the job worked callback and then recreate it with altered desired (stack size) inventory.
I also noticed that the job completed callback doesn't seem to be called reliably. Haven't looked into this though.

**Comment by Randshot** [comment]
Everything should be working.
It's bit annoying to resolve all these conflicts though.
But that's part of contributing, I guess :)

**Comment by vogonistic** [comment]
I'm reviewing it for merge right now so hopefully it'll work fine. I understand the pains of keeping them up to date, but that's because we are changing the engine all the time. When we get to the point where we just change resources and tweak game behavior, it'll be much less merge conflicts.

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
