### PR TITLE
Code Driven UI - Please Commit

### PR DESCRIPTION
**Pull request by dustinwloring1988**
I had to combined the trading scene into the code driven scene so that nothing would break as were making the UI code driven. 

Setting and Options are now Dialog Boxes.

Made a Dialog Manager to find Dialog Boxes more easily.

Modified code so that OnEnable will add listeners instead of doing this in the inspector.

Changed some comments I did so there is a space after the //.

Fixed some (a lot) of spelling - sorry spell is not my strong suit.

Deleted SettingHelper and added the code in DialogBoxSettings.

Changed RootMenuController.cs back to MenuController.cs

**********************************************************************************************
Here is a start of what I hope will be a fully code driven UI. 
As of this pull request all is working just like before but more is done by code then by linking in the inspector.
I have a couple of busy days ahead of me at work so I wanted to post this now so other can add to it.

### CODE REVIEW

**Comment by bjubes** [comment]
why exactly did you change MenuController.cs to RootMenuController.cs? I think being a controller implies it is the root of the menus and this will break a few PR in the process.

**Comment by Randshot** [comment]
@dustinwloring1988 Please try to accommodate our conventions.
For example for comments. All comments have to start with a capital character and there also has to be one space before the comment message.
Comments should also end with a period.

**Comment by vogonistic** [comment]
@dustinwloring1988 Looking at the commit, the use of whitespace and opening brace position seems to be all over the place. Can you correct it with converting tabs to 4 spaces. Ideally, run StyleCop and fix the issues that shows up. You only have to fix the issues that are on the rows that you've worked on. 

Take a quick look at the style examples in [CONTRIBUTING.md](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/CONTRIBUTING.md#style-guidelines)

**Comment by dustinwloring1988** [comment]
yes I read the readme and set mono like it says. So the last couple scripts should have been fine. Can you commit it then I will delete the fork and re fork this project then fix everything.
Thanks

**Comment by Randshot** [comment]
@dustinwloring1988 Hey, just did all the formatting. You can look it up [here](https://github.com/Randshot/ProjectPorcupine/tree/pulls/472)

**Comment by Randshot** [comment]
Just try to merge it into your branche.

**Comment by dustinwloring1988** [comment]
@Randshot Thanks I was doing the same. I think I just had to select all and format from in mono since I changed the settings half way though.
If this is not good enough for them to commit this time im done with this. This should be a fun project not a stressful one.

**Comment by Randshot** [comment]
@dustinwloring1988 I already run mine through StyleCorp. But let's wait and see :)

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
