### PR TITLE
New-UI

### PR DESCRIPTION
**Pull request by dustinwloring1988**
Sorry had to delete the other one I did as my git desktop was acting up. Cant wait to contribute more.....

**Commit Goal**
Here is a new UI for the project. 

**Next**
Would be to make this all code driven and add settings functionality to it.

**Pro**
No scripts were modified.
UI now take up less room when not selecting something to build

**Con**
Changed SCENE file
Still not code driven

**Screenshots Below**

### CODE REVIEW

**Comment by Grenkin1988** [comment]
Could we submenu build-furniture-....
Otherwise this leads to issue #364

**Comment by jamzam90** [comment]
Making it code driven shouldn't take much the scene has to be messed with if your working on ui anyways even if it's done through code. Also looks like we both tweaked ui things.

**Comment by WardBenjamin** [comment]
Submenuing furniture and such under the build menu would be good, but this looks good as-is. Good work!

**Comment by RodRitter** [comment]
After testing it, it seems there is something not right with regards to the localisation. If you sort that out I can merge.

image

**Comment by dustinwloring1988** [comment]
I have the build menu closing of escape being pressed but for the localization mine just stays in English not sure how it works is there a read me. Maybe some one could do the localization part after this is commited???
Also have the settings screen UI made not all the settings work yet...

**Comment by RodRitter** [comment]
It's still messed up on my end when I test it.

@vogonistic Can you confirm a test on your side to see if the localisation is messed up?

**Comment by dustinwloring1988** [comment]
I was a couple commits behind sorry I'm new to git hub... I will fix now

**Comment by Mizipzor** [comment]
@RodRitter Did I screw up my localization changes? I tested on latest master and I dont get those warnings. Or maybe its the other way around? This branch needs to merge those fixes from master?

**Comment by RodRitter** [comment]
@dustinwloring1988 added new UI elements to the scene. I don't think the text string are correct in the new elements.

**Comment by bjubes** [comment]
This looks great! My only suggestion is to put the save button in the settings dialog on the right, as that's usually where the "confirm" action is in most dialogs

**Comment by RodRitter** [comment]
I think the meta files are causing this conflict. Maybe pull down latest and see if those files sort the issue out.

**Comment by dustinwloring1988** [comment]
Fixed (i think). I will need translations for the other languages though

**Comment by RodRitter** [comment]
Perfect, works like a charm now. Good job

**Comment by ComputerOverlord** [comment]
Difference between settings and options?

**Comment by dustinwloring1988** [comment]
Settings where you can change your resolution and quality settings...
Options is where you have new world, save, quit..

**Pull request merged**
