### PR TITLE
English UK Localisation

### PR DESCRIPTION
**Pull request by nsfranklin**
English UK Localisation

### CODE REVIEW

**Comment by SanteriHetekivi** [comment]
Could you add translations to English UK for:
furn_power_generator=Power Generator
furn_power_generator_desc=Generates power out of nothing.

They are missing in current master, but pull request #169 should add them in.

**Comment by bjubes** [comment]
no, don't add anything for a pull request that hasn't been merged yet. These lines will be easy to add at a later date when #169 is merged, but until then all merge requests should exist in their own "sandbox" state where they only interact with the current master branch, not each other.

**Comment by nsfranklin** [comment]
Its become to messy and now I understand more about git.

**Comment by nsfranklin** [comment]
Its was redundant anyway there are no localisation differences at the moment. Those will come when people start adding colour alterations. Fun experiment!

**Pull request closed without merging**
