### PR TITLE
Console in game

### PR DESCRIPTION
**Pull request by kishtarn555**
This allow to do Lua instructions
Recive Text and show it in UI
But needs premade Lua Functions in Command.lua
And the information after try a Lua instruction is almost null

### CODE REVIEW

**Comment by ComputerOverlord** [comment]
Good idea! I wonder if Thequill will add this!

**Comment by quill18** [comment]
Please add more details about how this actually gets used in practice.

**Comment by kishtarn555** [comment]
It's an UI element and has attach a c# derivate from dialogbox.
There tree functions: Log, LogWarning and LogError.
They recive two objects as arguments:
 First is optional, its who is telling the message, and the second its the message. Both are printed by object.ToString().
The UI also has an InputField, when you press enter and finish the edit take his text and is interpreted 100% as Lua code. You can add premade Lua functions in Commands.lua

**Comment by kishtarn555** [comment]
image

**Comment by kishtarn555** [comment]
I moved the console to prefab because the merge problems

**Comment by svmnotn** [comment]
@kishtarn555 how would someone open/close(maybe not close as I do see the 'X') this? Is there a key binding? Like how paradox games have it in the ` key? or some in game button? does it just show up at the start and can't be opened afterwards?

**Comment by kishtarn555** [comment]
I dont have any open because I wanted to leave to the future because need more stuff like have a Developer mode.
But you can just add a button o key and write this line code
DevConsole.Instance.ShowDialog();

**Comment by kishtarn555** [comment]
I added a button to the Top Menu as temporal way to open it

**Comment by ComputerOverlord** [comment]
Not quite what I expected... well maybe sort of. You should add Commands or at least more commands.

**Comment by BeefEX** [comment]
@ComputerOverlord commands are defined in LUA, read please

**Comment by ComputerOverlord** [comment]
Maybe ~ should open console like in most games?

**Comment by Tranberry** [comment]
If tilde is added as the 'open console' key, will it be remapped to the key that is below (esc) on localized keyboards? On swedish keyboards (§) is the default console key (located below esc).

**Comment by ComputerOverlord** [comment]
@Tranberry I only half-understood that haha. I wonder how the keybind will be set up in the end..

**Comment by kishtarn555** [comment]
Well im not sure what to do...
Because if I add a key to openit This mean i would ad a Keyboard Controller And this part it's not about.
Like an temporally I will addit a father wich listen to a key

**Comment by ComputerOverlord** [comment]
@kishtarn555  yeah, It could be added later..

**Comment by Tranberry** [comment]
@ComputerOverlord 
delete

Do you get it now?

**Comment by ComputerOverlord** [comment]
@Tranberry haha. I was confused about the enter... I get it now...

**Comment by Mizipzor** [comment]
Off topic: You seem to merge a lot. Almost all the time. But thus far it looks like you never had to do it. You can probably save some time and effort. Like only merging after you create the pull request or push updates to it and Github says you have conflicts. What tool do you use btw? If I may ask. And is there a better place to discuss this rather than in this issue? :P

**Comment by kishtarn555** [comment]
I used F12 key

**Comment by kishtarn555** [comment]
Hey can someone tellme the correct translation for console and Type a command in Deustch 
I speak spanish and english

**Comment by RodRitter** [comment]
@kishtarn555 are the language updates necessary for this merge?

**Comment by Mizipzor** [comment]
I definitely think the localization changes should go in a separate pull request.

**Comment by vogonistic** [comment]
Please open a new PR where the merge errors are fixed and where we can use it to trigger lua. Please keep language updates separate.

**Pull request closed without merging**
