### PR TITLE
Moddable localization

### PR DESCRIPTION
**Pull request by vircung**
For every mod located in ```Data/Mods``` directory localization files will be loaded from ```Localization``` folder. Updates #528

### CODE REVIEW

**Comment by NogginBops** [comment]
I already did this in #541. I will fix whitespace there tomorrow.

**Comment by vogonistic** [comment]
When you've fixed the conflicts, remove `[conflict]` from the title. Thanks!

**Comment by vircung** [comment]
@vogonistic Conflict resolved
@NogginBops added folder Localization to match application directory structure

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
