### PR TITLE
Fixed sorting order for characters and carried inventory

### PR DESCRIPTION
**Pull request by dusho**
sorting order is now dependent on character Y position
before:
scr_sorting_before
after:
scr_sorting_after

### CODE REVIEW

**Comment by vogonistic** [comment]
This branch has merge conflicts. Please remove `[conflicts]` from the title when fixed.

**Comment by dusho** [comment]
merged

**Comment by mbstraus** [comment]
I checked this out for a bit, looking at different situations, and seems to be working as advertised.

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
