### PR TITLE
UI Bottom menu images

### PR DESCRIPTION
**Pull request by Ohda**
I have just replaced the images of the buttom menu with @alexfriesen's ones and switching the font color to white.

### CODE REVIEW

**Comment by TomMalbran** [comment]
This looks nice for now. But I think that later it will require a new design. @alexfriesen had one in the ui design post.

**Comment by sboigelot** [comment]
@TomMalbran agree, but this is ready. I'll always prioritize a ready PR to a possible future PR. There is too much PR being dropped by the original authors.

**Comment by TomMalbran** [comment]
I don't disagree with the merge. The UI looks much better. Just pointing out that this will not be the final design.

**Comment by sboigelot** [comment]
Sure, nothing is final :) never ^^

**Comment by Tranberry** [comment]
" I'll always prioritize a ready PR to a possible future PR. " This I agree with :+1:

**Pull request merged**
