### PR TITLE
[Ready] Animated character color change

### PR DESCRIPTION
**Pull request by Raketfart**
This PR depends on PR #669 and changes 3 colors in character sprite to use the random character color. The replaced colors are:
Color32(71, 86, 163, 255);
Color32(142, 154, 212, 255);
Color32(42, 56, 126, 255);

### CODE REVIEW

**Comment by Raketfart** [comment]
I'm not sure how I should do this untill PR #669 is merged. Most of these changes are the same, so no need to review these changes here also.

**Comment by Raketfart** [comment]
I stole the graphics from PR #684 to test it out. It's now the magenta colors that gets replaced instead of the blue.

It looks like this now.
animationcolors

Coloring the spritesheet takes a long time, so I need some sort of pre-rendering instead of doing it while the game is running.

**Comment by Raketfart** [comment]
Recoloring is now changed to using a shader to do color replacement. That means no lag, when spawning a new character.

**Comment by vogonistic** [comment]
How close is this to being finished?

**Comment by Raketfart** [comment]
It works right now - But the graphics needs a tweak, and I have to do some cleanup i think.
Probably today or tomorrow.

**Comment by Raketfart** [comment]
This should be ready to test and merge. I've removed the old character image files. I hope that's ok.
This PR depends on the shader from this project:
https://github.com/tutsplus/Dynamic-Sprite-Color-Swap-Shader

License is included in the shader folder

**Comment by quill18** [comment]
Looks so good.

**Pull request merged**
