### PR TITLE
Remove log spam

### PR DESCRIPTION
**Pull request by kd7uiy**
This log spam makes it quite difficult to build large stuff, noticeably slowing the game down. I suggest we comment it out for now, and when we have a new debug system as we are discussing, we can appropriately manage it there.

### CODE REVIEW

**Comment by WardBenjamin** [comment]
@kd7uiy This PR includes a bunch of extraneous commits, including a bunch of the "cursor circle" stuff. Also, this was addressed in #247 and #255.

**Comment by kd7uiy** [comment]
That's because I screwed up my first submission... Sigh. Will work on improving this commit, hang on.

**Comment by bjubes** [comment]
To me this change looks clean. One file changed, four add/del

**Comment by WardBenjamin** [comment]
@bjubes 
capture

**Comment by kd7uiy** [comment]
It was a mess, there's already at least one, maybe 2, pull requests that do something very similar, and I'm just going to drop it. Still, I do have my next commit in the queue:-)

**Comment by bjubes** [comment]
No I know the commit history is a mess, but the "changes" are clean and the commits get squashed anyway when PR Is accepted

**Pull request closed without merging**
