### PR TITLE
Added framework so that the mining drone can mine other things ...

### PR DESCRIPTION
**Pull request by alexisfcote**
than raw Iron.
Waiting for raw copper first  #575 and right click context menu to be able to select #514.
Also waiting for naming convention #505

### CODE REVIEW

**Comment by vogonistic** [comment]
Updated your title to say `[WIP]` which is short for Work in progress. Remove it when you want us to take a look at it.

**Comment by alexisfcote** [comment]
waiting for #658 to get merged

**Comment by TomMalbran** [comment]
Right now if you set both params to 1, the mining drone would want to mine both items, which would cause issues, since it won't be able to place the second item.

If the idea is to mine one or the other, and use a context menu to select which item to mine, it would be better to have one parameter ```<Param name="Output" value="Raw Iron" />"``` and then you can create the items with ```World.current.inventoryManager.PlaceInventory( j.furniture.GetSpawnSpotTile(), Inventory.__new(j.furniture.GetParameter("Output"), 50, 20) )```

**Comment by alexisfcote** [comment]
I did it like that because param value could only be a float.

**Comment by TomMalbran** [comment]
Right, I totally forgot about that. Once #675 gets merged, we can fix that.

**Comment by alexisfcote** [comment]
It works now, just right the mining drone to change the mined ressource. There should be no conflicts if you change type while it is worked

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
