### PR TITLE
[small] Moved the interfaces to a new folder

### PR DESCRIPTION
**Pull request by TomMalbran**
For a better file organization and a place to hold more interfaces in the future.

### CODE REVIEW

**Comment by Grenkin1988** [comment]
I've never had separate folder/namespace for Interfaces. That's a little bit strange

**Comment by TomMalbran** [comment]
I haven't worked mucho with interfaces. I just figure it would make sense. But if it doesn't is ok. We can just close this PR.

**Comment by Grenkin1988** [comment]
@TomMalbran I wouldn't do that. But other GateKeeper could have another opinion

**Comment by sboigelot** [comment]
I wouldn't do that either.

**Comment by dusho** [comment]
it usually makes sense to move interfaces to different namespace (even to separate assembly) if you're providing API to some outside world.. but in this project it really doesn't make sense to have separate namespace

**Comment by sboigelot** [comment]
Closing this issue then as we seem to agree.

**Pull request closed without merging**
