### PR TITLE
New character sprite + Expanded Character Sprite Color Replacement Range

### PR DESCRIPTION
**Pull request by koosemose**
image

New properly 64 ppu Character sprite. Sprite is a collaborative effort between myself and @Tranberry .

Additionally to get reasonable looking character sprite at true 64 ppu (rather than the 32 or so ppu sprite that was blown up to 70) a slightly larger range of colors was required, so Character Sprite Controller has 2 more uniform colors (total of 5, from very light to very dark) 2 more stripe colors (again for a total of 5), and skin tone has 1 more (total of 3, from normal to very dark). Hair color was not similarly expanded as it is not used at this time.

### CODE REVIEW

**Comment by Tranberry** [comment]
I'm so glad that this is done, you have no idea.

**Comment by koosemose** [comment]
Minor color issue I've got to sort out.

**Comment by UnknownSoldier1** [comment]
Looks really, really good.

**Comment by koosemose** [comment]
Gotta sort out some more color issues

**Comment by Tranberry** [comment]
char1_spacesuit

5 step shaded visor proposal - with this it will be simpler to have individual coloured visors I believe.

**Comment by ComputerOverlord** [comment]
Is eye color a thing?

**Comment by koosemose** [comment]
Not currently. And, personally, I'm not certain such a small detail is worth having a variation in colors, and generation of an appropriate range.

**Comment by mikejbrown** [comment]
Personally I'm not sure I'd trust a space helmet that can slide up to keep the air in. But hey... they've got Quillcorp gear, right?

**Comment by ComputerOverlord** [comment]
@mikejbrown I would trust it even less if it was by QuillCorp...

**Comment by mikejbrown** [comment]
Looks good. No obvious new bugs. Merging.

**Pull request merged**
