### PR TITLE
Implemented time scale controls

### PR DESCRIPTION
**Pull request by QuiZr**
Later there should be something like KeyboardController or InputController which controls all input and gives user option to rebind them.
Also, there should be some visual identifier but some of the pull requests already have modified the main scene so I don't want to make merging all of this even harder.

### For now keys are hardcoded:
Key(s) | Function
--- | ---
Spacebar | Pauses/Unpauses the game
Alfanumeric/Keypad 1 | Set time scale to 1x
Alfanumeric/Keypad 2 | Set time scale to 2x
Alfanumeric/Keypad 3 | Set time scale to 4x
Alfanumeric/Keypad +/- | Cycles through avaible timeScale. For now hardcoded: 0.1x, 0.5x, 1x, 2x, 4x, 8x.

### CODE REVIEW

**Comment by Tranberry** [comment]
I would add '+' to increase and '-' to decrease time scale.

**Comment by QuiZr** [comment]
@Tranberry Done, a little bit messy but oh well, should work fine.

**Comment by svmnotn** [comment]
@QuiZr you might want to fix the conflicts by updating your branch to the latest version of the master in this repo so that it is easier for @quill18 to merge the PR.

**Comment by QuiZr** [comment]
@svmnotn Will do but first I'm fixing #46

**Comment by QuiZr** [comment]
Done, safe to merge

**Comment by QuiZr** [comment]
Sorry for that >.> Save to merge now.

**Comment by ComputerOverlord** [comment]
Yes! Should be added for sure!

**Comment by quill18** [comment]
Nice!

**Pull request merged**
