### PR TITLE
StyleCop-ed : Better character animation

### PR DESCRIPTION
**Pull request by Raketfart**
Cleaned up Character Animation, and made a generic Animation class.
This now supports a spritesheet with and without helmet.
It still needs real graphics, and a fix for doorways not belonging to a room.

### CODE REVIEW

**Comment by Tranberry** [comment]
I've made PR directly to your branch, should work I hope.

**Comment by Raketfart** [comment]
This is ready for merge. @Tranberry added new spritesheet, so the character will remove the helmet indoors. I set the O2 requirement very low, because the starting spaceship can't currently produce enough oxygen for anyone to see the changes.

**Comment by Mizipzor** [comment]
This branch has conflicts that must be resolved, probably due to the huge StyleCop cleanup that just happened. Fix them and remove the `[Conflicts]` tag. :)

**Comment by Raketfart** [comment]
Conflict resolved

**Comment by Mizipzor** [comment]
Looks good. Seems like it also fixed that itchy issue where characters were sometimes facing the wrong way when opening doors. And I even saw him taking his helm off! :)

**Comment by Raketfart** [comment]
Yes, i fixed a bug with sprite flipping in this branch.

**Pull request merged**
