### PR TITLE
A few Audio Manager changes

### PR DESCRIPTION
**Pull request by TomMalbran**
1. Moved the Audio loading to ModManager.
2. Moved the file AudioManager to Models/InputOutput.
3. Removed unwanted metas.

### CODE REVIEW

**Comment by TomMalbran** [comment]
That was fast. Hehe

**Comment by sboigelot** [comment]
The power of git aliases

**Comment by TomMalbran** [comment]
I forgot to commit a file. I just noticed the pending change. Will do a PR with that fix.

**Comment by sboigelot** [comment]
Strange, everything works, at least I have sound and they play

**Comment by TomMalbran** [comment]
Is becaue now it loads everything twice. I forgot to commit the WorldController change which removed the old loading. Which was strange since I always add all the files I changed. I think I forgot to save it before commiting.

**Comment by sboigelot** [comment]
@TomMalbran  ping me in the PR, I'll have a look directly

**Pull request merged**
