### PR TITLE
Fixed bug in save dialog from the delete button

### PR DESCRIPTION
**Pull request by alexisfcote**
Delete button does not show in the save dialog. By design or by mistake of #194. I added a quick fix to check if GO is found. A proper refactor of the delete button might be in order.

### CODE REVIEW

**Comment by alexisfcote** [comment]
It messed with my double click code.

**Comment by henninglive** [comment]
You should maybe run the auto formatter on the whole file. The indentation is messed up.

**Comment by SquareMan** [comment]
Just looks as if your tab settings are set to 3 spaces instead of 4. I'm not sure if this would prevent this being merged or not but you should try to fix that.

**Comment by henninglive** [comment]
no, the whole file is messed up, also lines that have not been touched by his commit.

**Comment by quill18** [comment]
Merging this, but yeah it looks like we need to run a format pass on this file after.

**Pull request merged**
