### PR TITLE
Deconstruct Button fix

### PR DESCRIPTION
**Pull request by Dan54**
Fixes Deconstruct button

### CODE REVIEW

**Comment by abackwood** [comment]
Tested. Furniture can be deconstructed again.
Backwood seal of approval

**Comment by RodRitter** [comment]
Tested as well and it looks good. Is it necessary to modify the deconstruct button scene object?

**Comment by dustinwloring1988** [comment]
You should not have to change the unity scene just if you got rid of the blank refreance on the button. Note that the PR i have posted has this fix in it.

**Comment by Dan54** [comment]
@dustinwloring1988 Your fix is better - closing.

**Pull request closed without merging**
