### PR TITLE
Gives the Editor folder a structure that mimics Scripts

### PR DESCRIPTION
**Pull request by zwrawr**
Editor folder now has a folder structure that mimics scripts

### CODE REVIEW

**Comment by zwrawr** [comment]
screen shot , this will keep unit test organised in the future.

**Comment by vogonistic** [comment]
Unity removes 15 .meta files after I apply this change. Can you take a look at that?

**Comment by zwrawr** [comment]
I cannot replicate that, I closed and reopened unity and even re-imported all assets. No meta files where changed or deleted for me.
  
Do you know which meta files were effected.

**Comment by bjubes** [comment]
I can confirm the 15 deleted meta files
capture

**Comment by zwrawr** [comment]
I think i've figured it out , Git doesnt seem to track empty folders. So you never get some of the folders and so unity deletes the meta files for those folders that dont exist.

**Comment by bjubes** [comment]
fixed! not getting any meta files deleted

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
