### PR TITLE
Missing texture sprite

### PR DESCRIPTION
**Pull request by NogginBops**
Also fixed a bug where objects that link to neightbours wouldn't get any
preview sprite.

Old:
image
New:
capture1

### CODE REVIEW

**Comment by GamerInspired** [comment]
Any chance of a before and after image?

**Comment by NogginBops** [comment]
@GamerInspired Sorry, forgot. Will add one in a few minutes.

**Comment by GamerInspired** [comment]
That's fine, just it's good common practice so it helps people understand what it was like before. Also means it will help the person who will accept or decline something know what you have done more easily.

**Comment by NogginBops** [comment]
@GamerInspired Done!

**Comment by WardBenjamin** [comment]
Code looks good, but I would either rebase your commits to be based off of current master, or squash it so that there isn't a bunch of merge commits.

**Comment by NogginBops** [comment]
@WardBenjamin I had some problems with git yesterday that meant I could not do that. I will try and do it today though.

**Comment by vogonistic** [comment]
Don't forget to rebase the PR

**Comment by NogginBops** [comment]
@vogonistic I think I sorted it out now. Though I can't reopen this.

**Comment by NogginBops** [comment]
@RodRitter Could you have a look, since you are active?

**Comment by NogginBops** [comment]
Oh sorry I will make a new PR

**Comment by NogginBops** [comment]
@vogonistic I have made a new PR. #418

**Pull request closed without merging**
