### PR TITLE
Jobs created by dragging over several tiles now added to the queue in…

### LINKED ISSUE #1100: Tasks should be added as a "Snake" [Easy]
When building square shapes, like a huge patch of floors, the build pattern is really inefficient. The tiles should be added as a "snake", for even rows they should go from the bottom up, for odd rows from the top down. This would make building such shapes vastly more efficient. I know the job system is going to be re-written, but it helps to queue the jobs in the right order first, which this will reduce movement time considerably.
gif

### PR DESCRIPTION
**Pull request by jaselito**
… a snake pattern.

resolve #1100

### CODE REVIEW

**Comment by crafty-geek** [comment]
Consider adding a comment (or appending to the comment on line 407) to explain that those vars facilitate the efficient snake pattern.  it's a little hard to intuit that from reading the code as written.

**Comment by NogginBops** [comment]
@jaselito A screenshot would be appreciated.

**Comment by bjubes** [comment]
Just tested this, it works great!
snake

**Comment by jaselito** [comment]
Made the comment clearer as requested.  Thanks for the screencap @bjubes !

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
