### PR TITLE
Add world speed controls

### PR DESCRIPTION
**Pull request by ZadkielSantospirito**
Adds world speed controls to the top left corner of the UI and a set
world speed function to the WorldController

### CODE REVIEW

**Comment by BeefEX** [comment]
Speed control is already implemented.

**Comment by ComputerOverlord** [comment]
Please upload UI image

**Comment by WardBenjamin** [comment]
This is already completed, see [Lines 43 through 48](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/Controllers/WorldController.cs#L43) and [Lines 76 through 137](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/Assets/Scripts/Controllers/WorldController.cs#L76).

**Comment by quill18** [comment]
We don't have a visual representation for it yet (just hotkeys 1, 2, 3, +, -) -- but otherwise speed controls have been implemented. Closing this -- but feel free to make a new PR for the UI implementation.

**Pull request closed without merging**
