### PR TITLE
Hotfix/game tick

### PR DESCRIPTION
**Pull request by sboigelot**
I know it may not change much to #796 but it may help in the overall

Reduce the amount of LUA call to furniture to X (5 currently) times a second by creating a GameTick

(not sure if this is a hotfix but I'll call it like that anyway for now)

### CODE REVIEW

**Comment by vogonistic** [comment]
Is this compatible with the speed control? Bound to 1, 2 and 3 on the keyboard.

**Comment by sboigelot** [comment]
Yes this still use the TimeScale variable, so speed still works

**Comment by vogonistic** [comment]
Looking at your commits, it looks like you merge `upstream/master` into your `master`. Is that correct?

If so, next time you are on master *with no local changes*. Run these commands: `git fetch upstream; git reset --hard upstream/master`. It'll take your `master` and forcibly move it to the same commit as `upstream/master` and it'll look a little better on github after that.

**Comment by sboigelot** [comment]
@vogonistic I just executed the git bash commands. It doesn't seems to have affected my other PR for now, but may affect my future ones. Thanks a lot for the tip, maybe we should have a explanation about it in the contribution file. I tried to solve this issue alone a few time without success. (First time I'm working on a forked repo)

**Comment by vogonistic** [comment]
Yeah, it affects only the new PR's.

**Comment by vogonistic** [comment]
Although, if you see this again, ping me and we'll figure it out.

**Comment by Randshot** [comment]
@vogonistic Isn't fast-forwarding enough (after fetching upstream)?

**Comment by vogonistic** [comment]
@Randshot It is, unless you are already in a state like this, then you can't fast-forward because you already have merged earlier.

**Comment by sboigelot** [comment]
@Randshot   fast-forwarding? How do you do that?

**Comment by Randshot** [comment]
@sboigelot I think something like this: `git pull -ff master`
Basically something with '-ff'.

**Comment by Skalicon** [comment]
@sboigelot for future reference a hot fix is a bug fix that goes directly from the production code (usually master) and merges directly back into the production code. Since we haven't released the game yet nothing we do should be considered a hotfix, this is just a regular old bugfix :)

**Comment by sboigelot** [comment]
@Skalicon oki doki! I'll keep it in mind, thanks

**Pull request merged**
