### PR TITLE
Show compile errors clearly in Travis CI

### PR DESCRIPTION
**Pull request by bjubes**
Test.sh now parses unity's log file from a failed build and repeats the console output at the end of the build for easy access to errors. 

Previously the compiler errors from a build were logged, but 300 lines above where the build actually reports failing, making finding errors very difficult.

Sample output of a failing build:
after

### CODE REVIEW

**Comment by bjubes** [comment]
when this pr is merged I will work on the next logical step: logging the specific unit test that fails, similarly to how this pr logs compiler errors.

**Comment by TomMalbran** [comment]
@bjubes is the output supposed to be a single line, or are the line breaks not parsed properly?

**Comment by bjubes** [comment]
the latter, fixing now

**Comment by TomMalbran** [comment]
Great. Because the output in the screenshot was hard to read as a single line.

**Comment by bjubes** [comment]
I agree. here is a build of a branch that is rebased off this one, but introduces a compile error.
https://travis-ci.org/bjubes/ProjectPorcupine/builds/157542961
you can see the new output

**Comment by TomMalbran** [comment]
Is the output correct? There is way too much stuff.

**Comment by bjubes** [comment]
no that output is just the entire file. I thought removing one simple thing would fix the problem but that's not the case....

**Comment by bjubes** [comment]
should be multiline now. Here's the new test with a compilation error.
https://travis-ci.org/bjubes/ProjectPorcupine/builds/157546340

**Comment by TomMalbran** [comment]
That looks better. Small extra improvement: maybe add an extra line before and after "Build Failed!", or maybe just before.

**Comment by bjubes** [comment]
yeah that looks cleaner. Ill update the original image too

**Comment by vogonistic** [comment]
Is this PR ready to be merged?

**Comment by bjubes** [comment]
yes

**Comment by vogonistic** [comment]
Merged!

**Pull request merged**
