### PR TITLE
[Conflict] Ui redesign

### PR DESCRIPTION
**Pull request by alexfriesen**
I made some progress with the Options Dialog like explained in #956 

Here a preview 
pulllllllllllll

### CODE REVIEW

**Comment by TomMalbran** [comment]
I like it. But I think that adding some transparency to the background color, might make it look better.

**Comment by alexfriesen** [comment]
like that?
pull_trans

**Comment by TomMalbran** [comment]
Yes. i like that better than before.

**Comment by Tranberry** [comment]
looks good, as long as you don't go crazy with the transparency

**Comment by Mizipzor** [comment]
That transparency has a huge impact on the looks, I love it. Normally you have to strike the tricky balance, you want the transparency effect to be clearly visible, but not so much that it makes text difficult to read. We dont have that problem because we framed our buttons. I think you can go harder on the background but keep the button a bit more opaque. Does that make sense? Maybe youre already doing that, hard to tell with the color.

**Comment by alexfriesen** [comment]
In summary: 
 - settings are moved from the bottom menu to the options menu
 - the debug buttons are removed from the options menu (they didnt work anyway)

After I resolved the merge conflicts this might be ready to be merged.

**Comment by alexfriesen** [comment]
PROGRESS!
pp_menu

**Comment by sboigelot** [comment]
I love it, but be careful not to make too much change in this PR. At one point, decide to stop so we can merge it and start a new one.

Also, conflict ;)

**Comment by TomMalbran** [comment]
Looking good so far. I would make the construction menu title look like the options one, or change both so that they look the same.

If we are going to merge this partial design which would be great and then continue with more changes, I think that we should still try to keep a category (Furniture/Floors) / buildables structure in construction for a better organization.

**Pull request closed without merging**
