### PR TITLE
Unreachable Job Fix

### LINKED ISSUE #1536: [Bug] Unreachable Wall job loop
Characters stuck in a constant loop of bringing a steel to the unreachable Wall job and then taking it back.
untitled

...on the picture above: Blue guy just standing still, others are coming with the pieces of steel to where the Blue guy standing, spazzing out and go back to a stockpile. I think it might have something to do with a not canceled job.

It was reachable, but somebody put a walls that covered this spot, when Blue guy was walking to it (if I remember correctly).

### PR DESCRIPTION
**Pull request by Geoffrotism**
Fixes #1536, #1545, #1602 
Fixes when characters cant reach jobs and go into infinite loops.
- [x]  Figure out why jobs arent readded to the queue when a path changing event occurs.
- [x]  Fix: Half of jobs being created in unreachable areas are "deleted".
- [x] Address characters going to pick up inventory before realizing there isnt a path to the job site.
- [x] Small bug where characters aren't picking up build jobs that had inventory requirements that were unreachable. 
- [x] Fix: drag and drop jobs getting deleted.
To recreate: add build wall job somewhere (reachable). then add a stack of steel (unreachable). queue job to deconstruct wall (to make steel reachable). Wall should be deconstructed but the current characters will not do the build job (new characters that spawn in will pick it up though).

### CODE REVIEW

**Comment by dusho** [comment]
true, there is something weird.. some jobs got lost
image

**Comment by Geoffrotism** [comment]
I was a dummy. Was removing a job from the JobQueue when using the Enqueue method. should be all fixed. Just need to do stylecop. @dusho @koosemose Is there anything else I should address with jobs in this PR?

**Comment by koosemose** [comment]
Just focus on the main point of the PR. We can do saving/loading of jobs in another PR

**Comment by Geoffrotism** [comment]
Ready for testing.
Note: if you do stuff with unreachable stockpiles there will be a huge FPS problem but this is due to pathfinding AFAIK.

**Comment by koosemose** [comment]
First issue I notice, is that they still go to pick up the inventory before abandoning the job, and are now stuck with that inventory. Aside from the being stuck with inventory issue (which is separate from this), could you look into having them figure out they can't get to the job before getting inventory for it?

**Comment by Geoffrotism** [comment]
sure can.

**Comment by koosemose** [comment]
Not optimal, of course. But it works for now.

**Comment by bjubes** [comment]
Remove `[Conflicts]` from the title when you fix the merge conflicts.

**Comment by koosemose** [comment]
You've got failures, it looks like you had conflicts in Prefab.meta, and still have the HEAD>>> and such lines in it, guessing from the errors reported.

**Comment by koosemose** [comment]
Now your builds failing with the following error:
```
Assets/Scripts/State/JobState.cs(69,29): error CS1061: Type `Job' does not contain a definition for `charsCantReach' and no extension method `charsCantReach' of type `Job' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by Geoffrotism** [comment]
Almost done with this PR, some things to note. 
* Unreachable inventory creates a HUGE slowdown, especially since stockpiles are separate tiles (so the original base does 6 path finding calculations for unreachable hauling jobs.)

* Some of the perceivable lag is due to the IdleState where characters only try to pick up the job after a random amount of time between 0.5f and 2f.

The last thing to do is fix a bug described in the OP.

**Comment by Geoffrotism** [comment]
StyleCopped and ready to go. Time spent finding path to unreachable inventory is a problem but is outside the scope of this PR.

**Comment by Geoffrotism** [comment]
All done, terrible lag for unreachables though due to using dykjstra over the whole map, switching to A* pathfinding to nearest inventory, bi-directional searching, and metastockpiles will help with that though.

**Comment by bjubes** [comment]
You have merge conflicts. hopefully the mdb file wont give you trouble. I don't know why git doesn't just overwrite the meta files like it usually does.

**Comment by BraedonWooding** [comment]
I got these exact conflicts like 10s ago, I fixed it by merging in upstream like you normally would then just press clear errors in the Unity Console, and then just commit the changes, you shouldn't need to make any changes, the clear error is just to make sure it doesn't have any access errors and it should overwrite the metas/mdb files (thus fixing the conflict), then just push 😃

**Comment by Geoffrotism** [comment]
fixed conflicts, ty @BraedonWooding

**Pull request merged**
