### PR TITLE
Added functionality to remove the designation of furniture

### PR DESCRIPTION
**Pull request by gunthergun**
If you had a bunch of jobs, you could not remove any of the designations

### CODE REVIEW

**Comment by RodRitter** [comment]
No files were changed

**Comment by gunthergun** [comment]
Oops must have missed the commit

**Comment by Mizipzor** [comment]
I dont know if you are aware, but you can see a list of changes as youre creating the pull request, before its actually sent. That would have helped you avoid this. :) This is something @quill18 realized he didnt bring up in his video (after feedback). Try again. Ill help you if you want. :)

**Comment by gunthergun** [comment]
now there should be changes

**Comment by RodRitter** [comment]
Tested it and it works nicely. Good work!

**Comment by WardBenjamin** [comment]
Good change! This is something we've needed for a while.

**Comment by gunthergun** [comment]
Thanks ! :) I am amazed how fast it got approved :D

**Pull request merged**
