### PR TITLE
Click-able link to CONTRIBUTING.md from README.md

### PR DESCRIPTION
**Pull request by Tranberry**
Easy access to CONTRIBUTING.md from README.md for lazy people.

Eg. making CONTRIBUTING.md clickable in the README.md

### CODE REVIEW

**Comment by QuiZr** [comment]
TIL that you can link to other files in repo!

**Comment by Tranberry** [comment]
It's a handy feature for lazy people like me

**Comment by Tranberry** [comment]
Oops git n00b

**Comment by NogginBops** [comment]
@Tranberry You should probably make another PR with the original changes.

**Pull request closed without merging**
