### PR TITLE
[UI] Build menu closes after selecting furniture to build

### PR DESCRIPTION
**Pull request by frankitox16**
Pretty straightforward... (that commit name was unintended, got a couple of troubles getting used to git bash ^^)

### CODE REVIEW

**Comment by svmnotn** [comment]
alt text

Not sure if this is the exact behavior that is desired however.

**Comment by frankitox16** [comment]
@svmnotn what do you mean? any weird things happening? that line of code should hide te Build [furniture_name] buttons, that's all...

**Comment by svmnotn** [comment]
No, there is nothing wrong with it, I'm just not sure if that is the behavior that is desired. But, it is not up to me to decide that.

**Comment by vogonistic** [comment]
I like it. We can revert it if people dislike it.

**Pull request merged**
