### PR TITLE
Fix controller logging (part 1)

### PR DESCRIPTION
**Pull request by mikejbrown**
Related to #710 

Fixes logging calls in BuildModeController, CharacterSpriteController, FurnitureSpriteController, and GameEventManager to use UberLogger.

I also took the opportunity to make a few StyleCop changes (mostly whitespace).

### CODE REVIEW

**Comment by mikejbrown** [comment]
Resolved conflicts

**Comment by Mizipzor** [comment]
Sorry, now has conflicts again. :/ Try to find us on discord, maybe we can merge this as soon as you fix it.

**Comment by mikejbrown** [comment]
Fixed conflicts

**Comment by mikejbrown** [comment]
Fixed conflicts again

**Comment by Mizipzor** [comment]
This keeps getting conflicted by other stuff, marking it as high priority because I assume youre getting tired of fixing those. :P

**Comment by mikejbrown** [comment]
That should do it!

**Comment by Mizipzor** [comment]
Tested. Game starts without errors.

**Pull request merged**
