### PR TITLE
Allow disabling saves of ScheduledEvent. Fixes #1180.

### LINKED ISSUE #1180: Scheduler- Add an option to not save event on load
Some events, such as the HeadlineGenerator, really shouldn't be saved, as they interact with UI elements. There should be an option to not save those types of events. Related to #1175 .

### PR DESCRIPTION
**Pull request by mikejbrown**
Fixes #1180 
Adds a `bool ScheduledEvent.IsSaveable` flag which is checked by `Scheduler` before serializing the event.

Also adds documentation comments per #1126. :grinning:

### CODE REVIEW

**Comment by bjubes** [comment]
can you also make the Headline Generator use the IsSaveable flag. This will close the issue as opposed to just making a system for someone else to close it (ie. will never get fixed)

**Comment by mikejbrown** [comment]
@bjubes I prefer to make PRs touch as few systems as possible, but it's done.

**Comment by bjubes** [comment]
I understand wanting to make a PR small, but when you make a fix, you should implement it too. otherwise we end up with tons of systems that no ones knows exist because their not in use anywhere in the project

**Comment by bjubes** [comment]
Thanks for the fix!

**Pull request merged**
