### PR TITLE
Galactic Market

### PR DESCRIPTION
**Pull request by sboigelot**
Galactic Market - A multiplayer aspect for item and resource gathering! No longer you'll have to trade with these elves merchant! Kill them all and trade with your fellow players!

Galactic Market is a wip feature allowing player to access a multi-player trade network.

Currently the branch include the following feature:

- A mongodb database & data access layer to the database via unity.
- Some basic database entity:
- - Orders
- - Transactions
- - Trader
- A new furniture, no real visual for no, just a copy from the miner with text change
- A scaffold way to interact with furniture (currently only c# methods, no lua)
- change to the scene , oups, sorry, but I duplicated the scene to keep the original
- - A new Ui button to interact with furniture
- - a new Galactic Market DialogBox listing all orders in the database and allowing the user to trade
- - - currently only buying will spawn item, I have issue setting a haul job to sell

.Short-ish time Planned additional feature for the Galactic Market:

- Use currency, for now everything is free, sell & by doesn't make sence
- - this will requiere user log/pwd to the market
- Transport fee & delivery times (choose your own transport company)
- Saving transaction & trade history, for the lover of data and market optimisation

Long-ish time Planned additional feature:

- Build your own trade ship and delivery company, use fuel to complete hauling contract for a profit
- and whatever the community creativity will provide

Screenshots:
image

image
image

after buying 10
image

Why do I request a merge now?

I don't know much about this project, I didn't follow many of the tuto from Quill18, I mostly follow his LP channel. (Even though I really love the existence of Quill18create!)

As a result, I really have a small knowledge about the codebase of the game and struggle with simple concept like creating a haul job :)

I prefer sharing the current state of the feature so we can all start improving it instead of going in the wrogn direction for month before realizing my work was useless.

Additional info:

Unfortunatly using mongo db force us to switch the player settings of unity to a full .net stack. I  don't know what would be the impact of this on platform other then windows, but we can search for a solution. (Hosting a rest-api that mediate the communication between the game and the db is an option for instance)
required unity project player setting to use monodb

ProjectPorcupine\Assets\Scripts\Utilities\GalacticTradeNode\mongolabcredidentials.txt contains all info to login to the current db

### CODE REVIEW

**Comment by ComputerOverlord** [comment]
Sorry but, I don't see this happening.

**Comment by henninglive** [comment]
You should use a embedded database for this, something like sqlite. Using mongodb is overkill.

**Comment by sboigelot** [comment]
Yep I saw, I'm investigating them.

Can you elaborate why you don't see this happening You don't like the feature your have concern about the technology?


*edit*
Mongodb allow us to have a share database between all player without having to create our own db host. However I don't mind a switch to sqlitle (I love sqlite). It should'nt be embedded though, as we need one db for all players.

**Comment by henninglive** [comment]
If you want all players to trade with each other online we would have to implement a standalone web service to facilitate this. The service would be backed by a db, but we should not gave all clients direct access to the db. Anyway, this is way out of scope for this project.

**Comment by sboigelot** [comment]
Yep the rest-api mediator approch is described in the merge description. I just didn't do it yet.
But anyway, I had fun tonigth with it even if it's not merge. I thougth it was a cool idea for a rim-world-ish DF-ish game to have inter-player trader, I guess I'm the only one :disappointed:

**Comment by henninglive** [comment]
it's cool idea, but is way too early.

**Comment by ComputerOverlord** [comment]
Yeah, too early, and it looks like a multiplayer feature... which both should not happen for a game like this, and isn't even in.

**Comment by vogonistic** [comment]
@sboigelot Can you split this PR into two separate ones?

The trading system looks fantastic! It should be able to work on it's own for people who aren't connected to the internet or just plain doesn't want to. If the PR didn't have any other issues, we'd probably merge it on the spot. Maybe add random interval traders like in Rimworld as a start?

Secondly you should open an issue to discuss the the multiplayer trading system. Not everybody wants to play an always online game and it would be great to go over that more. We also need to investigate what the switch to .NET involves and discuss the MongoDB hosting, if that is the right database for it. We haven't started discussing multiplayer yet. I think it's too early to start merging it.

Awesome work!

**Comment by ComputerOverlord** [comment]
My idea for a trading system: #332

**Comment by sboigelot** [comment]
@vogonistic Thanks!

Unfortunatly about splitting the PR, there is not much to the trading system beside the online market. The UI is just a panel and a lot of people will do much better very quick  I could work on another one one day, but I was mostly exited by the multi player trade. I'm bored of the rimworld trader, always the same price, no real market dynamic; So I'm not feeling like re-creating it. But I'm sure a lot of people will love working on that.

> Not everybody wants to play an always online game 

I understand this, but no one force the player to build the furniture to access the online market. The connection is only active while opening the furniture screen.

>  We also need to investigate what the switch to .NET involves and discuss the MongoDB 

This is very temporary until we have a "middle man" api, we will just have to make web http get/post request, but no point to fix it if the feature is not interesting for most people. That's the reason I made the PR, not code too much for nothing. Stop before it's too late

**Comment by ComputerOverlord** [comment]
@sboigelot Solution: S&D System

**Comment by vogonistic** [comment]
@sboigelot I'd still love to see the trading system, even if it's just a simple panel with fixed prices that you can bring up on demand. It gives people a starting point for adding random intervals, more resources and think up new awesome ideas. If you can avoid changing the scene, you'll get some extra plus points from me.

**Comment by sboigelot** [comment]
@vogonistic Ok, I'll look into it this week end, but i'ts 2 am here and I need to sleep :) It should be will be easy to extract that part of the code into a separate branch and make the necessary changes to a copy of the scene.

**Comment by vogonistic** [comment]
@sboigelot No rush! I'll happily review it when you have something for me.

**Comment by vogonistic** [comment]
I'm closing this PR. Looking forward to one with just the trading system!

**Pull request closed without merging**
