### PR TITLE
Localization quick fix

### PR DESCRIPTION
**Pull request by relinu**
Adds localizationLoader to controllers-object and one additionalValue to the key.

### CODE REVIEW

**Comment by relinu** [comment]
Can't remove the other 5 files, otherwise git throws an error. :/

**Comment by Mizipzor** [comment]
In 2a1e27c you replaced every end of line character in those files. And thats the only thing you did in that commit. You should consider deleting it.

**Comment by relinu** [comment]
I don't know why but i did not change those files and i can't discard the changes done to them.

**Comment by Mizipzor** [comment]
You can absolutely change that, what makes you think you cant? You can:

1. Make another commit that is essentially the inverse and push it here. It's the easiest but least clean.
2. Make said commit and rebase/squash this branch to make it look like you never touched those files to begin with. This is the cleanest but most difficult.
3. Close this pull request and start over, copy pasting you changes. Very easy, very clean.

**Comment by relinu** [comment]
I fork from the master, then clone it to my PC (Windows) and these changes are there. A change to the .gitattributes 
> #* text=auto 

would help :/

**Comment by Mizipzor** [comment]
It is possible that the files were initially committed with the wrong eol characters and your git is correctly configured and "corrects" them. But if this is the case, it most certainly shouldnt happen as part of your pull request. I actually dont know if there's an agreed eol standard, I just assumed there was. Is there anything in the docs?

**Comment by relinu** [comment]
Got it ^^'

**Comment by Mizipzor** [comment]
#143 attempts to solve it. I'm trying to figure out if there's been a designated default for this project.

**Comment by Mizipzor** [comment]
@relinu whats going on now? Seems like youve started working on something else and havent created a new branch for it. All commits that goes into the same branch you used to create the pull request is automatically included here. And it's one of the main reasons why you never, ever should work directly on you master branch.

**Comment by relinu** [comment]
These are also loccalization changes and fixes the save/load dialog wasn't translated correctly and the translation for the power generation was missing completely. I still have some issues with the license files so i can't work on something diffrent without pushing it to this PR ^^'

**Comment by Mizipzor** [comment]
> i can't work on something diffrent without pushing it to this PR

That would be horrible if it's true and not very git-like. What is your issue with the license files? Lets fix that. Is there and issue for it?

**Comment by relinu** [comment]
As mentioned above i can't discard the changes to the license files ^^' Found a workaround to push "without" them, but I canT remove them from the GitHub GUI

**Comment by quill18** [comment]
This branch has conflicts that must be resolved.

**Pull request closed without merging**
