### PR TITLE
New settings xml file

### PR DESCRIPTION
**Pull request by zwrawr**
a new branch and PR becuse of messy commits in previous branch #121

Added a static Settings class that reads in settings from Settings.xml ,
values of these can be accessed via Settings.getSetting(string key)

Changed world controller to use this system when making a new world.
World size is now controlled by Settings.xml

Adds a couple of debug statements that only log once.

implements settings file as suggested in #21

### CODE REVIEW

**Comment by Mizipzor** [comment]
You should be able to preview the branch on your fork before making a pull request if you want to experiment with what commits show up. :)

**Comment by zwrawr** [comment]
I believe i've figure out how to use git well enough to not have all these merges show up in the future , but i don't know how i would go about removing them from this PR/branch so i'm just going to leave them for now.

**Comment by henninglive** [comment]
This pull request does follow the style guidelines, you are using tabs instead of spaces indentation. please take a look at the [style guidelines](https://github.com/TeamPorcupine/ProjectPorcupine/blob/master/CONTRIBUTING.md#style-guidelines).

**Comment by vogonistic** [comment]
@zwrawr If you update the indentation, I'll merge this PR.

**Comment by zwrawr** [comment]
I'll take a look this afternoon and clean up the style.

**Comment by zwrawr** [comment]
looks like git changed the line endings in some files for me :'(

**Comment by zwrawr** [comment]
closed , new PR and branch #401

**Pull request closed without merging**
